---
title: "PFAS_water"
author: "Savanah Leidholt"
format: html
editor: source
---

```{r}
library(ggplot2)
library(tidyverse)
library(janitor)
library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)
library(emmeans)
library(ggeffects)
library(patchwork)
library(gWQS)
library(corrplot)
library(gt)
library(table1)
library(stringr)
library(ggpubr)
library(jsonlite)
```

```{r}
#directories
user <- Sys.info()[["user"]]

if (user == "leidholt") {
  root_path <- c("/mmfs1/gscratch/togo/leidholt/")
  git_path <- "/mmfs1/gscratch/togo/leidholt/CHCO-Code/"
  keys <- fromJSON("/mmfs1/home/leidholt/keys.json")
  
} else if (user == "sleidholt") {
    root_path <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/")
    dir.results <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/PFAS/Results/")
    git_path <- "/Users/sleidholt/Documents/GitHub/CHCO-Code/Petter Bjornstad/PANTHER PFAS/"
    keys <- fromJSON("/Users/Shared/OneDrive - UW/Personal_storage/keys.json")
    
} else if (user == "savanahleidholt") {
    root_path <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/")
    dir.results <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/PFAS/Results")
    git_path <- "/Users/savanahleidholt/Desktop/CHCO-Code/Petter Bjornstad/PANTHER PFAS"
    keys <- fromJSON("/Users/savanahleidholt/OneDrive - UW/Personal_storage/keys.json")
    
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r}
dat_raw <- read.csv(fs::path(root_path,"Data Harmonization","Data Clean","harmonized_dataset.csv"),na.strings = "")
lod_raw <- read.csv(fs::path(root_path,"/PANTHER/Data_Raw/PFAS Emory 2025/8- PFAS Quantification/PFAS_LODs.csv"))
```


