---
title: "EDIPE analysis"
author: "Laura Pyle"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-expand: true
    number-sections: true
    number-depth: 4
    embed-resources: true
    echo: false
    warning: false
---

```{r include = F}
# =============================================================================
# LIBRARIES
# =============================================================================
library(dplyr)
library(arsenal)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(ggalluvial)
library(FSA)
library(fuzzyjoin)
library(purrr)
library(stringr)
library(arsenal)
library(Hmisc)
library(SomaDataIO)
library(caret)
library(survival)
library(broom)
library(openxlsx)
library(readxl)
library(knitr)
library(limma)
library(gtsummary)
library(cardx)
library(forestploter)
library(forcats)
library(fgsea)
library(car)

# specify user for paths
user <- Sys.info()[["user"]]
if (user == "laurapyle") {
  data_path <- "/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Piani/Data_raw"
  results_path <- "/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Piani/Results"
} else if (user == "lpyle") {
  data_path <- "/Users/lpyle/Library/CloudStorage/OneDrive-UW/Piani/Data_raw"
  results_path <- "/Users/lpyle/Library/CloudStorage/OneDrive-UW/Piani/Results"
} else if (user == "pylell") {
  data_path <- "/Users/pylell/Library/CloudStorage/OneDrive-UW/Piani/Data_raw"
  results_path <- "/Users/pylell/Library/CloudStorage/OneDrive-UW/Piani/Results"
} else {
  stop("Unknown user: please specify root path for this user.")
}


```

```{r functions, include=FALSE}
clean_variable_names <- function(data) {
  # Get current names
  old_names <- names(data)
  
  # Create new names
  new_names <- gsub(" ", "", old_names)           # Remove spaces
  new_names <- gsub("-", "_", new_names)          # Replace hyphens with underscores
  new_names <- gsub("[()]", "", new_names)        # Remove parentheses
  
  # Apply new names
  names(data) <- new_names
  
  # Optional: Print what changed for verification
  changed <- old_names != new_names
  if (any(changed)) {
    cat("Changed variable names:\n")
    for (i in which(changed)) {
      cat(sprintf("  '%s' -> '%s'\n", old_names[i], new_names[i]))
    }
  }
  
  return(data)
}

domod <- function(data, outcome, predictor){
  data <- as.data.frame(data)
  form = as.formula(paste0(outcome,"~", predictor))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  summary(mod)
}

domod_adj <- function(data, outcome, predictor, covariate){
  data <- as.data.frame(data)
  form = as.formula(paste0(outcome,"~ visit + per_wtloss"))
  mod <- lme(as.formula(form),random=~1|subject_id,data = data,na.action = na.omit, correlation = corCompSymm(form = ~1|subject_id))
  anova <- anova.lme(mod, type="marginal")
  m <- emmeans(mod,"visit")
  p <- pairs(m,adjust="tukey", simple="each")
  plot_dat <- data$outcome
  return(list(anova,m,p))
}
```

```{r include = F}
# =============================================================================
# READ DATA 
# =============================================================================

setwd(data_path)
data <- read_xlsx("./EDIPE_wide_delta_renamed.xlsx")

data <- clean_variable_names(data)

data$TG_HDL_T1 <- data$TG_T1 / data$HDL_T1
data$TG_HDL_T2 <- data$TG_T2 / data$HDL_T2
data$TG_HDL_delta <- data$TG_HDL_T2 - data$TG_HDL_T1
data$PBR4_25_T1 <- data$PBR4_25
data$PBR4_25_delta <- data$PBR4_25_T2 - data$PBR4_25_T1

# identify outcome variables
outcomes <- c("HDP", "HDPbinary", "GDM", "Neonweight", "Egdelivery", "neonatalsex", "Csection")

# identify predictors
main_predictors_adj <- c("PWVcf_T1", "PWVcf_T2", "PWVcf_delta")
main_predictors <- c("PWVcf_at_85PAM_T1",	"PWVcf_at_85PAM_T2", "PWVcf_at_85PAM_delta", "PBR4_25_T1", "PBR4_25_T2", "PBR4_25_delta")
# PWVcf_T1 and PWVcf_T2 are better adjusted for MAP_T1, MAP_T2, MAP_delta

# yellow are secondary predictors
secondary_predictors <- c("Morphologpulse_T1",	"Morphologpulse_T2", "morphologypulse_delta", "PWVcr_T1",	"PWVcr_T2", "PWVcr_delta", "TG_T1",	"TG_T2", "TG_delta", "APOB_T1",	"APOB_T2", "APOB_delta",	
                          "Lpa_T1",	"Lpa_T2", "Lpa_delta", "CRPhs_T1",	"CRPhs_T2", "CRPhs_delta",
                          "PWVcf_at_85PAM_T1",	"PWVcf_at_85PAM_T2",	"PWVcf_at_85PAM_delta", "AIx75_calc_T1",	"AIx75_calc_T2",	"AIx75_calc_delta", "AvrgSBPsitting_T1",	"AvrgSBPsitting_T2", "AvrgSBPsitting_delta")

# orange are tertiary predictors
tertiary_predictors <- c("AIx_T1",	"AIx_T2", "AIx_delta", "SEVR_T1", "SEVR_T2", "SEVR_delta", "Vasc.Age_T1",	"Vasc.Age_T2", "Vasc.Age_delta", "Car_Rad_PWVsub._T1",	"Car_Rad_PWVsub._T2", "Car_Rad_PWVsub._delta")

# other things that are not highlighted that Fede may be interested in are lipid profile, serum uric acid, serum creatinine ratio, TG/HDL ratio
other_predictors <- c("HDL_T1",	"HDL_T2", "HDL_delta",	"LDL_T1",	"LDL_T2", "LDL_delta", "HDL_T1",	"HDL_T2", "HDL_delta",	"LDL_T1", "LDL_T2", "LDL_delta", "URI_T1", "URI_T2", "URI_delta", "CREA_T1", 'CREA_T2', 'CREA_delta', 'TG_HDL_T1', "TG_HDL_T2", "TG_HDL_delta")

```

# Questions

1) Variable "PBR4_25" did not have a version with "T1", just "PBR4_25" and "PBR4_25_T2". I assume that "PBR4_25" is T1?

# Results

## Descriptive statistics

```{r include=F}
t1 <- data %>%
  gtsummary::tbl_summary(
    missing = "ifany",
    include = c(HDP, HDPbinary, GDM, Neonweight, Egdelivery, neonatalsex, Csection, PWVcf_T1, PWVcf_T2, PWVcf_delta,
                PWVcf_at_85PAM_T1,	PWVcf_at_85PAM_T2, PWVcf_at_85PAM_delta, PBR4_25_T1, PBR4_25_T2, PBR4_25_delta, 
                MAP_T1, MAP_T2, MAP_delta, Morphologpulse_T1,	Morphologpulse_T2, morphologypulse_delta, PWVcr_T1,	
                PWVcr_T2, PWVcr_delta, TG_T1,	TG_T2, TG_delta, APOB_T1, APOB_T2, APOB_delta, Lpa_T1,	Lpa_T2,  
                Lpa_delta, CRPhs_T1,	CRPhs_T2, CRPhs_delta, PWVcf_at_85PAM_T1,	PWVcf_at_85PAM_T2,	PWVcf_at_85PAM_delta, 
                AIx75_calc_T1,	AIx75_calc_T2,	AIx75_calc_delta, AvrgSBPsitting_T1,	AvrgSBPsitting_T2, AvrgSBPsitting_delta,
                AIx_T1,	AIx_T2, AIx_delta, SEVR_T1, SEVR_T2, SEVR_delta, Vasc.Age_T1,	Vasc.Age_T2, Vasc.Age_delta, Car_Rad_PWVsub._T1,	
                Car_Rad_PWVsub._T2, Car_Rad_PWVsub._delta,
                HDL_T1,	HDL_T2, HDL_delta,	LDL_T1,	LDL_T2, LDL_delta, URI_T1, 
                URI_T2, URI_delta, CREA_T1, CREA_T2, CREA_delta, TG_HDL_T1, TG_HDL_T2, TG_HDL_delta
    ),
    type = list(
      c(Neonweight, Egdelivery, PWVcf_T1, PWVcf_T2, PWVcf_delta,
                PWVcf_at_85PAM_T1,	PWVcf_at_85PAM_T2, PWVcf_at_85PAM_delta, PBR4_25_T1, PBR4_25_T2, PBR4_25_delta, 
                MAP_T1, MAP_T2, MAP_delta, Morphologpulse_T1,	Morphologpulse_T2, morphologypulse_delta, PWVcr_T1,	
                PWVcr_T2, PWVcr_delta, TG_T1,	TG_T2, TG_delta, APOB_T1, APOB_T2, APOB_delta, Lpa_T1,	Lpa_T2,  
                Lpa_delta, CRPhs_T1,	CRPhs_T2, CRPhs_delta, PWVcf_at_85PAM_T1,	PWVcf_at_85PAM_T2,	PWVcf_at_85PAM_delta, 
                AIx75_calc_T1,	AIx75_calc_T2,	AIx75_calc_delta, AvrgSBPsitting_T1,	AvrgSBPsitting_T2, AvrgSBPsitting_delta,
                AIx_T1,	AIx_T2, AIx_delta, SEVR_T1, SEVR_T2, SEVR_delta, Vasc.Age_T1,	Vasc.Age_T2, Vasc.Age_delta, Car_Rad_PWVsub._T1,	
                Car_Rad_PWVsub._T2, Car_Rad_PWVsub._delta,
                HDL_T1,	HDL_T2, HDL_delta,	LDL_T1,	LDL_T2, LDL_delta, HDL_T1,	HDL_T2, HDL_delta,	LDL_T1, LDL_T2, LDL_delta, URI_T1, 
                URI_T2, URI_delta, CREA_T1, CREA_T2, CREA_delta, TG_HDL_T1, TG_HDL_T2, TG_HDL_delta) ~ "continuous",
      c(HDPbinary, GDM, Csection, neonatalsex) ~ "dichotomous",
      c(HDP) ~ "categorical"
    ),
    statistic = list(
      gtsummary::all_continuous() ~ "{mean} ({sd}) | {median} ({p25}, {p75})",
      gtsummary::all_categorical() ~ "{n} ({p}%)"
    ),
  ) %>%
  gtsummary::modify_header(label ~ "**Characteristic**") %>%
  gtsummary::bold_labels()
```

```{r}
t1
```

```{r}
# run all models and save to file
res <- NULL
temp <- NULL
# Neonweight
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("Neonweight ~", paste0(main_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Neonweight", paste0(main_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
# PWVcf_T1
form = as.formula(paste0("Neonweight ~ PWVcf_T1 + MAP_T1"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Neonweight", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
res <- rbind(res, temp)
# PWVcf_T2
form = as.formula(paste0("Neonweight ~ PWVcf_T2 + MAP_T2"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Neonweight", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
res <- rbind(res, temp)
# PWVcf_delta
form = as.formula(paste0("Neonweight ~ PWVcf_delta + MAP_delta"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Neonweight", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
res <- rbind(res, temp)
res <- as.data.frame(res)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("Neonweight ~ ", paste0(secondary_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Neonweight", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("Neonweight ~ ", paste0(tertiary_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Neonweight", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("Neonweight ~ ", paste0(other_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Neonweight", paste0(other_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
res <- as.data.frame(res)

# Egdelivery
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("Egdelivery ~", paste0(main_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Egdelivery", paste0(main_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
# PWVcf_T1
form = as.formula(paste0("Egdelivery ~ PWVcf_T1 + MAP_T1"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Egdelivery", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
res <- rbind(res, temp)
# PWVcf_T2
form = as.formula(paste0("Egdelivery ~ PWVcf_T2 + MAP_T2"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Egdelivery", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
res <- rbind(res, temp)
# PWVcf_delta
form = as.formula(paste0("Egdelivery ~ PWVcf_delta + MAP_delta"))
mod <- lm(as.formula(form), data = data, na.action = na.omit)
temp <- c("Egdelivery", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
res <- rbind(res, temp)
res <- as.data.frame(res)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("Egdelivery ~ ", paste0(secondary_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Egdelivery", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("Egdelivery ~ ", paste0(tertiary_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Egdelivery", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("Egdelivery ~ ", paste0(other_predictors[i])))
  mod <- lm(as.formula(form), data = data, na.action = na.omit)
  temp <- c("Egdelivery", paste0(other_predictors[i]), summary(mod)$coef[2,])
  res <- rbind(res, temp)
}
res <- as.data.frame(res)

# add tab for binary outcomes
res_binary <- NULL
temp <- NULL
# HDPbinary
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("HDPbinary ~", paste0(main_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("HDPbinary", paste0(main_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# PWVcf_T1
form = as.formula(paste0("HDPbinary ~ PWVcf_T1 + MAP_T1"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("HDPbinary", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_T2
form = as.formula(paste0("HDPbinary ~ PWVcf_T2 + MAP_T2"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("HDPbinary", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_delta
form = as.formula(paste0("HDPbinary ~ PWVcf_delta + MAP_delta"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("HDPbinary", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("HDPbinary ~", paste0(secondary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("HDPbinary", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("HDPbinary ~", paste0(tertiary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("HDPbinary", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("HDPbinary ~", paste0(other_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("HDPbinary", paste0(other_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# GDM
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("GDM ~", paste0(main_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("GDM", paste0(main_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# PWVcf_T1
form = as.formula(paste0("GDM ~ PWVcf_T1 + MAP_T1"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("GDM", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_T2
form = as.formula(paste0("GDM ~ PWVcf_T2 + MAP_T2"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("GDM", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_delta
form = as.formula(paste0("GDM ~ PWVcf_delta + MAP_delta"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("GDM", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("GDM ~", paste0(secondary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("GDM", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("GDM ~", paste0(tertiary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("GDM", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("GDM ~", paste0(other_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("GDM", paste0(other_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# neonatalsex
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("neonatalsex ~", paste0(main_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("neonatalsex", paste0(main_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# PWVcf_T1
form = as.formula(paste0("neonatalsex ~ PWVcf_T1 + MAP_T1"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("neonatalsex", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_T2
form = as.formula(paste0("neonatalsex ~ PWVcf_T2 + MAP_T2"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("neonatalsex", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_delta
form = as.formula(paste0("neonatalsex ~ PWVcf_delta + MAP_delta"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("neonatalsex", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("neonatalsex ~", paste0(secondary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("neonatalsex", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("neonatalsex ~", paste0(tertiary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("neonatalsex", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("neonatalsex ~", paste0(other_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("neonatalsex", paste0(other_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# Csection
for (i in 1:length(main_predictors)) {
  form = as.formula(paste0("Csection ~", paste0(main_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("Csection", paste0(main_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
# PWVcf_T1
form = as.formula(paste0("Csection ~ PWVcf_T1 + MAP_T1"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("Csection", "PWVcf_T1 (adj MAP_T1)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_T2
form = as.formula(paste0("Csection ~ PWVcf_T2 + MAP_T2"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("Csection", "PWVcf_T2 (adj MAP_T2)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
# PWVcf_delta
form = as.formula(paste0("Csection ~ PWVcf_delta + MAP_delta"))
mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
conf_int_log_odds <- confint(mod)
temp <- c("Csection", "PWVcf_delta (adj MAP_delta)", summary(mod)$coef[2,])
temp <- c(temp, conf_int_log_odds[2,])
res_binary <- rbind(res_binary, temp)
for (i in 1:length(secondary_predictors)) {
  form = as.formula(paste0("Csection ~", paste0(secondary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("Csection", paste0(secondary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(tertiary_predictors)) {
  form = as.formula(paste0("Csection ~", paste0(tertiary_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("Csection", paste0(tertiary_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
for (i in 1:length(other_predictors)) {
  form = as.formula(paste0("Csection ~", paste0(other_predictors[i])))
  mod <- glm(as.formula(form), family = "binomial", data = data, na.action = na.omit)
  conf_int_log_odds <- confint(mod)
  temp <- c("Csection", paste0(other_predictors[i]), summary(mod)$coef[2,])
  temp <- c(temp, conf_int_log_odds[2,])
  res_binary <- rbind(res_binary, temp)
}
res_binary <- as.data.frame(res_binary)

# format continuous results
res[,c("Estimate", "Std. Error", "t value", "Pr(>|t|)")] <- apply(res[,c("Estimate", "Std. Error", "t value", "Pr(>|t|)")], 2, as.numeric)
res[,c("Estimate", "Std. Error", "t value", "Pr(>|t|)")] <- apply(res[,c("Estimate", "Std. Error", "t value", "Pr(>|t|)")], 2, round, digits=4)
#colnames(res) <- c("Outcome", "Predictor", colnames(res[,3:ncol(res)]))
colnames(res) <- c("Outcome", "Predictor", "Beta", "SE", "t-value", "P-value")

# format binary results
colnames(res_binary) <- c("Outcome", "Predictor", "Odds Ratio", "SE", "z-value", "P-value", 
                   "95% CI Lower", "95% CI Upper")
res_binary$SE <- NULL
res_binary[,c("Odds Ratio", "z-value", "P-value", "95% CI Lower", "95% CI Upper")] <- apply(res_binary[,c("Odds Ratio", "z-value", "P-value", "95% CI Lower", "95% CI Upper")], 2, as.numeric)
res_binary$`Odds Ratio` <- exp(res_binary$`Odds Ratio`)
res_binary$`95% CI Lower` <- exp(res_binary$`95% CI Lower`)
res_binary$`95% CI Upper` <- exp(res_binary$`95% CI Upper`)
res_binary[,c("Odds Ratio", "z-value", "P-value", "95% CI Lower", "95% CI Upper")] <- apply(res_binary[,c("Odds Ratio", "z-value", "P-value", "95% CI Lower", "95% CI Upper")], 2, round, digits=4)

# write all results to file
filename <- "EDIPE_univariable_results.xlsx"
full_path <- file.path(results_path, filename)
wb <- createWorkbook()
addWorksheet(wb,"continuous_outcomes")
writeData(wb,"continuous_outcomes",res,rowNames = F)
addWorksheet(wb,"binary_outcomes")
writeData(wb,"binary_outcomes",res_binary,rowNames = F)
saveWorkbook(wb,full_path,overwrite = TRUE)
```
