---
title: "Missingness & outlier report for IMPROVE"
author: "Ye Ji Choi"
format: html
---

# To do

* Iohexol from Mo

* PAH reports from Mo

* Renal flow (GFR)

* UACR (albumin and creatinine)

* MRI

* Cystatin C

* TKV manual by Phoom (tkv_outcomes = 1 & volume_right_manual, volume_left_manual)

* Who's missing the most data? by visit ID, record_id's

* outliers



```{r echo = F}
library(dplyr)
library(purrr)
library(arsenal)
library(tidyr)
library(naniar)
```


```{r echo = F}
harm_dat <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")

improve <- harm_dat %>% filter(study == "IMPROVE") %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                                     race == "Black or African American" & 
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                                     ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                                     T ~ "Not Hispanic or Latino Other")) %>%
  arrange(record_id) %>%
  select(-mrn)
```

# Table of characteristics

```{r echo = F}
tab1 <- arsenal::tableby(group ~ age + sex, data = improve)

```
