---
title: "TODAY somalogic data cleaning liver enzymes"
author: "Hailey E. Hampson"
date: "2025-12-19"
output: html_document
---
#1. Load Data
```{r, include=FALSE}
#Set Director
dir.dat <- c("/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive")

#Load libraries
library(tidyverse)

# load somalogic data, with QC samples already excluded
load(fs::path(dir.dat,"/TODAY subaward/Somalogic data raw/soma.Rdata"))

# load analyte info
load(fs::path(dir.dat,"/TODAY subaward/Somalogic data raw/analytes.Rdata"))

# load comorbidity data
load(fs::path(dir.dat,"/TODAY subaward/Clinical data/comorb.Rdata"))

# load baseline risk factors
load(fs::path(dir.dat,"/TODAY subaward/Clinical data/TODAY/baserisk.Rdata"))

#load CBL
CBL <- read.csv(fs::path(dir.dat,"/TODAY subaward/Clinical data/TODAY/CBL.csv")) %>% 
  filter(mvisit!="R")

#Get key for peoteins and gene names 
key <- analytes %>% 
  dplyr::select(c("AptName","SeqId","EntrezGeneSymbol"))

```

#2. Baseline Proteomics
```{r}
# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% dplyr::group_by(releaseid) %>% dplyr::filter(row_number()==1)
# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# the above section of code used to work but seems to have broken....this should accomplish the same thing?
#base <- soma %>% filter(visit==1)

# merge in complication data
base <- left_join(base, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- left_join(base, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
base$log_UAlbCreat <- log(base$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(base[,seq])
# none

# log2 transform
base_log <- base %>% modify_if(is_seq(names(.)), log2)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[,paste0(predictors[i])] <- base_log_scale[,paste0(predictors[i])]/sd(unlist(base_log[,paste0(predictors[i])]))
}

# saveRDS(base_log,"/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive/Liver project/Data/today_proteomics_log2.rds")

```

#3. Baseline & Followup Proteomics
```{r}
#Collect all samples, baseline and followup 
follow <- soma %>% 
  arrange(releaseid,Date.Drawn) %>% 
  dplyr::group_by(releaseid) 
# dplyr::filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
#instead of removing, switch visit 1 to visit 2 and maintain in data for mixed model
follow <- follow %>% 
  mutate(visit=ifelse(releaseid %in% c("65-85903","65-47984","65-25901"),2,visit))
# filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# merge in complication data
follow <- tidylog::left_join(follow, comorb, by="releaseid")
# this was previously:
# base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
#Remove visit from baseline risk factors since all at baseline
baserisk <- baserisk %>% 
  dplyr::select(-visit)
follow <- tidylog::left_join(follow, baserisk, by="releaseid")
# this was previously:
#base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# log transform UAlbCreat
follow$log_UAlbCreat <- log(follow$UAlbCreat + 0.0000001)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(follow))

# convert to numeric
follow[,seq] <- apply(follow[,seq],2,as.numeric)

# are there proteins with low variability?
no_var = caret::nearZeroVar(follow[,seq])
# integer(0), none

# log2 transform
follow_log <- follow %>% modify_if(is_seq(names(.)), log2)

# scale by SD
follow_log_scale <- follow_log
predictors <- colnames(follow_log[seq])
for (i in 1:length(predictors)) {
  follow_log_scale[,paste0(predictors[i])] <- follow_log_scale[,paste0(predictors[i])]/sd(unlist(follow_log[,paste0(predictors[i])]))
}

# saveRDS(follow_log,"/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive/Liver project/Data/today_proteomics_longitudinal_log2.rds")

```

