---
title: "TODAY Somalogic baseline analyses - associations with parameters of insulin sensitivity"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(SomaDataIO)
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
if(Sys.info()["sysname"] == "Windows"){
  home_dir = "E:/Petter Bjornstad/TODAY subaward"
} else if (Sys.info()["sysname"] == "Linux"){
  home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
} else if (Sys.info()["sysname"] == "Darwin"){
  home_dir = "/Users/pylell/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/TODAY subaward"
}
knitr::opts_knit$set(root.dir = home_dir)

```

```{r, include=FALSE}
# load somalogic data, with QC samples already excluded
load("./Somalogic data raw/soma.Rdata")

# load analyte info
load("./Somalogic data raw/analytes.Rdata")

# load clinical data
load("./Clinical data/TODAY/clinical_data_long.Rdata")

# load baseline clinical data
load("./Clinical data/TODAY/baserisk.Rdata")
sex <- baserisk %>% select(releaseid, sex_char)

# take only the baseline soma samples
# can we just take the earliest or is it possible someone would have a follow-up sample but not baseline?
# probably can take the first and then check the years to make sure compatible with TODAY
base <- soma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)

# these 3 release IDs have first sample after end of recruitment, so they must be missing the baseline visit
base <- base %>% filter(!releaseid %in% c("65-85903","65-47984","65-25901"))

# create table of baseline clinical data
base_clinical <- long %>% filter(visit=="M00")
base_clinical$codi0 <- base_clinical$codi
base_clinical$codi <- NULL
base_clinical$si_1_ins00 <- base_clinical$si_1_ins0
base_clinical$si_1_ins0 <- NULL
base_clinical$bmi0 <- base_clinical$bmi
base_clinical$bmi <- NULL
base_clinical$trig0 <- base_clinical$trig
base_clinical$trig <- NULL
base_clinical$hba1c0 <- base_clinical$hba1c
base_clinical$hba1c <- NULL
base_clinical$bmipct0 <- base_clinical$bmipct
base_clinical$bmipct <- NULL
base_clinical <- left_join(base_clinical, sex, by="releaseid")
base_clinical_proteins <- merge(base_clinical,base,by="releaseid",all.x=F,all.y=T)

# create dataframe with slope of BMI, eIS, cODI
# function to calculate predicted value at mean insulin
# returns dataframe with StudyID and y_hat
calc_slope <- function(data, outcome) {
  slope_summary <- NULL
  df = data
  ids = as.factor(unique(df$releaseid))
  for (i in levels(ids)) {
    df_i = df[df$releaseid==i,]
    XY <- NULL
    # Predictor matrix
    X = df_i[,"visit_num"]
    # Outcome
    Y = df_i[,outcome]
    XY = cbind(X,Y)
    XY = XY[complete.cases(XY),]
    slope <- NA
    try(
      if (nrow(XY)>2) {
      # Regression 
      mod = lm(as.numeric(Y) ~ as.numeric(X), na.action = na.omit)
      int = coef(mod)[1]
      slope = coef(mod)[2]
      } else {slope <- NA})
    slope_summary <- c(slope_summary,slope)
  }
  slope_summary <- data.frame(cbind(unlist(unique(df$releaseid)),unlist(slope_summary)))
  slope_summary[,2] <- as.numeric(slope_summary[,2])
  colnames(slope_summary) <- c("releaseid",paste0("slope",outcome))
  return(slope_summary)
}
slope_bmi <- calc_slope(data = long, outcome = "bmi")
slope_odi <- calc_slope(data = long, outcome = "codi")
slope_eis <- calc_slope(data = long, outcome = "si_1_ins0")
slope_bmipct <- calc_slope(data = long, outcome = "bmipct")
base_clinical_proteins <- merge(base_clinical_proteins,slope_bmi,by="releaseid",all.x=F,all.y = F)
base_clinical_proteins <- merge(base_clinical_proteins,slope_odi,by="releaseid",all.x=F,all.y = F)
base_clinical_proteins <- merge(base_clinical_proteins,slope_eis,by="releaseid",all.x=F,all.y = F)
base_clinical_proteins <- merge(base_clinical_proteins,slope_bmipct,by="releaseid",all.x=F,all.y = F)
base_clinical_proteins$slopebmi <- as.numeric(base_clinical_proteins$slopebmi)
base_clinical_proteins$slopesi_1_ins0 <- as.numeric(base_clinical_proteins$slopesi_1_ins0)
base_clinical_proteins$slopecodi <- as.numeric(base_clinical_proteins$slopecodi)
base_clinical_proteins$slopebmipct <- as.numeric(base_clinical_proteins$slopebmipct)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("seq", .x)
seq <- is_seq(names(base_clinical_proteins))
# convert to numeric
base_clinical_proteins[,seq] <- apply(base_clinical_proteins[,seq],2,as.numeric)
# log transform
base_clinical_proteins_log <- base_clinical_proteins %>% modify_if(is_seq(names(.)), log)


```

# Unadjusted association between baseline proteins and baseline insulin sensitivity parameters, baseline proteins and change in insulin sensitivity parameters

```{r, include=FALSE}
# BMI0
df_bmi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$bmi0),]
bmi0_contrast <- model.matrix(~bmi0,df_bmi0)
df_bmi0 <- df_bmi0 %>% filter(!is.na(df_bmi0$bmi0))
ymat <- t(df_bmi0[,seq])
fit <- lmFit(ymat,bmi0_contrast)
fit <- eBayes(fit)
results_bmi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_bmi0$AptName <- row.names(results_bmi0)
results_bmi0 <- merge(results_bmi0,analytes,by="AptName",all.x = T, all.y = F)
results_bmi0 <- results_bmi0[order(results_bmi0$P.Value),]
ymat <- NULL
fit <- NULL

# BMIPCT0
df_bmipct0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$bmipct0),]
bmipct0_contrast <- model.matrix(~bmipct0,df_bmipct0)
df_bmipct0 <- df_bmipct0 %>% filter(!is.na(df_bmipct0$bmipct0))
ymat <- t(df_bmipct0[,seq])
fit <- lmFit(ymat,bmipct0_contrast)
fit <- eBayes(fit)
results_bmipct0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_bmipct0$AptName <- row.names(results_bmipct0)
results_bmipct0 <- merge(results_bmipct0,analytes,by="AptName",all.x = T, all.y = F)
results_bmipct0 <- results_bmipct0[order(results_bmipct0$P.Value),]
ymat <- NULL
fit <- NULL

# eIS
df_si_1_ins00 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$si_1_ins00),]
si_1_ins00_contrast <- model.matrix(~si_1_ins00,df_si_1_ins00)
df_si_1_ins00 <- df_si_1_ins00 %>% filter(!is.na(df_si_1_ins00$si_1_ins00))
ymat <- t(df_si_1_ins00[,seq])
fit <- lmFit(ymat,si_1_ins00_contrast)
fit <- eBayes(fit)
results_si_1_ins00 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_si_1_ins00$AptName <- row.names(results_si_1_ins00)
results_si_1_ins00 <- merge(results_si_1_ins00,analytes,by="AptName",all.x = T, all.y = F)
results_si_1_ins00 <- results_si_1_ins00[order(results_si_1_ins00$P.Value),]
ymat <- NULL
fit <- NULL

# coDI
df_codi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$codi0),]
codi0_contrast <- model.matrix(~codi0,df_codi0)
df_codi0 <- df_codi0 %>% filter(!is.na(df_codi0$codi0))
ymat <- t(df_codi0[,seq])
fit <- lmFit(ymat,codi0_contrast)
fit <- eBayes(fit)
results_codi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_codi0$AptName <- row.names(results_codi0)
results_codi0 <- merge(results_codi0,analytes,by="AptName",all.x = T, all.y = F)
results_codi0 <- results_codi0[order(results_codi0$P.Value),]
ymat <- NULL
fit <- NULL

# change in BMI
df_slopebmi = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmi),]
slopebmi_contrast <- model.matrix(~slopebmi,df_slopebmi)
df_slopebmi <- df_slopebmi %>% filter(!is.na(df_slopebmi$slopebmi))
ymat <- t(df_slopebmi[,seq])
fit <- lmFit(ymat,slopebmi_contrast)
fit <- eBayes(fit)
results_slopebmi <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmi$AptName <- row.names(results_slopebmi)
results_slopebmi <- merge(results_slopebmi,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmi <- results_slopebmi[order(results_slopebmi$P.Value),]
ymat <- NULL
fit <- NULL

# change in BMIPCT
df_slopebmipct = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmipct),]
slopebmipct_contrast <- model.matrix(~slopebmipct,df_slopebmipct)
df_slopebmipct <- df_slopebmipct %>% filter(!is.na(df_slopebmipct$slopebmipct))
ymat <- t(df_slopebmipct[,seq])
fit <- lmFit(ymat,slopebmipct_contrast)
fit <- eBayes(fit)
results_slopebmipct <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmipct$AptName <- row.names(results_slopebmipct)
results_slopebmipct <- merge(results_slopebmipct,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmipct <- results_slopebmipct[order(results_slopebmipct$P.Value),]
ymat <- NULL
fit <- NULL

# change in eIS
df_slopesi_1_ins0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopesi_1_ins0),]
slopesi_1_ins0_contrast <- model.matrix(~slopesi_1_ins0,df_slopesi_1_ins0)
df_slopesi_1_ins0 <- df_slopesi_1_ins0 %>% filter(!is.na(df_slopesi_1_ins0$slopesi_1_ins0))
ymat <- t(df_slopesi_1_ins0[,seq])
fit <- lmFit(ymat,slopesi_1_ins0_contrast)
fit <- eBayes(fit)
results_slopesi_1_ins0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopesi_1_ins0$AptName <- row.names(results_slopesi_1_ins0)
results_slopesi_1_ins0 <- merge(results_slopesi_1_ins0,analytes,by="AptName",all.x = T, all.y = F)
results_slopesi_1_ins0 <- results_slopesi_1_ins0[order(results_slopesi_1_ins0$P.Value),]
ymat <- NULL
fit <- NULL

# change in coDI
df_slopecodi = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopecodi),]
slopecodi_contrast <- model.matrix(~slopecodi,df_slopecodi)
df_slopecodi <- df_slopecodi %>% filter(!is.na(df_slopecodi$slopecodi))
ymat <- t(df_slopecodi[,seq])
fit <- lmFit(ymat,slopecodi_contrast)
fit <- eBayes(fit)
results_slopecodi <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopecodi$AptName <- row.names(results_slopecodi)
results_slopecodi <- merge(results_slopecodi,analytes,by="AptName",all.x = T, all.y = F)
results_slopecodi <- results_slopecodi[order(results_slopecodi$P.Value),]
ymat <- NULL
fit <- NULL

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"BMI0_moderated_FDR")
writeData(wb,"BMI0_moderated_FDR",results_bmi0,rowNames = F)

addWorksheet(wb,"BMIPCT0_moderated_FDR")
writeData(wb,"BMIPCT0_moderated_FDR",results_bmipct0,rowNames = F)

addWorksheet(wb,"si_1_ins00_moderated_FDR")
writeData(wb,"si_1_ins00_moderated_FDR",results_si_1_ins00,rowNames = F)

addWorksheet(wb,"codi0_moderated_FDR")
writeData(wb,"codi0_moderated_FDR",results_codi0,rowNames = F)

addWorksheet(wb,"slopebmi_moderated_FDR")
writeData(wb,"slopebmi_moderated_FDR",results_slopebmi,rowNames = F)

addWorksheet(wb,"slopebmipct_moderated_FDR")
writeData(wb,"slopebmipct_moderated_FDR",results_slopebmipct,rowNames = F)

addWorksheet(wb,"slopesi_1_ins0_moderated_FDR")
writeData(wb,"slopesi_1_ins0_moderated_FDR",results_slopesi_1_ins0,rowNames = F)

addWorksheet(wb,"slopecodi_moderated_FDR")
writeData(wb,"slopecodi_moderated_FDR",results_slopecodi,rowNames = F)

saveWorkbook(wb,"./Results/Linear and Cox models/TODAY somalogic limma baseline unadjusted insulin sensitivity.xlsx",overwrite = TRUE)
#saveWorkbook(wb,"/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/TODAY somalogic limma baseline unadjusted insulin sensitivity.xlsx",overwrite = TRUE)
```

# ADJUSTED association between baseline proteins and baseline insulin sensitivity parameters, baseline proteins and change in insulin sensitivity parameters

```{r, include=FALSE}
# BMI0
df_bmi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$bmi0) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
bmi0_contrast <- model.matrix(~bmi0+trig0+hba1c0+sex_char,df_bmi0)
df_bmi0 <- df_bmi0 %>% filter(!is.na(df_bmi0$bmi0))
ymat <- t(df_bmi0[,seq])
fit <- lmFit(ymat,bmi0_contrast)
fit <- eBayes(fit)
results_bmi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_bmi0$AptName <- row.names(results_bmi0)
results_bmi0 <- merge(results_bmi0,analytes,by="AptName",all.x = T, all.y = F)
results_bmi0 <- results_bmi0[order(results_bmi0$P.Value),]
ymat <- NULL
fit <- NULL

# BMIPCT0
df_bmipct0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$bmipct0) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
bmipct0_contrast <- model.matrix(~bmipct0+trig0+hba1c0+sex_char,df_bmipct0)
df_bmipct0 <- df_bmipct0 %>% filter(!is.na(df_bmipct0$bmipct0))
ymat <- t(df_bmipct0[,seq])
fit <- lmFit(ymat,bmipct0_contrast)
fit <- eBayes(fit)
results_bmipct0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_bmipct0$AptName <- row.names(results_bmipct0)
results_bmipct0 <- merge(results_bmipct0,analytes,by="AptName",all.x = T, all.y = F)
results_bmipct0 <- results_bmipct0[order(results_bmipct0$P.Value),]
ymat <- NULL
fit <- NULL

# eIS
df_si_1_ins00 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$si_1_ins00) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
si_1_ins00_contrast <- model.matrix(~si_1_ins00+trig0+hba1c0+sex_char,df_si_1_ins00)
df_si_1_ins00 <- df_si_1_ins00 %>% filter(!is.na(df_si_1_ins00$si_1_ins00))
ymat <- t(df_si_1_ins00[,seq])
fit <- lmFit(ymat,si_1_ins00_contrast)
fit <- eBayes(fit)
results_si_1_ins00 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_si_1_ins00$AptName <- row.names(results_si_1_ins00)
results_si_1_ins00 <- merge(results_si_1_ins00,analytes,by="AptName",all.x = T, all.y = F)
results_si_1_ins00 <- results_si_1_ins00[order(results_si_1_ins00$P.Value),]
ymat <- NULL
fit <- NULL

# coDI
df_codi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$codi0) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
codi0_contrast <- model.matrix(~codi0+trig0+hba1c0+sex_char,df_codi0)
df_codi0 <- df_codi0 %>% filter(!is.na(df_codi0$codi0))
ymat <- t(df_codi0[,seq])
fit <- lmFit(ymat,codi0_contrast)
fit <- eBayes(fit)
results_codi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_codi0$AptName <- row.names(results_codi0)
results_codi0 <- merge(results_codi0,analytes,by="AptName",all.x = T, all.y = F)
results_codi0 <- results_codi0[order(results_codi0$P.Value),]
ymat <- NULL
fit <- NULL

# change in BMI
df_slopebmi = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmi) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
slopebmi_contrast <- model.matrix(~slopebmi+trig0+hba1c0+sex_char,df_slopebmi)
df_slopebmi <- df_slopebmi %>% filter(!is.na(df_slopebmi$slopebmi))
ymat <- t(df_slopebmi[,seq])
fit <- lmFit(ymat,slopebmi_contrast)
fit <- eBayes(fit)
results_slopebmi <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmi$AptName <- row.names(results_slopebmi)
results_slopebmi <- merge(results_slopebmi,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmi <- results_slopebmi[order(results_slopebmi$P.Value),]
ymat <- NULL
fit <- NULL

# change in BMIPCT
df_slopebmipct = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmipct) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
slopebmipct_contrast <- model.matrix(~slopebmipct+trig0+hba1c0+sex_char,df_slopebmipct)
df_slopebmipct <- df_slopebmipct %>% filter(!is.na(df_slopebmipct$slopebmipct))
ymat <- t(df_slopebmipct[,seq])
fit <- lmFit(ymat,slopebmipct_contrast)
fit <- eBayes(fit)
results_slopebmipct <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmipct$AptName <- row.names(results_slopebmipct)
results_slopebmipct <- merge(results_slopebmipct,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmipct <- results_slopebmipct[order(results_slopebmipct$P.Value),]
ymat <- NULL
fit <- NULL

# change in eIS
df_slopesi_1_ins0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopesi_1_ins0) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
slopesi_1_ins0_contrast <- model.matrix(~slopesi_1_ins0+trig0+hba1c0+sex_char,df_slopesi_1_ins0)
df_slopesi_1_ins0 <- df_slopesi_1_ins0 %>% filter(!is.na(df_slopesi_1_ins0$slopesi_1_ins0))
ymat <- t(df_slopesi_1_ins0[,seq])
fit <- lmFit(ymat,slopesi_1_ins0_contrast)
fit <- eBayes(fit)
results_slopesi_1_ins0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopesi_1_ins0$AptName <- row.names(results_slopesi_1_ins0)
results_slopesi_1_ins0 <- merge(results_slopesi_1_ins0,analytes,by="AptName",all.x = T, all.y = F)
results_slopesi_1_ins0 <- results_slopesi_1_ins0[order(results_slopesi_1_ins0$P.Value),]
ymat <- NULL
fit <- NULL

# change in coDI
df_slopecodi = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopecodi) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char),]
slopecodi_contrast <- model.matrix(~slopecodi+trig0+hba1c0+sex_char,df_slopecodi)
df_slopecodi <- df_slopecodi %>% filter(!is.na(df_slopecodi$slopecodi))
ymat <- t(df_slopecodi[,seq])
fit <- lmFit(ymat,slopecodi_contrast)
fit <- eBayes(fit)
results_slopecodi <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopecodi$AptName <- row.names(results_slopecodi)
results_slopecodi <- merge(results_slopecodi,analytes,by="AptName",all.x = T, all.y = F)
results_slopecodi <- results_slopecodi[order(results_slopecodi$P.Value),]
ymat <- NULL
fit <- NULL

# NOW ADJUST MODELS FOR SLOPE FOR BASELINE VALUE TOO
# change in BMI
df_slopebmi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmi) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char) &
                                            !is.na(base_clinical_proteins_log$bmi0),]
slopebmi0_contrast <- model.matrix(~slopebmi+trig0+hba1c0+sex_char+bmi0,df_slopebmi0)
df_slopebmi0 <- df_slopebmi0 %>% filter(!is.na(df_slopebmi0$slopebmi))
ymat <- t(df_slopebmi0[,seq])
fit <- lmFit(ymat,slopebmi0_contrast)
fit <- eBayes(fit)
results_slopebmi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmi0$AptName <- row.names(results_slopebmi0)
results_slopebmi0 <- merge(results_slopebmi0,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmi0 <- results_slopebmi0[order(results_slopebmi0$P.Value),]
ymat <- NULL
fit <- NULL

# change in BMIPCT
df_slopebmipct0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopebmipct) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char) &
                                            !is.na(base_clinical_proteins_log$bmipct0),]
slopebmipct0_contrast <- model.matrix(~slopebmipct+trig0+hba1c0+sex_char+bmi0,df_slopebmipct0)
df_slopebmipct0 <- df_slopebmipct0 %>% filter(!is.na(df_slopebmipct0$slopebmipct))
ymat <- t(df_slopebmipct0[,seq])
fit <- lmFit(ymat,slopebmipct0_contrast)
fit <- eBayes(fit)
results_slopebmipct0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopebmipct0$AptName <- row.names(results_slopebmipct0)
results_slopebmipct0 <- merge(results_slopebmipct0,analytes,by="AptName",all.x = T, all.y = F)
results_slopebmipct0 <- results_slopebmipct0[order(results_slopebmipct0$P.Value),]
ymat <- NULL
fit <- NULL

# change in eIS
df_slopesi_1_ins00 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopesi_1_ins0) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char) &
                                            !is.na(base_clinical_proteins_log$si_1_ins00),]
slopesi_1_ins00_contrast <- model.matrix(~slopesi_1_ins0+trig0+hba1c0+sex_char+si_1_ins00,df_slopesi_1_ins00)
df_slopesi_1_ins00 <- df_slopesi_1_ins00 %>% filter(!is.na(df_slopesi_1_ins00$slopesi_1_ins0))
ymat <- t(df_slopesi_1_ins00[,seq])
fit <- lmFit(ymat,slopesi_1_ins00_contrast)
fit <- eBayes(fit)
results_slopesi_1_ins00 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopesi_1_ins00$AptName <- row.names(results_slopesi_1_ins00)
results_slopesi_1_ins00 <- merge(results_slopesi_1_ins00,analytes,by="AptName",all.x = T, all.y = F)
results_slopesi_1_ins00 <- results_slopesi_1_ins00[order(results_slopesi_1_ins00$P.Value),]
ymat <- NULL
fit <- NULL

# change in coDI
df_slopecodi0 = base_clinical_proteins_log[!is.na(base_clinical_proteins_log$slopecodi) & !is.na(base_clinical_proteins_log$trig0) &
                                              !is.na(base_clinical_proteins_log$hba1c0) & !is.na(base_clinical_proteins_log$sex_char) &
                                            !is.na(base_clinical_proteins_log$codi0),]
slopecodi0_contrast <- model.matrix(~slopecodi+trig0+hba1c0+sex_char+codi0,df_slopecodi0)
df_slopecodi0 <- df_slopecodi0 %>% filter(!is.na(df_slopecodi0$slopecodi))
ymat <- t(df_slopecodi0[,seq])
fit <- lmFit(ymat,slopecodi0_contrast)
fit <- eBayes(fit)
results_slopecodi0 <- topTable(fit,coef = 2,number = nrow(ymat), confint = TRUE)
results_slopecodi0$AptName <- row.names(results_slopecodi0)
results_slopecodi0 <- merge(results_slopecodi0,analytes,by="AptName",all.x = T, all.y = F)
results_slopecodi0 <- results_slopecodi0[order(results_slopecodi0$P.Value),]
ymat <- NULL
fit <- NULL

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"BMI0_FDR_adj")
writeData(wb,"BMI0_FDR_adj",results_bmi0,rowNames = F)

addWorksheet(wb,"BMIPCT0_FDR_adj")
writeData(wb,"BMIPCT0_FDR_adj",results_bmipct0,rowNames = F)

addWorksheet(wb,"si_1_ins00_FDR_adj")
writeData(wb,"si_1_ins00_FDR_adj",results_si_1_ins00,rowNames = F)

addWorksheet(wb,"codi0_FDR_adj")
writeData(wb,"codi0_FDR_adj",results_codi0,rowNames = F)

addWorksheet(wb,"slopebmi_FDR_adj_v1")
writeData(wb,"slopebmi_FDR_adj_v1",results_slopebmi,rowNames = F)

addWorksheet(wb,"slopebmipct_FDR_adj_v1")
writeData(wb,"slopebmipct_FDR_adj_v1",results_slopebmipct,rowNames = F)

addWorksheet(wb,"slopesi_1_ins0_FDR_adj_v1")
writeData(wb,"slopesi_1_ins0_FDR_adj_v1",results_slopesi_1_ins0,rowNames = F)

addWorksheet(wb,"slopecodi_FDR_adj_v1")
writeData(wb,"slopecodi_FDR_adj_v1",results_slopecodi,rowNames = F)

addWorksheet(wb,"slopebmi_FDR_adj_v2")
writeData(wb,"slopebmi_FDR_adj_v2",results_slopebmi0,rowNames = F)

addWorksheet(wb,"slopebmipct_FDR_adj_v2")
writeData(wb,"slopebmipct_FDR_adj_v2",results_slopebmipct0,rowNames = F)

addWorksheet(wb,"slopesi_1_ins0_FDR_adj_v2")
writeData(wb,"slopesi_1_ins0_FDR_adj_v2",results_slopesi_1_ins00,rowNames = F)

addWorksheet(wb,"slopecodi_FDR_adj_v2")
writeData(wb,"slopecodi_FDR_adj_v2",results_slopecodi0,rowNames = F)

saveWorkbook(wb,"./Results/Linear and Cox models/TODAY somalogic limma baseline adjusted insulin sensitivity.xlsx",overwrite = TRUE)
#saveWorkbook(wb,"/Users/pylell/Dropbox/TODAY glycemic manuscript [shared]/Analysis output/TODAY somalogic limma baseline adjusted insulin sensitivity.xlsx",overwrite = TRUE)
```


