---
title: "CITE seq priority list"
format: html
---

```{r}
library(dplyr)
library(purrr)
library(openxlsx)
```

```{r}
user <- Sys.info()[["user"]]

if (user == "choiyej") { # local version
  root_path <- "/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/keys.json")
} else if (user == "rameshsh") { # hyak version
  root_path <- ""
  git_path <- "/mmfs1/gscratch/togo/rameshsh/CHCO-Code/Petter Bjornstad"
} else if (user == "yejichoi") { # hyak version
  root_path <- "/mmfs1/gscratch/togo/yejichoi/"
  git_path <- "/mmfs1/gscratch/togo/yejichoi/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/yejichoi/keys.json")
} else if (user == "pylell") {
  root_path <- "/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/pylell/keys.json")
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r}
# Biopsies
mrn_map <- read.csv(file.path(root_path, "Data Harmonization/Data clean/mrn_uuid_map.csv"))
biopsy_master <- read_excel("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/Biopsy master tracker.xlsx", skip = 2) 
colnames(biopsy_master) <- gsub(" ", "_", colnames(biopsy_master))  # Replace spaces with underscores
colnames(biopsy_master) <- gsub("/", "_", colnames(biopsy_master))  # Replace slashes with underscores
colnames(biopsy_master) <- gsub("\\(", "_", colnames(biopsy_master))  # Replace opening parentheses with underscores
colnames(biopsy_master) <- gsub("\\)", "", colnames(biopsy_master))  # Remove closing parentheses

biopsy_master <- biopsy_master %>%
  dplyr::rename(record_id=Study_ID,
                visit=Visit_ID) %>%
  mutate(visit = case_when(Study == "ATTEMPT" ~ visit,
                           Study == "REMODEL" ~ visit, 
                           Study == "IMPROVE" & visit == "4M" ~ "3_months_post_surgery",
                           visit == "12M" ~ "12_months_post_surgery",
                           visit == "Follow-up" ~ "follow_up",
                           T ~ "baseline"),
         record_id = case_when(startsWith(record_id, "RPC") & !is.na(Coenroll_ID__Same_visit_only) ~ Coenroll_ID__Same_visit_only,
                               T ~ record_id)) # RH2-60-T and RH2-48-T coenrolled into RPC2 as of 02/03/25 data pull


# PBMC list
pbmc_list_raw <- openxlsx::read.xlsx(file.path(root_path, "PBMCs/Bjornstad PBMC Manifest_17Jan2025-2.xlsx"), sheet = "PBMCs",
                                 startRow = 1,colNames = T)
pbmc_list <- pbmc_list_raw %>%
  filter(!is.na(Cell.Line)) %>%
  distinct(Cell.Line, .keep_all = T) %>%
  mutate(study = case_when(grepl("CRC", Cell.Line) ~ "CROCODILE",
                           grepl("IT2D", Cell.Line) ~ "IMPROVE",
                           grepl("RPC", Cell.Line) ~ "RPC2",
                           grepl("RH", Cell.Line) ~ "RENAL-HEIR"),
         Cell.Line = case_when(study == "IMPROVE" ~ gsub("IT2D", "IT", Cell.Line),
                               T ~ Cell.Line),
         record_number = gsub("\\D", "", Cell.Line),
         record_id = case_when(study == "CROCODILE" ~ paste0("CRC-", record_number),
                               study == "IMPROVE" ~ paste0("IT_", record_number),
                               study == "RPC2" ~ paste0("RPC-", record_number),
                               study == "RENAL-HEIR" ~ paste0("RH-", record_number, "-T")),
         pbmc_availability = TRUE,
         visit = "baseline") %>%
  dplyr::select(record_id, visit, pbmc_availability)

# Harmonized dataset
harm_dat <- read.csv(file.path(root_path, "Data Harmonization/Data Clean/soma_harmonized_dataset.csv"), na.strings = "") %>%
  dplyr::select(
    -starts_with("seq."),
    any_of(c("seq.10000.28_urine_cradj", "seq.10000.28"))
  )

harm_dat_collapsed <- harm_dat %>% 
  mutate(bx_date = case_when(procedure == "kidney_biopsy" ~ date),
         visit = case_when(kit_id == "KL-0024005" ~ "12_months_post_surgery", T ~ visit),
         visit = case_when(study == "RPC2" & visit == "v2_gfr_mri_arm_1" ~ "baseline", T ~ visit)) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) 

harm_dat_combined <- harm_dat_collapsed %>%
  left_join(pbmc_list) %>%
  mutate(pbmc = case_when(pbmc_availability ~ 1, T ~ 0),
         urine_soma = case_when(!is.na(seq.10000.28_urine_cradj) ~ 1, T ~ 0),
         blood_soma = case_when(!is.na(seq.10000.28) ~ 1, T ~ 0),
         clamp = case_when(!is.na(p2_raw_m) ~ 1, T ~ 0),
         pet = case_when((!is.na(avg_c_f) | !is.na(avg_m_f)) ~ 1, T ~ 0),
         mri = case_when((!is.na(avg_c_r2) | !is.na(avg_k_r2) | !is.na(avg_m_r2)) ~ 1, T ~ 0),
         mgfr = case_when(!is.na(gfr_bsa_plasma) ~ 1, T ~ 0),
         erpf = case_when(!is.na(erpf_bsa_plasma) ~ 1, T ~ 0),
         egfr = case_when(!is.na(eGFR_CKD_epi) ~ 1, T ~ 0)) %>%
  left_join(biopsy_master) %>%
  arrange(desc(pbmc)) %>%
  dplyr::select(record_id, study, visit, pbmc, urine_soma, blood_soma, clamp, pet, mri, mgfr, erpf, egfr,
                ends_with("_ID", ignore.case = F)) %>%
  filter(pbmc == 1)

write.csv(harm_dat_combined, file.path(root_path, "CITE-seq/CITE_seq_PBMC_priority_list.csv"))
```

