---
title: "Jenny's grant tables"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r echo = F, include = F}
library(dplyr)
library(purrr)
library(jsonlite)
library(aws.s3)
library(digest)
library(arsenal)
library(readxl)
```

```{r echo = F, warning = F}
user <- Sys.info()[["user"]]

if (user == "choiyej") { # local version
  root_path <- "/Users/choiyej/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/keys.json")
} else if (user == "yejichoi") { # hyak version
  root_path <- "/mmfs1/gscratch/togo/yejichoi"
  git_path <- "/mmfs1/gscratch/togo/yejichoi/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/yejichoi/keys.json")
} else if (user == "pylell") {
  root_path <- "/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad"
} else {
  stop("Unknown user: please specify root path for this user.")
}

## Create an S3 client
Sys.setenv(
  "AWS_ACCESS_KEY_ID" = keys$MY_ACCESS_KEY,
  "AWS_SECRET_ACCESS_KEY" = keys$MY_SECRET_KEY,
  "AWS_DEFAULT_REGION" = "",
  "AWS_REGION" = "",
  "AWS_S3_ENDPOINT" = "s3.kopah.uw.edu"
)
```

```{r echo = F, warning = F}
# read in biopsy master spreadsheet (updated real time)
biopsy_master <- read_excel("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/Biopsy master tracker.xlsx", skip = 2) 
colnames(biopsy_master) <- gsub(" ", "_", colnames(biopsy_master))  # Replace spaces with underscores
colnames(biopsy_master) <- gsub("/", "_", colnames(biopsy_master))  # Replace slashes with underscores
colnames(biopsy_master) <- gsub("\\(", "_", colnames(biopsy_master))  # Replace opening parentheses with underscores
colnames(biopsy_master) <- gsub("\\)", "", colnames(biopsy_master))  # Remove closing parentheses
biopsy_master <- biopsy_master %>%
  dplyr::rename(record_id = Study_ID,
                visit = Visit_ID) %>%
  mutate(visit = case_when(Study == "ATTEMPT" ~ visit,
                           Study == "REMODEL" ~ visit, 
                           Study == "IMPROVE" & visit == "4M" ~ "3_months_post_surgery",
                           visit == "12M" ~ "12_months_post_surgery",
                           visit == "Follow-up" ~ "follow-up",
                           T ~ "baseline"),
         record_id = case_when(startsWith(Coenroll_ID__Same_visit_only, "RPC") & !is.na(Coenroll_ID__Same_visit_only) ~ Coenroll_ID__Same_visit_only,
                               T ~ record_id),
         Study = case_when(startsWith(Coenroll_ID__Same_visit_only, "RPC") & !is.na(Coenroll_ID__Same_visit_only) ~ "RPC2",
                            T ~ Study))

biopsy_master_complete <- biopsy_master %>%
  filter(scRNA_status == "Complete")
```


```{r echo = F, warning = F}
# data pull
harm_dat <- read.csv(file.path(root_path, "Data Harmonization/Data Clean/harmonized_dataset.csv"), na.strings = "")

dat_subset <- harm_dat %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) %>%
  filter(paste0(record_id, visit) %in% paste0(biopsy_master_complete$record_id, biopsy_master_complete$visit))
```

```{r echo = F, warning = F}
sglt2i_subset <- dat_subset %>%
  filter(group %in% c("Type 2 Diabetes", "Lean Control")) %>%
  filter(visit == "baseline") %>%
  filter(record_id != "CRC-55") %>%
  mutate(group_sglt2i = case_when(group == "Type 2 Diabetes" & epic_sglti2_1 == "Yes" ~ "T2Di+",
                                  group == "Type 2 Diabetes" & epic_sglti2_1 == "No" ~ "T2Di-",
                                  group == "Lean Control" ~ "HC"))

vsg_subset <- dat_subset %>%
  filter(study == "IMPROVE" & 
           visit %in% c("baseline", "12_months_post_surgery"))
```

```{r echo = F, results = 'asis', warning = F}
summary(arsenal::tableby(group_sglt2i ~ age + sex + bmi + hba1c + kwt(acr_u, "medianq1q3") + eGFR_CKD_epi + sbp + dbp,
                 data = sglt2i_subset), digits = 1, total = F, test = F)

vsg_subset$visit <- factor(vsg_subset$visit, levels = c("baseline", "12_months_post_surgery"))
summary(arsenal::tableby(visit ~ age + sex + bmi + hba1c + kwt(acr_u, "medianq1q3") + eGFR_CKD_epi + sbp + dbp,
                 data = vsg_subset), digits = 1, total = F, test = F)
```


# hyak

```{r}
library(edgeR)
library(Seurat)
```

```{r}
pb90 <- s3readRDS("data_clean/pb90_processed.rds", "scrna", region = "")
pb90 <- subset(pb90, KPMP_celltype_general == "PT")
# pseudobulk expression
pb90_pb <- AggregateExpression(pb90, 
                               group.by = c("kit_id", "group"), 
                               return.seurat = T)

pb90_pb_counts <- GetAssayData(pb90_pb, layer = "counts")

# median number of counts per gene after pseudobulking in PT
gene_median_counts <- apply(pb90_pb_counts, 1, median, na.rm = TRUE)

# Assuming 'counts' is your pseudobulk count matrix (genes x samples)
# and 'group' is your condition vector (e.g., "Control", "DKD")
dge <- DGEList(counts = pb90_pb_counts, group = pb90_pb$group)
dge <- calcNormFactors(dge)
dge <- estimateDisp(dge)
# BCV is the square root of the common dispersion
bcv_common <- sqrt(dge$common.dispersion)
bcv_gene   <- sqrt(dge$tagwise.dispersion)
# Or look at the trended/tagwise estimates
plotBCV(dge)

pb90_bcv_list <- list("gene_median_counts" = gene_median_counts, 
                      "bcv_common" = bcv_common, 
                      "bcv_gene" = bcv_gene)

s3saveRDS(pb90_bcv_list, "data_clean/pb90_pseudobulk_bcv.rds", "scrna", region = "")
```