---
title: "Pathway_analysis_proteomics2"
author: "Savanah Leidholt"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
.libPaths("~/leidholt/R")
```

```{r}
library(fgsea)      
library(dplyr)
library(purrr)
library(tidyverse)  
library(ggplot2)  
library(tidyr)     
library(gridExtra) 
library(msigdbr)
library(forcats)
library(stringr)
library(rlang)
library(limma)
library(jsonlite)
```


```{r}
user <- Sys.info()[["user"]]

if (user == "leidholt") {
  root_path <- "/mmfs1/gscratch/togo/leidholt/"
  git_path  <- "/mmfs1/gscratch/togo/leidholt/CHCO-Code/"
  keys      <- fromJSON("/mmfs1/home/leidholt/keys.json")
} else if (user == "sleidholt") {
  root_path <- "/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/"
  dir.results <- file.path(root_path, "Savanah Leidholt", "TRIAD", "Results")
  git_path <- "/Users/sleidholt/Documents/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/Shared/OneDrive - UW/Personal_storage/keys.json")
} else if (user == "savanahleidholt") {
  root_path <- "/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/"
  dir.results <- file.path(root_path, "Savanah Leidholt", "TRIAD", "Results")
  git_path <- "/Users/savanahleidholt/Desktop/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/savanahleidholt/OneDrive - UW/Personal_storage/keys.json")
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

#-------------------------------
# getting KEGG and GO databases
#-------------------------------
```{r}
msig_hs <- msigdbr(species = "Homo sapiens")

# Reactome (C2:CP:REACTOME)
reactome <- msig_hs %>%
  dplyr::filter(gs_collection == "C2", gs_subcollection == "CP:REACTOME") %>%
  dplyr::select(gs_name, gene_symbol)

# GO categories (C5)
go_bp <- msig_hs %>%
  dplyr::filter(gs_collection == "C5", gs_subcollection == "GO:BP") %>%
  dplyr::select(gs_name, gene_symbol)

go_cc <- msig_hs %>%
  dplyr::filter(gs_collection == "C5", gs_subcollection == "GO:CC") %>%
  dplyr::select(gs_name, gene_symbol)

go_mf <- msig_hs %>%
  dplyr::filter(gs_collection== "C5", gs_subcollection == "GO:MF") %>%
  dplyr::select(gs_name, gene_symbol)

# Combine + split to fgsea pathways list
pathways <- bind_rows(reactome, go_bp, go_cc, go_mf) %>%
  dplyr::distinct(gs_name, gene_symbol) %>%
  dplyr::group_by(gs_name) %>%
  summarise(genes = list(unique(gene_symbol)), .groups = "drop") %>%
  tibble::deframe()

summary(lengths(pathways))
```

#----------------
#model ~age + sex +study
#----------------
```{r}
obj <- readRDS(file.path(root_path, "Savanah Leidholt", "TRIAD", "Data", "limma_gsea_inputs_age_sex_study.rds"))

dat1 <- obj$primary
dat2 <- obj$noObeseT1D
dat3 <- obj$no_ATTEMPT
dat4 <- obj$all_omics


dat1_fit <- dat1$fit
dat2_fit <- dat2$fit
dat3_fit <- dat3$fit
dat4_fit <- dat4$fit

out1 <- dat1$out
out2 <- dat2$out
out3 <- dat3$out
out4 <- dat4$out

contrast_names <- colnames(dat1_fit$coefficients) %>% trimws()
```


```{r}
analytes <- read.csv(file.path(root_path, "Data Harmonization", "Combined SomaScan", "analytes.csv"))

id_map <- analytes %>%
  transmute(
    feature_id  = AptName,
    gene_symbol = EntrezGeneSymbol
  ) %>%
  filter(!is.na(gene_symbol), gene_symbol != "") %>%
  distinct()


```

#----------------------------------
#Gene Set Enrichment Analysis
#----------------------------------
```{r}
# analyte mapping must provide: feature_id -> gene_symbol
run_fgsea_contrast <- function(fit, coef_name, id_map, pathways,
                               feature_col = "feature_id",
                               symbol_col  = "gene_symbol",
                               rank_by = c("t", "logFC"),
                               minSize = 15, maxSize = 500) {

  rank_by <- match.arg(rank_by)

  # safe matching of coef name
  coef_name <- match.arg(coef_name, choices = colnames(fit$coefficients))

  tt <- topTable(fit, coef = coef_name, number = Inf, sort.by = "none") %>%
    tibble::rownames_to_column(feature_col) %>%
    left_join(id_map, by = feature_col) %>%
    dplyr::filter(!is.na(.data[[symbol_col]]), .data[[symbol_col]] != "")

  # collapse duplicate genes
  tt_gene <- tt %>%
    dplyr::group_by(.data[[symbol_col]]) %>%
    slice_max(order_by = abs(.data[[rank_by]]), n = 1) %>%
    ungroup()

  stats <- tt_gene[[rank_by]]
  names(stats) <- tt_gene[[symbol_col]]
  stats <- sort(stats, decreasing = TRUE)

  fgseaMultilevel(
    pathways = pathways,
    stats = stats,
    minSize = minSize,
    maxSize = maxSize
  ) %>%
    as_tibble() %>%
    dplyr::mutate(
      contrast = coef_name,
      rank_metric = rank_by,
      n_genes_ranked = length(stats)
    ) %>%
    dplyr::arrange(padj, desc(abs(NES)))
}

```


```{r}
fgsea1 <- map_dfr(
  contrast_names,
  ~ run_fgsea_contrast(
      fit = dat1_fit,
      coef_name = .x,
      id_map = id_map,
      pathways = pathways,
      rank_by = "t"
  )
)

```

```{r}
fgsea1 <- fgsea1 %>%
  dplyr::mutate(collection = case_when(
    grepl("REACTOME", pathway) ~ "Reactome",
    grepl("GOBP", pathway)     ~ "GO:BP",
    grepl("GOCC", pathway)     ~ "GO:CC",
    grepl("GOMF", pathway)     ~ "GO:MF",
    TRUE ~ "Other"
  ))


fgsea1

#getting only significant pathways
fgsea_sig1 <- fgsea1 %>% filter(padj < 0.05 & abs(NES) >= 1)
table(fgsea_sig1$contrast)


fgsea1 %>%
  filter(padj < 0.05 & abs(NES) >= 2) %>%
  count(contrast)

```

```{r}
fgsea2 <- map_dfr(
  contrast_names,
  ~ run_fgsea_contrast(
      fit = dat2_fit,
      coef_name = .x,
      id_map = id_map,
      pathways = pathways,
      rank_by = "t"
  )
)

```

```{r}
fgsea2 <- fgsea2 %>%
  mutate(collection = case_when(
    grepl("REACTOME", pathway) ~ "Reactome",
    grepl("GOBP", pathway)     ~ "GO:BP",
    grepl("GOCC", pathway)     ~ "GO:CC",
    grepl("GOMF", pathway)     ~ "GO:MF",
    TRUE ~ "Other"
  ))



#getting only significant pathways

fgsea_sig2 <- fgsea2 %>% filter(padj < 0.05 & abs(NES) >= 1)
table(fgsea_sig2$contrast)


fgsea2 %>%
  filter(padj < 0.05 & abs(NES) >= 2) %>%
  count(contrast)

```
```{r}
fgsea3 <- map_dfr(
  contrast_names,
  ~ run_fgsea_contrast(
      fit = dat3_fit,
      coef_name = .x,
      id_map = id_map,
      pathways = pathways,
      rank_by = "t"
  )
)


```

```{r}
fgsea3 <- fgsea3 %>%
  mutate(collection = case_when(
    grepl("REACTOME", pathway) ~ "Reactome",
    grepl("GOBP", pathway)     ~ "GO:BP",
    grepl("GOCC", pathway)     ~ "GO:CC",
    grepl("GOMF", pathway)     ~ "GO:MF",
    TRUE ~ "Other"
  ))


fgsea3
#getting only significant pathways

fgsea_sig3 <- fgsea3 %>% filter(padj < 0.05 & abs(NES) >= 1)
table(fgsea_sig3$contrast)


fgsea3 %>%
  filter(padj < 0.05 & abs(NES) >= 2) %>%
  count(contrast)

```


```{r}
fgsea4 <- map_dfr(
  contrast_names,
  ~ run_fgsea_contrast(
      fit = dat4_fit,
      coef_name = .x,
      id_map = id_map,
      pathways = pathways,
      rank_by = "t"
  )
)

```

```{r}
fgsea4 <- fgsea4 %>%
  mutate(collection = case_when(
    grepl("REACTOME", pathway) ~ "Reactome",
    grepl("GOBP", pathway)     ~ "GO:BP",
    grepl("GOCC", pathway)     ~ "GO:CC",
    grepl("GOMF", pathway)     ~ "GO:MF",
    TRUE ~ "Other"
  ))


fgsea4
#getting only significant pathways

fgsea_sig4 <- fgsea4 %>% filter(padj < 0.05 & abs(NES) >= 1)
table(fgsea_sig4$contrast)


fgsea4 %>%
  filter(padj < 0.05 & abs(NES) >= 2) %>%
  count(contrast)

```

#----------------------
#dotplot function
#----------------------
```{r}
enrich_dotplot <- function(fgsea_df, n = 15, title = NULL, wrap_width = 60) {

  if (nrow(fgsea_df) == 0) {
    return(ggplot() + theme_void() + labs(title = title %||% "No results"))
  }

  dfp <- fgsea_df %>%
    filter(!is.na(padj)) %>%
    slice_min(padj, n = n) %>%
    mutate(
      pathway = str_replace_all(pathway, "_", " "),
      pathway = fct_reorder(pathway, NES),
      neg_log10_padj = -log10(padj)
    )

  ggplot(dfp, aes(
    x = NES,
    y = pathway,
    size = size,
    color = neg_log10_padj
  )) +
    geom_point(alpha = 0.85) +
    scale_y_discrete(labels = label_wrap_gen(width = wrap_width)) +
    scale_color_viridis_c(option = "plasma", name = "-log10(adj p)") +
    scale_size(range = c(2, 8), name = "Gene set size") +
    geom_vline(xintercept = 0, linetype = "dashed", color = "pink") +
    theme_bw() +
    theme(axis.text.y = element_text(size = 8)) +
    labs(
      title = title %||% unique(fgsea_df$contrast)[1],
      x = "Normalized Enrichment Score (NES)",
      y = NULL
    )
}



```

```{r}
plots <- lapply(contrast_names, function(cn) {
  df <- fgsea1 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 10, title = paste("FGSEA:", cn))
})

plots

```
```{r}
plots2 <- lapply(contrast_names, function(cn) {
  df <- fgsea2 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 10, title = paste("FGSEA:", cn))
})

plots2

```

```{r}
plots3 <- lapply(contrast_names, function(cn) {
  df <- fgsea3 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 10, title = paste("FGSEA:", cn))
})

plots3

```
```{r}
plots4 <- lapply(contrast_names, function(cn) {
  df <- fgsea4 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 10, title = paste("FGSEA:", cn))
})

plots4

```
#-----------------------------------
#plotting only top 10 reactome pathways in each contrast
#-----------------------------------
```{r}
fgsea_reactome <- fgsea1 %>%
  filter(grepl("^REACTOME_", pathway))

fgsea_reactome_top10 <- fgsea_reactome %>%
  group_by(contrast) %>%
  slice_min(padj, n = 15, with_ties = FALSE) %>%
  ungroup()


reactome_plots <- lapply(unique(fgsea_reactome_top10$contrast), function(cn) {
  df <- fgsea_reactome_top10 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 15, title = paste("Top Reactome:", cn))
})


reactome_plots

gridExtra::grid.arrange(grobs = reactome_plots, ncol = 2)

```

```{r}
#plotting only top 10 reactome pathways in each contrast
fgsea_reactome2 <- fgsea2 %>%
  filter(grepl("^REACTOME_", pathway))

fgsea_reactome2_top10 <- fgsea_reactome2 %>%
  group_by(contrast) %>%
  slice_min(padj, n = 15, with_ties = FALSE) %>%
  ungroup()


reactome_plots2 <- lapply(unique(fgsea_reactome2_top10$contrast), function(cn) {
  df <- fgsea_reactome2_top10 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 15, title = paste("Top Reactome:", cn))
})


reactome_plots

gridExtra::grid.arrange(grobs = reactome_plots, ncol = 2)

```
```{r}
#plotting only top 10 reactome pathways in each contrast
fgsea_reactome3 <- fgsea3 %>%
  filter(grepl("^REACTOME_", pathway))

fgsea_reactome3_top10 <- fgsea_reactome3 %>%
  group_by(contrast) %>%
  slice_min(padj, n = 15, with_ties = FALSE) %>%
  ungroup()


reactome_plots3 <- lapply(unique(fgsea_reactome3_top10$contrast), function(cn) {
  df <- fgsea_reactome3_top10 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 15, title = paste("Top Reactome:", cn))
})


reactome_plots3

gridExtra::grid.arrange(grobs = reactome_plots, ncol = 2)

```
```{r}
#plotting only top 10 reactome pathways in each contrast
fgsea_reactome4 <- fgsea4 %>%
  filter(grepl("^REACTOME_", pathway))

fgsea_reactome4_top10 <- fgsea_reactome4 %>%
  group_by(contrast) %>%
  slice_min(padj, n = 15, with_ties = FALSE) %>%
  ungroup()


reactome_plots4 <- lapply(unique(fgsea_reactome4_top10$contrast), function(cn) {
  df <- fgsea_reactome4_top10 %>% filter(contrast == cn)
  enrich_dotplot(df, n = 15, title = paste("Top Reactome:", cn))
})


reactome_plots4

gridExtra::grid.arrange(grobs = reactome_plots, ncol = 2)

```


#-------------------------------
#Pathway overlap between models
#-------------------------------
```{r}
fgsea_sig_list <- list(
  primary       = fgsea_sig1,
  no_obese_T1D   = fgsea_sig2,
  no_ATTEMPT     = fgsea_sig3,
  all_omics  = fgsea_sig4
)

fgsea_list <- list(
  primary       = fgsea1,
  no_obese_T1D   = fgsea2,
  no_ATTEMPT     = fgsea3,
  all_omics  = fgsea4
)
```

```{r}
compare_fgsea_nes <- function(primary_df, sens_df, sens_name) {
  
  contrast_names <- intersect(
    unique(primary_df$contrast),
    unique(sens_df$contrast)
  )
  
  map_dfr(contrast_names, function(cc) {
    
    df <- primary_df %>%
      filter(contrast == cc) %>%
      select(pathway, NES_primary = NES) %>%
      inner_join(
        sens_df %>%
          filter(contrast == cc) %>%
          select(pathway, NES_sensitivity = NES),
        by = "pathway"
      ) %>%
      filter(
        is.finite(NES_primary),
        is.finite(NES_sensitivity)
      )
    
    tibble(
      sensitivity = sens_name,
      contrast = cc,
      n_shared_pathways = nrow(df),
      spearman_NES = ifelse(
        nrow(df) >= 3,
        cor(df$NES_primary, df$NES_sensitivity, method = "spearman"),
        NA_real_
      )
    )
  })
}

```
#------------------------------------
#sig pathways spearman correlations
#------------------------------------
```{r}
gsea_sensitivity_cor <- imap_dfr(
  fgsea_sig_list[-1],
  ~ compare_fgsea_nes(
      primary_df = fgsea_sig_list$primary,
      sens_df = .x,
      sens_name = .y
    )
)

gsea_sensitivity_cor
```

```{r}
gsea_sensitivity_cor_wide <- gsea_sensitivity_cor %>%
  select(sensitivity, contrast, spearman_NES) %>%
  pivot_wider(
    names_from = sensitivity,
    values_from = spearman_NES
  )

gsea_sensitivity_cor_wide
```
#----------------------------------
#all pathways spearman correlations
#----------------------------------
```{r}
gsea_sensitivity_cor2 <- imap_dfr(
  fgsea_list[-1],
  ~ compare_fgsea_nes(
      primary_df = fgsea_list$primary,
      sens_df = .x,
      sens_name = .y
    )
)

gsea_sensitivity_cor2

gsea_sensitivity_cor_wide2 <- gsea_sensitivity_cor2 %>%
  select(sensitivity, contrast, spearman_NES) %>%
  pivot_wider(
    names_from = sensitivity,
    values_from = spearman_NES
  )

gsea_sensitivity_cor_wide2
```

```{r}
plot_fgsea_correlation <- function(primary_df,
                                   sens_df,
                                   sens_name,
                                   contrast_name) {

  df <- primary_df %>%
    filter(contrast == contrast_name) %>%
    select(pathway, NES_primary = NES) %>%
    inner_join(
      sens_df %>%
        filter(contrast == contrast_name) %>%
        select(pathway, NES_sensitivity = NES),
      by = "pathway"
    ) %>%
    filter(
      is.finite(NES_primary),
      is.finite(NES_sensitivity)
    )

  rho <- cor(
    df$NES_primary,
    df$NES_sensitivity,
    method = "spearman"
  )

  ggplot(
    df,
    aes(
      x = NES_primary,
      y = NES_sensitivity
    )
  ) +
    geom_point(alpha = 0.4, size = 2) +
    geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed",
      color = "red"
    ) +
    coord_equal() +
    scale_x_continuous(limits = c(-3, 3)) +
    scale_y_continuous(limits = c(-3, 3)) +
    theme_bw() +
    labs(
      title = contrast_name,
      subtitle = paste0(
        "ρ = ",
        round(rho, 3),
        " (n = ",
        nrow(df),
        ")"
      ),
      x = "Primary NES",
      y = paste0(sens_name, " NES")
    )
}
```

```{r}
library(patchwork)
plots_noObese <- map(
  contrast_names,
  ~plot_fgsea_correlation(
    primary_df = fgsea_sig1,
    sens_df = fgsea_sig2,
    sens_name = "No Obese T1D",
    contrast_name = .x
  )
)

panel_noObese <- wrap_plots(
  plots_noObese,
  ncol = 3
) +
  plot_annotation(
    title = "Pathway sensitivity analysis: Remove obese T1D"
  )

panel_noObese
```
```{r}
plots_noObese <- map(
  contrast_names,
  ~plot_fgsea_correlation(
    primary_df = fgsea1,
    sens_df = fgsea2,
    sens_name = "No Obese T1D",
    contrast_name = .x
  )
)

panel_noObese <- wrap_plots(
  plots_noObese,
  ncol = 3
) +
  plot_annotation(
    title = "Pathway sensitivity analysis: Remove obese T1D"
  )

panel_noObese
```

```{r}
plots_noATT <- map(
  contrast_names,
  ~plot_fgsea_correlation(
    primary_df = fgsea_sig1,
    sens_df = fgsea_sig3,
    sens_name = "No ATTEMPT",
    contrast_name = .x
  )
)

panel_noATT <- wrap_plots(
  plots_noATT,
  ncol = 3
) +
  plot_annotation(
    title = "Pathway sensitivity analysis: No ATTEMPT"
  )

panel_noATT
```

```{r}
plots_allomics <- map(
  contrast_names,
  ~plot_fgsea_correlation(
    primary_df = fgsea_sig1,
    sens_df = fgsea_sig4,
    sens_name = "All Omics",
    contrast_name = .x
  )
)

panel_allomics <- wrap_plots(
  plots_allomics,
  ncol = 3
) +
  plot_annotation(
    title = "Pathway sensitivity analysis: All Omics"
  )

panel_allomics
```
```{r}
plots_allomics <- map(
  contrast_names,
  ~plot_fgsea_correlation(
    primary_df = fgsea1,
    sens_df = fgsea4,
    sens_name = "All Omics",
    contrast_name = .x
  )
)

panel_allomics <- wrap_plots(
  plots_allomics,
  ncol = 3
) +
  plot_annotation(
    title = "Pathway sensitivity analysis: All Omics"
  )

panel_allomics
```


```{r}
make_top_pathway_overlap <- function(primary_df,
                                     sens_df,
                                     sens_name,
                                     top_n = 100) {
  
  contrast_names <- intersect(
    unique(primary_df$contrast),
    unique(sens_df$contrast)
  )
  
  purrr::map_dfr(contrast_names, function(cc) {
    
    primary_top <- primary_df %>%
      filter(contrast == cc, is.finite(NES)) %>%
      arrange(desc(abs(NES))) %>%
      slice_head(n = top_n) %>%
      pull(pathway)
    
    sens_top <- sens_df %>%
      filter(contrast == cc, is.finite(NES)) %>%
      arrange(desc(abs(NES))) %>%
      slice_head(n = top_n) %>%
      pull(pathway)
    
    n_overlap <- length(intersect(primary_top, sens_top))
    
    tibble(
      sensitivity = sens_name,
      contrast = cc,
      top_n = top_n,
      n_overlap = n_overlap,
      pct_overlap = round(100 * n_overlap / top_n, 1),
      jaccard_index = round(
        n_overlap / length(union(primary_top, sens_top)),
        3
      )
    )
  })
}
```

```{r}
pathway_top_overlap <- bind_rows(
  make_top_pathway_overlap(fgsea1, fgsea2, "No obese T1D", top_n = 100),
  make_top_pathway_overlap(fgsea1, fgsea3, "No ATTEMPT", top_n = 100),
  make_top_pathway_overlap(fgsea1, fgsea4, "All Omics", top_n = 100)
)

pathway_top_overlap
```


```{r}
top_pathway_overlap_wide <- pathway_top_overlap %>%
  select(sensitivity, contrast, jaccard_index) %>%
  pivot_wider(
    names_from = sensitivity,
    values_from = jaccard_index
  )

top_pathway_overlap_wide 
```
