---
title: "scRNA_data_cleaning"
author: "Savanah Leidholt"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
#.libPaths("~/leidholt/R")
```

```{r}
#loading packages
library(tidyverse)
#BiocManager::install("arsenal")
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(Hmisc)
library(readxl)
library(purrr)
library(aws.s3)
library(jsonlite)
library(Seurat)
library(harmony)
library(readr)
library(parallel)
```

```{r}
#directores
user <- Sys.info()[["user"]]

if (user == "leidholt") {
  root_path <- c("/mmfs1/gscratch/togo/leidholt/") #hyak
  git_path <- "/mmfs1/gscratch/togo/leidholt/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/leidholt/keys.json")
} else if (user == "sleidholt") {
    root_path <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/") #mac studio
    dir.results <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Savanah Leidholt/") 
    git_path <- "/Users/sleidholt/Documents/GitHub/CHCO-Code/Petter Bjornstad/Savanah Leidholt"
} else if (user == "savanahleidholt") {
    root_path <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/") #laptop
    dir.results <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Savanah Leidholt/") 
    git_path <- "/Users/savanahleidholt/Desktop/CHCO-Code/Petter Bjornstad/Savanah Leidholt"
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r}
#detectCores()
#plan("multisession", workers = 5)
plan("sequential")
```


```{r}
Sys.setenv(
  "AWS_ACCESS_KEY_ID" = keys$MY_ACCESS_KEY,
  "AWS_SECRET_ACCESS_KEY" = keys$MY_SECRET_KEY,
  "AWS_DEFAULT_REGION" = "",
  "AWS_REGION" = "",
  "AWS_S3_ENDPOINT" = "s3.kopah.uw.edu"
)
```

```{r echo = F, eval = T}
pb90_multiomics<- s3readRDS(
          object = "data_clean/pb90_multiomics_savanah_baseline_20260406.rds", 
          bucket = "scrna",
          region = "")
```

```{r}
ids <- pb90_multiomics@meta.data$record_id 
ids <- as.data.frame(ids) %>%
  dplyr::distinct(ids) %>%
  dplyr::pull(ids)  
``` 

```{r}
DefaultAssay(pb90_multiomics)

Assays(pb90_multiomics)

slotNames(pb90_multiomics[["RNA"]])
```

#-----------------------------------------------
#reacreating UMAPS for TRIAD subset
# ye ji has already filtered out low cell counts (<5%)
# also removed mito and ribo genes
# counts data is raw (pseudobulk) 
# data = normalized (nebula)
#-----------------------------------------------
```{r}
set.seed(1835)

pb90_multiomics <- pb90_multiomics 
DefaultAssay(pb90_multiomics) <- "RNA"

# Remove old reductions from larger dataset
pb90_multiomics@reductions <- list()

#remove old cluster columns from larger dataset
pb90_multiomics$seurat_clusters <- NULL
pb90_multiomics$harmony_clusters <- NULL

pb90_multiomics[["RNA"]]$scale.data <- NULL
pb90_multiomics[["RNA"]]@layers$scale.data <- NULL
Layers(pb90_multiomics[["RNA"]])
#Layers(pb90_multiomics[["RNA"]])


# Re-identify variable genes within this subset
pb90_multiomics <- FindVariableFeatures(
  pb90_multiomics)

# Scale only variable genes to save memory
pb90_multiomics <- ScaleData(
  pb90_multiomics)


# PCA on subset
pb90_multiomics <- RunPCA(
  pb90_multiomics)

ElbowPlot(pb90_multiomics, ndims = 50)
```

```{r}
pb90_multiomics <- FindNeighbors(
  pb90_multiomics,
  reduction = "pca",
  dims = 1:30
)

pb90_multiomics <- FindClusters(
  pb90_multiomics,
  resolution = 1.5,
  cluster.name = "unintegrated_clusters"
)

pb90_multiomics <- RunUMAP(
  pb90_multiomics,
  dims = 1:30,
  reduction = "pca",
  reduction.name = "umap.unintegrated"
)
```

```{r}
pb90_multiomics_integrated <- RunHarmony(
  object = pb90_multiomics,
  group.by.vars = "orig.ident",
  reduction.use = "pca",
  assay.use = DefaultAssay(pb90_multiomics),
  reduction.save = "harmony"
)
```
```{r}
# neighbors/clusters/UMAP using Harmony
pb90_multiomics_integrated <- FindNeighbors(
  pb90_multiomics_integrated,
  reduction = "harmony",
  dims = 1:30
)

pb90_multiomics_integrated <- FindClusters(
  pb90_multiomics_integrated,
  resolution = 1.5,
  cluster.name = "TRIAD_clusters"
)

pb90_multiomics_integrated <- RunUMAP(
  pb90_multiomics_integrated,
  reduction = "harmony",
  dims = 1:30,
  reduction.name = "umap.TRIAD"
)
```

```{r}
# Extract UMAP coordinates from the TRIAD reduction
umap_coords <- Embeddings(
  pb90_multiomics_integrated,
  reduction = "umap.TRIAD"
)

# Add as metadata columns
pb90_multiomics_integrated$umapTRIAD_1 <- umap_coords[,1]
pb90_multiomics_integrated$umapTRIAD_2 <- umap_coords[,2]
```

#save file so I don't have to repeat above steps
```{r}
#s3saveRDS(pb90_multiomics_integrated, 
 #         object = "data_clean/pb90_multiomics_subset_savanah_20260420.rds", 
  #        bucket = "scrna",
   #       region = "",
  #  multipart = T)
```

#start here post cleaning steps
```{r}
#pb90_multiomics_integrated <- s3readRDS(
 #         object = "data_clean/pb90_multiomics_subset_savanah_20260406.rds", 
  #        bucket = "scrna",
   #       region = "")
```

```{r}
p1 <- DimPlot(
  pb90_multiomics_integrated,
  reduction = "umap.unintegrated",
  group.by = "study"
)

p2 <- DimPlot(
  pb90_multiomics_integrated,
  reduction = "umap.TRIAD",
  group.by = "study"
)

p1 | p2
```

```{r}
reticulate::use_python("/mmfs1/gscratch/togo/leidholt/pytorch-cuda11/bin/python", required = T)
reticulate::repl_python()
reticulate::py_config()
# set up Kopah connection
## Load boto3 and pandas
boto3 <- reticulate::import("boto3")
pd <- reticulate::import("pandas")

## Create an S3 client
session <- boto3$session$Session(
  aws_access_key_id = keys$MY_ACCESS_KEY,
  aws_secret_access_key = keys$MY_SECRET_KEY
)

## Create an S3 client with the session
s3 <- session$client("s3", endpoint_url = "https://s3.kopah.uw.edu")
```

```{r}
bucket <- "harmonized.dataset" # bucket name in Kopah
temp_file <- tempfile(fileext = ".csv") # need to create a temporary file
s3$download_file(bucket, "harmonized_dataset.csv", temp_file)
harm_meta_data <- read.csv(temp_file)

#harm_meta_data <- readRDS(file.path(root_path, "Data Harmonization", "Data Clean", "harmonized_dataset.rds"))
```

```{r}
#same with ids columns (all categorical)
id_cols <- as.character(c(
  "record_id","mrn","attempt_id","croc_id","improve_id","rh_id","rh2_id","panther_id",
  "study","visit","group","sex","race","ethnicity"
))

#clinical numeric data I want to keep stored in a list
clin_cols <- c(
  "age","bmi","eGFR_CKiD_U25_avg", "avg_c_r2", "avg_k_r2","acr_u"
)
#filtering the same way as metabolomic and proteomic metadata
 # for non-numeric: keep value only if it's consistent within record_id+visit
 # for numeric: mean within record_id+visit (not counting NAs within the mean)
meta_scrna <- harm_meta_data %>%
  arrange(record_id) %>%
  filter(record_id %in% ids) %>%
  filter(visit == "baseline") %>%
  select(any_of(c(id_cols, clin_cols))) %>%
  summarise(
    across(
      where(~ !is.numeric(.x)),
      ~{
        vals <- unique(na.omit(.x))
        if (length(vals) == 0) NA_character_
        else if (length(vals) == 1) as.character(vals)
        else NA_character_
      }
    ),
    across(
      where(is.numeric),
      ~ if (all(is.na(.x))) NA_real_ else mean(.x, na.rm = TRUE)
    ),
    .by = c(record_id, visit)
  ) %>%
  mutate(
    race_ethnicity_condensed = case_when(
      race == "White" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
      race == "Black or African American" & ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
      ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
      TRUE ~ "Not Hispanic or Latino Other"
    )
  )
```

```{r}
meta <- pb90_multiomics_integrated@meta.data
pb90_multiomics_meta_subset <- pb90_multiomics_integrated@meta.data %>%
  dplyr::select(1:7, record_id, kit_id, visit, source, celltype_rpca, celltype_harmony, KPMP_celltype, unintegrated_clusters, TRIAD_clusters, umapTRIAD_1, umapTRIAD_2) %>%
  dplyr::mutate(kit_id = gsub("kl", "KL", gsub("KI", "KL", kit_id)),
                visit = case_when(visit == "screening" ~ "baseline",
                                  T ~ visit)) %>%
  left_join(meta_scrna) %>%
  dplyr::mutate(rownames = paste0(source, "_", barcode)) 
```

#-----------------------------------------------------------------
#create KPMP_celltype_general
#   also create subset data with just endothelial cells & subtypes
#-----------------------------------------------------------------
```{r}
celltype_groups <- list(
  PT = c("PT-S1/S2", "PT-S3", "aPT"),
  TAL = c("C-TAL-1", "C-TAL-2", "aTAL", "dTAL"),
  PC = c("CCD-PC", "CNT-PC", "dCCD-PC", "M-PC", "tPC-IC"),
  IC = c("IC-A", "IC-B", "aIC"),
  DTL_ATL = c("DTL", "aDTL", "ATL"),   # grouped thin limbs
  DCT_CNT = c("DCT", "dDCT", "CNT"),   # grouped distal tubule/connecting tubule
  EC = c("EC-AVR", "EC-GC", "EC-PTC", "EC-AEA", "EC-LYM", "EC/VSMC"),  #endothelial cells
  Immune = c("MAC", "MON", "cDC", "pDC", "CD4+ T", "CD8+ T", "B", "NK", "cycT"),
  # Immune_Myeloid = c("MAC", "MON", "cDC", "pDC"),
  # Immune_Lymphoid = c("CD4+ T", "CD8+ T", "B", "NK", "cycT"),
  VSMC_P_FIB = c("VSMC/P", "FIB"),
  POD = "POD",
  MC = "MC",                         # mesangial cells
  PEC = "PEC",                       # parietal epithelial cells
  Schwann = "SchwannCells",
  Other = c("non-specific")          # catchall
)

map_celltype_to_general <- function(celltype, celltype_groups) {
  for (group_name in names(celltype_groups)) {
    if (celltype %in% celltype_groups[[group_name]]) {
      return(group_name)
    }
  }
  return("Other")  # For any celltype not found in groups
}

pb90_multiomics_meta_subset$KPMP_celltype_general <- sapply(
  pb90_multiomics_meta_subset$KPMP_celltype, 
  map_celltype_to_general, 
  celltype_groups = celltype_groups)

rownames(pb90_multiomics_meta_subset) <- pb90_multiomics_meta_subset$rownames

table((pb90_multiomics_meta_subset %>%
  distinct(record_id, visit, .keep_all = T))$study) 

pb90_multiomics_subset <- pb90_multiomics[, colnames(pb90_multiomics) %in% rownames(pb90_multiomics_meta_subset)]
pb90_multiomics_subset@meta.data <- pb90_multiomics_meta_subset
```

```{r}
s3saveRDS(pb90_multiomics_subset, 
          object = "data_clean/pb90_multiomics_subset_savanah_20260420.rds", 
          bucket = "scrna",
          region = "",
          multipart = T)
```



