---
title: "10_scRNA_nebula"
author: "Savanah Leidholt"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
    theme:
      light: flatly
      dark: darkly
editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
.libPaths("/mmfs1/gscratch/togo/leidholt/R_SLL_Seurat/")
```

```{r}
install_if_missing_cran <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(
      pkg,
      lib = ("/mmfs1/gscratch/togo/leidholt/R_SLL_Seurat/"),
      dependencies = TRUE
    )
  }
}

install_if_missing_bioc <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    BiocManager::install(
      pkg,
      lib = ("/mmfs1/gscratch/togo/leidholt/R_SLL_Seurat/"),
      update = FALSE,
      ask = FALSE
    )
  }
}
```

```{r}
library(Seurat)
library(tidyverse)
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(Hmisc)
library(readxl)
library(purrr)
library(aws.s3)
library(jsonlite)
library(RColorBrewer)
library(ggtrace)
library(kableExtra)
library(data.table)
library(table1)
library(BiocManager)
library(GSA)
library(emmeans)
library(pheatmap)
library(enrichplot)
library(enrichR)
library(nebula)
library(doParallel)
library(Matrix)
library(edgeR)
library(stringr)
library(patchwork)
library(msigdbr)
library(fgsea)


#install_if_missing_bioc("speckle")
library(speckle)

```
#directories
```{r}
user <- Sys.info()[["user"]]

if (user == "leidholt") {
  root_path <- c("/mmfs1/gscratch/togo/leidholt/")
  git_path <- "/mmfs1/gscratch/togo/leidholt/CHCO-Code/"
  keys <- fromJSON("/mmfs1/home/leidholt/keys.json")
  
} else if (user == "sleidholt") {
    root_path <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/")
    dir.results <- c("/Users/Shared/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Savanah Leidholt/TRIAD/Results")
    git_path <- "/Users/sleidholt/Documents/GitHub/CHCO-Code/Petter Bjornstad"
    keys <- fromJSON("/Users/Shared/OneDrive - UW/Personal_storage/keys.json")
    
} else if (user == "savanahleidholt") {
    root_path <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/")
    dir.results <- c("/Users/savanahleidholt/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Savanah Leidholt/TRIAD/Results")
    git_path <- "/Users/savanahleidholt/Desktop/CHCO-Code/Petter Bjornstad"
    keys <- fromJSON("/Users/savanahleidholt/OneDrive - UW/Personal_storage/keys.json")
    
} else {
  stop("Unknown user: please specify root path for this user.")
}
```
#-------------------
#reading in nebula results file
#-------------------
```{r}
PT_OC_LC_results <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2", "nebula_PT_OC_vs_LC.rds"))
PT_OC_LC_results <- PT_OC_LC_results$results
PT_OC_LC <- PT_OC_LC_results %>%
  filter(stable_fit == "TRUE")
PT_diag <- readRDS(file = file.path(dir.results, "scRNA results", "nebula", "nebula_2","nebula_PT_OC_vs_LC.rds"))
PT_diag <- PT_diag$diagnostics

PT_T1D_LC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_PT_T1D_vs_LC.rds"))
PT_T1D_LC_res <- PT_T1D_LC_res$results
PT_T1D_LC <- PT_T1D_LC_res %>%
  filter(stable_fit == "TRUE")

PT_T2D_LC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_PT_T2D_vs_LC.rds"))
PT_T2D_LC_res <- PT_T2D_LC_res$results
PT_T2D_LC <- PT_T2D_LC_res %>%
  filter(stable_fit == "TRUE")

PT_T1D_T2D_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_PT_T1D_vs_T2d.rds"))
PT_T1D_T2D_res <- PT_T1D_T2D_res$results
PT_T1D_T2D <- PT_T1D_T2D_res %>%
  filter(stable_fit == "TRUE")

TAL_T1D_LC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_T1D_vs_LC.rds"))
TAL_T1D_LC_res <- TAL_T1D_LC_res$results
TAL_T1D_LC <- TAL_T1D_LC_res %>%
  filter(stable_fit =="TRUE")

TAL_T1D_OC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_T1D_vs_OC.rds"))
TAL_T1D_OC_res <- TAL_T1D_OC_res$results
TAL_T1D_OC <- TAL_T1D_OC_res %>%
  filter(stable_fit =="TRUE")

TAL_T1D_T2D_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_T1D_vs_T2D.rds"))
TAL_T1D_T2D_res <- TAL_T1D_T2D_res$results
TAL_T1D_T2D <- TAL_T1D_T2D_res %>%
  filter(stable_fit =="TRUE")

TAL_T2D_LC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_T2D_vs_LC.rds"))
TAL_T2D_LC_res <- TAL_T2D_LC_res$results
TAL_T2D_LC <- TAL_T2D_LC_res %>%
  filter(stable_fit =="TRUE")

TAL_T2D_OC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_T2D_vs_OC.rds"))
TAL_T2D_OC_res <- TAL_T2D_OC_res$results
TAL_T2D_OC <- TAL_T2D_OC_res %>%
  filter(stable_fit =="TRUE")

TAL_OC_LC_res <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_2","nebula_TAL_OC_vs_LC.rds"))
TAL_OC_LC_res <- TAL_OC_LC_res$results
TAL_OC_LC <- TAL_OC_LC_res %>%
  filter(stable_fit =="TRUE")

Cell_list <- list(
  "PT_OC_vs_LC"   = PT_OC_LC,
  "PT_T1D_vs_LC"  = PT_T1D_LC,
  "PT_T2D_vs_LC"  = PT_T2D_LC,
  "PT_T1D_vs_T2D" = PT_T1D_T2D,
  "TAL_T1D_LC" = TAL_T1D_LC,
  "TAL_T1D_OC" = TAL_T1D_OC,
  "TAL_T1D_T2D" = TAL_T1D_T2D,
  "TAL_T2D_LC"= TAL_T2D_LC,
  "TAL_T2D_OC" = TAL_T2D_OC,
  "TAL_OC_LC" = TAL_OC_LC
)



```

```{r}
volcano_plots <- lapply(names(Cell_list), function(cc) {

  plot_df <- Cell_list[[cc]] %>%
    filter(
      is.finite(logFC_group_contrast),
      is.finite(p_adj),
      is.finite(neg_log10_fdr)
    ) %>%
    mutate(
      sig_class = case_when(
        p_adj < 0.05 & logFC_group_contrast >  0.5 ~ "Increased",
        p_adj < 0.05 & logFC_group_contrast < -0.5 ~ "Decreased",
        TRUE ~ "Not significant"
      )
    )

  top_labs <- plot_df %>%
    filter(p_adj < 0.05) %>%
    arrange(p_adj) %>%
    slice_head(n = 20)

  ggplot(
    plot_df,
    aes(
      x = logFC_group_contrast,
      y = neg_log10_fdr,
      color = sig_class
    )
  ) +
    geom_point(alpha = 0.65, size = 2) +
    geom_vline(
      xintercept = c(-0.5, 0.5),
      linetype = "dashed"
    ) +
    geom_hline(
      yintercept = -log10(0.05),
      linetype = "dashed"
    ) +
    geom_text_repel(
      data = top_labs,
      aes(label = gene),
      size = 3,
      max.overlaps = Inf
    ) +
    scale_color_manual(
      values = c(
        "Increased" = "orange3",
        "Decreased" = "purple4",
        "Not significant" = "grey75"
      )
    ) +
    coord_cartesian(
      xlim = c(-20, 20),
      ylim = c(
        0,
        ceiling(max(plot_df$neg_log10_fdr, na.rm = TRUE))
      )
    ) +
    labs(
      title = paste("NEBULA PT:", gsub("_", " ", cc)),
      x = "logFC group contrast",
      y = "-log10(FDR)",
      color = NULL
    ) +
    theme_classic(base_size = 14)

})
```

```{r}
names(volcano_plots) <- names(Cell_list)

volcano_plots$PT_OC_vs_LC
volcano_plots$PT_T1D_vs_LC
volcano_plots$PT_T2D_vs_LC
volcano_plots$PT_T1D_vs_T2D
volcano_plots$TAL_T1D_LC
volcano_plots$TAL_T1D_OC
volcano_plots$TAL_T1D_T2D
volcano_plots$TAL_T2D_LC
volcano_plots$TAL_T2D_OC
volcano_plots$TAL_OC_LC
```
```{r}
hist_plots <- lapply(names(Cell_list), function(cc) {

  plot_df <- Cell_list[[cc]]

  ggplot(
    plot_df,
    aes(x = logFC_group_contrast)
  ) +
    geom_histogram(bins = 60) +
    coord_cartesian(xlim = c(-20, 20)) +
    theme_classic(base_size = 14) +
    labs(
      title = paste("Distribution of NEBULA coefficients:", gsub("_", " ", cc)),
      x = "logFC group contrast",
      y = "Number of genes"
    )

})

names(hist_plots) <- names(Cell_list)
hist_plots$PT_OC_vs_LC
hist_plots$PT_T1D_vs_LC
hist_plots$PT_T2D_vs_LC
hist_plots$PT_T1D_vs_T2D
hist_plots$TAL_T1D_LC
```
```{r}
dot_plots <- lapply(names(Cell_list), function(cc) {

  plot_df <- Cell_list[[cc]] %>%
    filter(
      is.finite(logFC_group_contrast),
      is.finite(p_adj),
      is.finite(neg_log10_fdr)
    ) %>%
    mutate(
      sig_class = case_when(
        p_adj < 0.05 & logFC_group_contrast > 0.5 ~ "Higher in First Group",
        p_adj < 0.05 & logFC_group_contrast < -0.5 ~ "Lower in First Group"
      )
    )

  top_dot <- plot_df %>%
    filter(p_adj < 0.05) %>%
    arrange(p_adj) %>%
    slice_head(n = 30)

  ggplot(
    top_dot,
    aes(
      x = logFC_group_contrast,
      y = reorder(gene, logFC_group_contrast),
      color = sig_class,
      size = neg_log10_fdr
    )
  ) +
    geom_point() +
    geom_vline(xintercept = 0, linetype = "dashed") +
    scale_color_manual(values = c(
      "Higher positive group" = "red3",
      "Higher reference group" = "blue3"
    )) +
    labs(
      title = paste("Top NEBULA PT genes:", gsub("_", " ", cc)),
      x = "logFC group contrast",
      y = NULL,
      color = NULL,
      size = "-log10(FDR)"
    ) +
    theme_classic(base_size = 14)

})

names(dot_plots) <- names(Cell_list)

dot_plots$PT_OC_vs_LC
dot_plots$PT_T1D_vs_LC
dot_plots$PT_T2D_vs_LC
dot_plots$PT_T1D_vs_T2D
dot_plots$TAL_T1D_LC
```
```{r}
PT_OC_LC_results2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3", "nebula_PT_OC_vs_LC.rds"))
PT_OC_LC_results2 <- PT_OC_LC_results2$results
PT_OC_LC2 <- PT_OC_LC_results2 %>%
  filter(stable_fit == "TRUE")
PT_diag2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula", "nebula_3","nebula_PT_OC_vs_LC.rds"))
PT_diag2 <- PT_diag2$diagnostics

PT_T1D_LC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_PT_T1D_vs_LC.rds"))
PT_T1D_LC_res2 <- PT_T1D_LC_res2$results
PT_T1D_LC2 <- PT_T1D_LC_res2 %>%
  filter(stable_fit == "TRUE")

PT_T2D_LC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_PT_T2D_vs_LC.rds"))
PT_T2D_LC_res2 <- PT_T2D_LC_res2$results
PT_T2D_LC2 <- PT_T2D_LC_res2 %>%
  filter(stable_fit == "TRUE")

PT_T1D_T2D_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_PT_T1D_vs_T2d.rds"))
PT_T1D_T2D_res2 <- PT_T1D_T2D_res2$results
PT_T1D_T2D2 <- PT_T1D_T2D_res2 %>%
  filter(stable_fit == "TRUE")

TAL_T1D_LC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_T1D_vs_LC.rds"))
TAL_T1D_LC_res2 <- TAL_T1D_LC_res2$results
TAL_T1D_LC2 <- TAL_T1D_LC_res2 %>%
  filter(stable_fit =="TRUE")

TAL_T1D_OC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_T1D_vs_OC.rds"))
TAL_T1D_OC_res2 <- TAL_T1D_OC_res2$results
TAL_T1D_OC2 <- TAL_T1D_OC_res2 %>%
  filter(stable_fit =="TRUE")

TAL_T1D_T2D_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_T1D_vs_T2D.rds"))
TAL_T1D_T2D_res2 <- TAL_T1D_T2D_res2$results
TAL_T1D_T2D2 <- TAL_T1D_T2D_res2 %>%
  filter(stable_fit =="TRUE")

TAL_T2D_LC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_T2D_vs_LC.rds"))
TAL_T2D_LC_res2 <- TAL_T2D_LC_res2$results
TAL_T2D_LC2 <- TAL_T2D_LC_res2 %>%
  filter(stable_fit =="TRUE")

TAL_T2D_OC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_T2D_vs_OC.rds"))
TAL_T2D_OC_res2 <- TAL_T2D_OC_res2$results
TAL_T2D_OC2 <- TAL_T2D_OC_res2 %>%
  filter(stable_fit =="TRUE")

TAL_OC_LC_res2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_3","nebula_TAL_OC_vs_LC.rds"))
TAL_OC_LC_res2 <- TAL_OC_LC_res2$results
TAL_OC_LC2 <- TAL_OC_LC_res2 %>%
  filter(stable_fit =="TRUE")

Cell_list <- list(
  "PT_OC_vs_LC"   = PT_OC_LC2,
  "PT_T1D_vs_LC"  = PT_T1D_LC2,
  "PT_T2D_vs_LC"  = PT_T2D_LC2,
  "PT_T1D_vs_T2D" = PT_T1D_T2D2,
  "TAL_T1D_LC" = TAL_T1D_LC2,
  "TAL_T1D_OC" = TAL_T1D_OC2,
  "TAL_T1D_T2D" = TAL_T1D_T2D2,
  "TAL_T2D_LC"= TAL_T2D_LC2,
  "TAL_T2D_OC" = TAL_T2D_OC2,
  "TAL_OC_LC" = TAL_OC_LC2
)


```

```{r}
names(volcano_plots) <- names(Cell_list)

volcano_plots$PT_OC_vs_LC
volcano_plots$PT_T1D_vs_LC
volcano_plots$PT_T2D_vs_LC
volcano_plots$PT_T1D_vs_T2D
volcano_plots$TAL_T1D_LC
volcano_plots$TAL_T1D_OC
volcano_plots$TAL_T1D_T2D
volcano_plots$TAL_T2D_LC
volcano_plots$TAL_T2D_OC
volcano_plots$TAL_OC_LC
```
```{r}
names(hist_plots) <- names(Cell_list)
hist_plots$PT_OC_vs_LC
hist_plots$PT_T1D_vs_LC
hist_plots$PT_T2D_vs_LC
hist_plots$PT_T1D_vs_T2D
hist_plots$TAL_T1D_LC
```
```{r}
names(dot_plots) <- names(Cell_list)

dot_plots$PT_OC_vs_LC
dot_plots$PT_T1D_vs_LC
dot_plots$PT_T2D_vs_LC
dot_plots$PT_T1D_vs_T2D
dot_plots$TAL_T1D_LC
```

```{r}
PT_OC_LC_res3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_5","nebula_PT_OC_vs_LC.rds"))
PT_OC_LC_res3 <- PT_OC_LC_res3$results
PT_OC_LC3 <- PT_OC_LC_res3 %>%
  filter(stable_fit == "TRUE")

PT_T1D_LC_res3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_5","nebula_PT_T1D_vs_LC.rds"))
PT_T1D_LC_res3 <- PT_T1D_LC_res3$results
PT_T1D_LC3 <- PT_T1D_LC_res3 %>%
  filter(stable_fit == "TRUE")

PT_T1D_OC_res3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_5","nebula_PT_T1D_vs_OC.rds"))
PT_T1D_OC_res3 <- PT_T1D_OC_res3$results
PT_T1D_OC3 <- PT_T1D_OC_res3 %>%
  filter(stable_fit == "TRUE")

PT_T1D_T2D_res3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_5","nebula_PT_T1D_vs_T2D.rds"))
PT_T1D_T2D_res3 <- PT_T1D_T2D_res3$results
PT_T1D_T2D3 <- PT_T1D_T2D_res3 %>%
  filter(stable_fit == "TRUE")

PT_T2D_LC_res3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_5","nebula_PT_T2D_vs_LC.rds"))
PT_T2D_LC_res3 <- PT_T2D_LC_res3$results
PT_T2D_LC3 <- PT_T2D_LC_res3 %>%
  filter(stable_fit == "TRUE")

Cell_list2 <- list(
  "PT_OC_vs_LC3" = PT_OC_LC3,
  "PT_T1D_vs_LC3"  = PT_T1D_LC3,
  "PT_T1D_vs_OC3" = PT_T1D_OC3,
  "PT_T1D_vs_T2D3" = PT_T1D_T2D3,
  "PT_T2D_vs_LC3"  = PT_T2D_LC3
)



```

```{r}
volcano_plots <- lapply(names(Cell_list2), function(cc) {

  plot_df <- Cell_list2[[cc]] %>%
    filter(
      is.finite(logFC_group_contrast),
      is.finite(p_adj),
      is.finite(neg_log10_fdr)
    ) %>%
    mutate(
      sig_class = case_when(
        p_adj < 0.05 & logFC_group_contrast >  0.5 ~ "Increased",
        p_adj < 0.05 & logFC_group_contrast < -0.5 ~ "Decreased",
        TRUE ~ "Not significant"
      )
    )

  top_labs <- plot_df %>%
    filter(p_adj < 0.05) %>%
    arrange(p_adj) %>%
    slice_head(n = 20)

  ggplot(
    plot_df,
    aes(
      x = logFC_group_contrast,
      y = neg_log10_fdr,
      color = sig_class
    )
  ) +
    geom_point(alpha = 0.65, size = 2) +
    geom_vline(
      xintercept = c(-0.5, 0.5),
      linetype = "dashed"
    ) +
    geom_hline(
      yintercept = -log10(0.05),
      linetype = "dashed"
    ) +
    geom_text_repel(
      data = top_labs,
      aes(label = gene),
      size = 3,
      max.overlaps = Inf
    ) +
    scale_color_manual(
      values = c(
        "Increased" = "orange3",
        "Decreased" = "purple4",
        "Not significant" = "grey75"
      )
    ) +
    coord_cartesian(
      xlim = c(-20, 20),
      ylim = c(
        0,
        ceiling(max(plot_df$neg_log10_fdr, na.rm = TRUE))
      )
    ) +
    labs(
      title = paste("NEBULA PT:", gsub("_", " ", cc)),
      x = "logFC group contrast",
      y = "-log10(FDR)",
      color = NULL
    ) +
    theme_classic(base_size = 14)

})
```

```{r}
names(volcano_plots) <- names(Cell_list2)

volcano_plots$PT_OC_vs_LC3
volcano_plots$PT_T1D_vs_LC3
volcano_plots$PT_T1D_vs_OC3
volcano_plots$PT_T1D_vs_T2D3
volcano_plots$PT_T2D_vs_LC3
```
```{r}
names(hist_plots) <- names(Cell_list)
hist_plots$PT_OC_vs_LC
hist_plots$PT_T1D_vs_LC
hist_plots$PT_T1D_vs_OC
hist_plots$PT_T1D_vs_T2D
hist_plots$PT_T2D_vs_LC
```
```{r}
names(dot_plots) <- names(Cell_list)

dot_plots$PT_OC_vs_LC
dot_plots$PT_T1D_vs_LC
dot_plots$PT_T1D_vs_OC
dot_plots$PT_T1D_vs_T2D
dot_plots$PT_T2D_vs_LC

```


#----------------------------
#archived code
#keeping for troubleshooting
#----------------------------
```{r}
PT_test2 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula", "nebula_2nebula_PT_OC_vs_LC.rds" ))
PT_test2 <- PT_test2$results

PT_test3 <- readRDS(file = file.path(dir.results, "scRNA results", "nebula","nebula_PT_OC_vs_LC.rds"))
PT_test3 <- PT_test3$results

PT_test3 <- PT_test3 %>%
  filter(stable_fit == "TRUE")

nebula_plot_df2 <- PT_test2 %>%
  filter(
    is.finite(logFC_group_contrast),
    is.finite(p_adj),
    is.finite(neg_log10_fdr)
  ) %>%
  mutate(
    sig_class = case_when(
      p_adj < 0.05 & logFC_group_contrast > 0 ~ "Increased in OC",
      p_adj < 0.05 & logFC_group_contrast < 0 ~ "Decreased in OC",
      TRUE ~ "Not significant"
    )
  )
  
```

```{r}
top_labs2 <- nebula_plot_df2 %>%
  filter(p_adj < 0.05) %>%
  arrange(p_adj) %>%
  slice_head(n = 20)

ggplot(
  nebula_plot_df2,
  aes(
    x = logFC_group_contrast,
    y = neg_log10_fdr,
    color = sig_class
  )
) +
  geom_point(alpha = 0.65, size = 2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_text_repel(
    data = top_labs2,
    aes(label = gene),
    size = 3,
    max.overlaps = Inf
  ) +
  scale_color_manual(values = c(
    "Increased in OC" = "orange3",
    "Decreased in OC" = "purple4",
    "Not significant" = "grey75"
  )) +
  coord_cartesian(
    xlim = c(-600, 600),
    ylim = c(0, 300)
  ) +
  labs(
    title = "NEBULA PT: Obese Control vs Lean Control",
    subtitle = "LC is the reference; positive logFC = increased in OC",
    x = "logFC relative to LC",
    y = "-log10(FDR)",
    color = NULL
  ) +
  theme_classic(base_size = 14)
```
```{r}
ggplot(
  nebula_plot_df2,
  aes(x = logFC_group_contrast)
) +
  geom_histogram(bins = 60) +
  coord_cartesian(xlim = c(-1000, 1000)) +
  theme_classic(base_size = 14) +
  labs(
    title = "Distribution of NEBULA group coefficients",
    x = "logFC group contrast",
    y = "Number of genes"
  )
```

```{r}
top_dot2 <- nebula_plot_df2 %>%
  filter(p_adj < 0.05) %>%
  arrange(p_adj) %>%
  slice_head(n = 30)

ggplot(
  top_dot2,
  aes(
    x = logFC_group_contrast,
    y = reorder(gene, logFC_group_contrast),
    color = sig_class,
    size = neg_log10_fdr
  )
) +
  geom_point() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = c(
    "Higher in OC" = "red3",
    "Higher in LC" = "blue3"
  )) +
  labs(
    title = "Top NEBULA PT genes: OC vs LC",
    x = "NEBULA logFC group contrast",
    y = NULL,
    color = NULL,
    size = "-log10(FDR)"
  ) +
  theme_classic(base_size = 14)
```

```{r}
top_labs3 <- nebula_plot_df3 %>%
  filter(p_adj < 0.05) %>%
  arrange(p_adj) %>%
  slice_head(n = 20)

ggplot(
  nebula_plot_df3,
  aes(
    x = logFC_group_contrast,
    y = neg_log10_fdr,
    color = sig_class
  )
) +
  geom_point(alpha = 0.65, size = 2) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_text_repel(
    data = top_labs3,
    aes(label = gene),
    size = 3,
    max.overlaps = Inf
  ) +
  scale_color_manual(values = c(
    "Increased in OC" = "orange3",
    "Decreased in OC" = "purple4",
    "Not significant" = "grey75"
  )) +
  coord_cartesian(
    xlim = c(-20, 20),
    ylim = c(0, 10)
  ) +
  labs(
    title = "NEBULA PT: Obese Control vs Lean Control",
    subtitle = "LC is the reference; positive logFC = increased in OC",
    x = "logFC relative to LC",
    y = "-log10(FDR)",
    color = NULL
  ) +
  theme_classic(base_size = 14)
```

```{r}
top_dot3 <- nebula_plot_df3 %>%
  filter(p_adj < 0.05) %>%
  arrange(p_adj) %>%
  slice_head(n = 30)

ggplot(
  top_dot3,
  aes(
    x = logFC_group_contrast,
    y = reorder(gene, logFC_group_contrast),
    color = sig_class,
    size = neg_log10_fdr
  )
) +
  geom_point() +
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_color_manual(values = c(
    "Higher in OC" = "red3",
    "Higher in LC" = "blue3"
  )) +
  labs(
    title = "Top NEBULA PT genes: OC vs LC",
    x = "NEBULA logFC group contrast",
    y = NULL,
    color = NULL,
    size = "-log10(FDR)"
  ) +
  theme_classic(base_size = 14)
```
```{r}
ggplot(
  nebula_plot_df3,
  aes(x = logFC_group_contrast)
) +
  geom_histogram(bins = 10) +
  coord_cartesian(xlim = c(-50, 50)) +
  theme_classic(base_size = 14) +
  labs(
    title = "Distribution of NEBULA group coefficients",
    x = "logFC group contrast",
    y = "Number of genes"
  )
```
