---
title: "Proteomics and HTN - SOMAScan correlation"
author: "Laura Pyle, Ye Ji Choi & Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    page-layout: full
editor: source
execute:
  echo: false
  message: false
---

```{r libraries}
#| include: false
library(psych)
library(corrplot)
library(pander)
library(dplyr)
library(tableone)
library(knitr)
library(gtools)
library(ggpubr)
library(parallel)
library(limma)
library(Hmisc)
library(knitr)
library(tidyverse)
library(gtsummary)
library(ggpubr)
library(lmerTest)
library(parallel)
library(emmeans)
library(RColorBrewer)
library(VennDiagram)
library(broom.mixed)
library(readxl)
# Print all pander tables
panderOptions("knitr.auto.asis", FALSE)

# specify user for paths
user <- Sys.info()[["user"]]
if (user == "laurapyle") {
  data_path <- '/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive'
} else if (user == "lpyle") {
  data_path <- "/Users/lpyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive"
} else if (user == "pylell") {
  data_path <- "/Users/pylell/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive"
} else if (user == "kristenmiller") {
  data_path <- "/Users/kristenmiller/Library/CloudStorage/OneDrive-UW/Laura Pyle's files - Biostatistics Core Shared Drive"
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r data import}
setwd(data_path)
#| include: false
prot_include <- c("SEZ6L","NCAM-120","NCAM1","SCG3","Aminoacylase-1",
"WFKN2","ESPN","PURA1","SERB","CHL1","LSAMP",
"Growth hormone receptor","OFUT1")
seq_include <- c("seq.19563.3","seq.4498.62",
"seq.20161.41","seq.7957.2","seq.3343.1","seq.24957.6",
"seq.13998.26","seq.24681.2","seq.8958.51","seq.2999.6",
"seq.2948.58","seq.5634.39",
#kristen added these on 5/18/2026: top 20 from TODAY
"seq.13408.23","seq.5307.12","seq.23569.53",
"seq.3235.50","seq.6506.54","seq.7735.17",
"seq.17755.5","seq.18896.23","seq.15487.164")
load("./Proteomics and HTN/Data_Cleaned/analysis_dataset.RData")
top_htn <- top_htn_df %>%
  filter(AptName %in% seq_include) %>%
  slice_max(abs(log(estimate)), n = 21) %>%
  pull(AptName)
df <- NULL

# source("~/GitHub/CHCO-Code/Petter Bjornstad/Proteomics and DKD/create_today_dkd_analysis_dataset.R")
# load("/Volumes/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/Proteomics and HTN/Data_Cleaned/analysis_dataset.RData")
load("./Teen Labs/Data_Cleaned/analysis_dataset.RData")
# Tim already log transformed proteins when creating dataframe
df$map <- NA
for (i in 1:nrow(df)) {
  df[i,]$map <- df[i,]$dbp + ((1/3) * (df[i,]$sbp - df[i,]$dbp))
}
df_long_keep <- df %>% select(ID, visit, sbp, dbp, bmi, all_of(seq_include))

load("./TODAY subaward/Somalogic data raw/analytes.Rdata")
analytes_keep <- analytes %>% filter(AptName %in% seq_include)

# create df with change in SBP/DBP and proteins between baseline and 1 year
deltas_temp <- df %>% filter(visit %in% c("Month 1", "Year 1"))
deltas_temp <- deltas_temp %>% select(ID, visit, sbp, dbp, bmi, all_of(seq_include))
deltas <- reshape(deltas_temp, timevar = "visit", idvar = "ID", direction = "wide")
deltas$sbp <- deltas$`sbp.Year 1` - deltas$`sbp.Month 1`
deltas$dbp <- deltas$`dbp.Year 1` - deltas$`dbp.Month 1`
deltas$bmi <- deltas$`bmi.Year 1` - deltas$`bmi.Month 1`
deltas$seq.19563.3 <- deltas$`seq.19563.3.Year 1` - deltas$`seq.19563.3.Month 1`
deltas$seq.4498.62 <- deltas$`seq.4498.62.Year 1` - deltas$`seq.4498.62.Month 1`
deltas$seq.20161.41 <- deltas$`seq.20161.41.Year 1` - deltas$`seq.20161.41.Month 1`
deltas$seq.7957.2 <- deltas$`seq.7957.2.Year 1` - deltas$`seq.7957.2.Month 1`
deltas$seq.3343.1 <- deltas$`seq.3343.1.Year 1` - deltas$`seq.3343.1.Month 1`
deltas$seq.24957.6 <- deltas$`seq.24957.6.Year 1` - deltas$`seq.24957.6.Month 1`
deltas$seq.13998.26 <- deltas$`seq.13998.26.Year 1` - deltas$`seq.13998.26.Month 1`
deltas$seq.24681.2 <- deltas$`seq.24681.2.Year 1` - deltas$`seq.24681.2.Month 1`
deltas$seq.8958.51 <- deltas$`seq.8958.51.Year 1` - deltas$`seq.8958.51.Month 1`
deltas$seq.2999.6 <- deltas$`seq.2999.6.Year 1` - deltas$`seq.2999.6.Month 1`
deltas$seq.2948.58 <- deltas$`seq.2948.58.Year 1` - deltas$`seq.2948.58.Month 1`
deltas$seq.5634.39 <- deltas$`seq.5634.39.Year 1` - deltas$`seq.5634.39.Month 1`
deltas$seq.13408.23 <- deltas$`seq.13408.23.Year 1` - deltas$`seq.13408.23.Month 1`
deltas$seq.5307.12 <- deltas$`seq.5307.12.Year 1` - deltas$`seq.5307.12.Month 1`
deltas$seq.23569.53 <- deltas$`seq.23569.53.Year 1` - deltas$`seq.23569.53.Month 1`
deltas$seq.3235.50 <- deltas$`seq.3235.50.Year 1` - deltas$`seq.3235.50.Month 1`
deltas$seq.6506.54 <- deltas$`seq.6506.54.Year 1` - deltas$`seq.6506.54.Month 1`
deltas$seq.7735.17 <- deltas$`seq.7735.17.Year 1` - deltas$`seq.7735.17.Month 1`
deltas$seq.17755.5 <- deltas$`seq.17755.5.Year 1` - deltas$`seq.17755.5.Month 1`
deltas$seq.18896.23 <- deltas$`seq.18896.23.Year 1` - deltas$`seq.18896.23.Month 1`
deltas$seq.15487.164 <- deltas$`seq.15487.164.Year 1` - deltas$`seq.15487.164.Month 1`

deltas_km <- deltas 

deltas <- deltas %>% select(ID, sbp, dbp, bmi, seq.19563.3, seq.4498.62, seq.20161.41, seq.7957.2, seq.3343.1, 
                            seq.24957.6, seq.13998.26, seq.24681.2, seq.8958.51, seq.2999.6, seq.2948.58, seq.5634.39 )

```

```{r functions}
#### validation analysis added by kristen on 5/18: adding BMI as a covariate
names(deltas_km) <- gsub(" ", ".", names(deltas_km))

sbp_lm_results <- list()
for (i in seq_include){
  sbp_unad <- lm(as.formula(paste0("sbp ~", i,".Month.1")), data = deltas_km)
  sbp_unad_sum<-data.frame(summary(sbp_unad)$coefficients)
  sbp_unad_keep<-sbp_unad_sum[grep("seq", rownames(sbp_unad_sum)), ]
  
  
  sbp_bmi_adj <- lm(as.formula(paste0("sbp ~", i, ".Month.1+bmi")), data = deltas_km)
  sbp_adj_sum<-data.frame(summary(sbp_bmi_adj)$coefficients)
  sbp_adj_keep<-sbp_adj_sum[grep("seq", rownames(sbp_adj_sum)), ]
  
  sbp_out <- data.frame(
    protein = i,
    unadj_estimate = sbp_unad_keep$Estimate,
    unadj_se = sbp_unad_keep$Std..Error,
    unadj_p = sbp_unad_keep$Pr...t..,
    adj_estimate = sbp_adj_keep$Estimate,
    adj_se = sbp_adj_keep$Std..Error,
    adj_p = sbp_adj_keep$Pr...t..
  )
  
  sbp_lm_results[[i]] <- sbp_out
}
sbp_lm_results_df <- do.call(rbind, sbp_lm_results)

sbp_lm_results_df$sbp_direction<-NA
sbp_lm_results_df$sbp_direction[sbp_lm_results_df$unadj_estimate<0 & sbp_lm_results_df$adj_estimate<0]<-"negative"
sbp_lm_results_df$sbp_direction[sbp_lm_results_df$unadj_estimate>0 & sbp_lm_results_df$adj_estimate>0]<-"positive"

sbp_lm_results_df$sbp_strength<-NA
sbp_lm_results_df$sbp_strength[sbp_lm_results_df$sbp_direction=="negative" & sbp_lm_results_df$unadj_estimate<sbp_lm_results_df$adj_estimate]<-"weaken"
sbp_lm_results_df$sbp_strength[sbp_lm_results_df$sbp_direction=="negative" & sbp_lm_results_df$unadj_estimate>sbp_lm_results_df$adj_estimate]<-"strengthen"
sbp_lm_results_df$sbp_strength[sbp_lm_results_df$sbp_direction=="positive" & sbp_lm_results_df$unadj_estimate<sbp_lm_results_df$adj_estimate]<-"strengthen"
sbp_lm_results_df$sbp_strength[sbp_lm_results_df$sbp_direction=="positive" & sbp_lm_results_df$unadj_estimate>sbp_lm_results_df$adj_estimate]<-"weaken"

dbp_lm_results <- list()
for (i in seq_include){
  dbp_unad <- lm(as.formula(paste0("dbp ~", i,".Month.1")), data = deltas_km)
  dbp_unad_sum<-data.frame(summary(dbp_unad)$coefficients)
  dbp_unad_keep<-dbp_unad_sum[grep("seq", rownames(dbp_unad_sum)), ]
  
  
  dbp_bmi_adj <- lm(as.formula(paste0("dbp ~", i, ".Month.1+bmi")), data = deltas_km)
  dbp_adj_sum<-data.frame(summary(dbp_bmi_adj)$coefficients)
  dbp_adj_keep<-dbp_adj_sum[grep("seq", rownames(dbp_adj_sum)), ]
  
  dbp_out <- data.frame(
    protein = i,
    unadj_estimate = dbp_unad_keep$Estimate,
    unadj_se = dbp_unad_keep$Std..Error,
    unadj_p = dbp_unad_keep$Pr...t..,
    adj_estimate = dbp_adj_keep$Estimate,
    adj_se = dbp_adj_keep$Std..Error,
    adj_p = dbp_adj_keep$Pr...t..
  )
  
  dbp_lm_results[[i]] <- dbp_out
}
dbp_lm_results_df <- do.call(rbind, dbp_lm_results)

dbp_lm_results_df$dbp_direction<-NA
dbp_lm_results_df$dbp_direction[dbp_lm_results_df$unadj_estimate<0 & dbp_lm_results_df$adj_estimate<0]<-"negative"
dbp_lm_results_df$dbp_direction[dbp_lm_results_df$unadj_estimate>0 & dbp_lm_results_df$adj_estimate>0]<-"positive"

dbp_lm_results_df$dbp_strength<-NA
dbp_lm_results_df$dbp_strength[dbp_lm_results_df$dbp_direction=="negative" & dbp_lm_results_df$unadj_estimate<dbp_lm_results_df$adj_estimate]<-"weaken"
dbp_lm_results_df$dbp_strength[dbp_lm_results_df$dbp_direction=="negative" & dbp_lm_results_df$unadj_estimate>dbp_lm_results_df$adj_estimate]<-"strengthen"
dbp_lm_results_df$dbp_strength[dbp_lm_results_df$dbp_direction=="positive" & dbp_lm_results_df$unadj_estimate<dbp_lm_results_df$adj_estimate]<-"strengthen"
dbp_lm_results_df$dbp_strength[dbp_lm_results_df$dbp_direction=="positive" & dbp_lm_results_df$unadj_estimate>dbp_lm_results_df$adj_estimate]<-"weaken"

#write files
#write.csv(sbp_lm_results_df,"./TODAY subaward/TODAY HTN and DKD output/TeenLABS_SBP_bmiadjusted_lm.csv", row.names = F)
#write.csv(dbp_lm_results_df,"./TODAY subaward/TODAY HTN and DKD output/TeenLABS_DBP_bmiadjusted_lm.csv", row.names = F)

#adjudicate with TODAY findings:
today_hr<-data.frame(read_excel("/Users/kristenmiller/Library/CloudStorage/OneDrive-UW/Melissa Leroux's files - Tommerdahl Bjornstad Files/Manuscripts/TODAY Hypertension Diabetes Care Proteomics/Manuscript May 2026/TODAY somalogic Cox models scaled baseline adjusted HTN model selection_TOP20.xlsx",sheet = "HTN CPH base"))
today_hr$protein<-today_hr$Aptamer.Name

today_hr<-merge(today_hr,sbp_lm_results_df[,c("protein","sbp_direction","sbp_strength")],by="protein",all=T)
km_validation_study<-merge(today_hr,dbp_lm_results_df[,c("protein","dbp_direction","dbp_strength")],by="protein",all=T)
km_validation_study

km_validation_study$sbp_agreement<-NA
km_validation_study$sbp_agreement[km_validation_study$HR<1 & km_validation_study$sbp_direction=="negative"]<-"agree"
km_validation_study$sbp_agreement[km_validation_study$HR<1 & km_validation_study$sbp_direction=="positive"]<-"disagree"
km_validation_study$sbp_agreement[km_validation_study$HR>1 & km_validation_study$sbp_direction=="positive"]<-"agree"
km_validation_study$sbp_agreement[km_validation_study$HR>1 & km_validation_study$sbp_direction=="negative"]<-"disagree"

km_validation_study$dbp_agreement<-NA
km_validation_study$dbp_agreement[km_validation_study$HR<1 & km_validation_study$dbp_direction=="negative"]<-"agree"
km_validation_study$dbp_agreement[km_validation_study$HR<1 & km_validation_study$dbp_direction=="positive"]<-"disagree"
km_validation_study$dbp_agreement[km_validation_study$HR>1 & km_validation_study$dbp_direction=="positive"]<-"agree"
km_validation_study$dbp_agreement[km_validation_study$HR>1 & km_validation_study$dbp_direction=="negative"]<-"disagree"

km_validation_study<-km_validation_study[,c("protein","HR","sbp_direction","sbp_strength","dbp_direction","dbp_strength","sbp_agreement","dbp_agreement")]
```

