---
title: "BaHZING Results"
format: 
  docx:
    fig-width: 7
    fig-height: 5
    dpi: 300
execute:
  echo: false
  warning: false
  message: false
---

# 1. Set Up 
```{r setup}
#Set Directories
#Direcotry for where simulation results files are saved
dir.dat <- c("/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive/Hailey Hampson/1_Ongoing Projects/Microbiome Manuscript/Simulation Data 01_08/Simularion Results Data/Final")

#Directory for where HPC materials are saved
dir.dat2 <- c("/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive/Hailey Hampson/1_Ongoing Projects/Microbiome Manuscript/Simulation Data 01_08/HPC Data")

#Directory for where all code materials are saved - change to file path that has correct folder
dir.code <- c("/Users/hhampson/CHCO-Code/Petter Bjornstad/Simulation Analysis/Simulation Code/Materials for Code Review")

#Directory to save results - change to file path you want
dir.results <- c("/Users/hhampson/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Biostatistics Core Shared Drive/Hailey Hampson/1_Ongoing Projects/Microbiome Manuscript/Simulation Results")

#Source Packages
source(fs::path(dir.code,"Libraries.R"))

# Source Functions
source(fs::path(dir.code,"Functions.R"))

# Set theme for all plots
theme_set(theme_bw(base_family = "Times", base_size = 11))
```

# 2. Process Results
```{r load-data}
# Load & process simulation results
#Which Scenarios do you want to process?
#To examine a single scenario, fill in the scenario number below -OR- for all fill in as "all": 
scenario_num <- 1 #Replace with scenario of interest (1 to 9) or "all"

#Run processing code
source(fs::path(dir.code,"Data_Cleaning.R"))
```

# 3. Visualizations 
## a. Mixture Effect Estimates
```{r scheme1-plots, fig.width=14, fig.height=12}
mixture_plot <- create_estimate_plots(all_formatted_results, 
                                    analysis_type = "mixture",
                                    n_sample_iterations = 25,
                                    save_plots = TRUE,
                                    seed=123) #Default seed set to 123, can change for different sample
mixture_plot
```

## b. Individual Effect Estimates
```{r scheme1-plots, fig.width=14, fig.height=12}
individual_plot <- create_estimate_plots(all_formatted_results, 
                                    analysis_type = "individual",
                                    n_sample_iterations = 25,
                                    save_plots = TRUE)
individual_plot
```

# 4. Calculate Measures of Perormance
## a. Sensitivity Measures - Individual Exposure
```{r sensitivity-individual, fig.width=10, fig.height=8}
individual_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "individual",
  save_plots = TRUE,
  save_csv = TRUE
)

individual_sens$heatmap_specificity
individual_sens$heatmap_fdr
```

## b. Sensitivity Measures - Mixture Exposure
```{r sensitivity-mixture, fig.width=10, fig.height=8}
mixture_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "mixture",
  save_plots = TRUE,
  save_csv = TRUE
)

mixture_sens$heatmap_specificity
mixture_sens$heatmap_fdr
```

## c. Bias- Mixture
```{r bias, fig.width=10, fig.height=8}
# Calculate bias at species level
bias_mixute <- calculate_bias_species(
  data = all_formatted_results,
  analysis_type = "mixture",
  save_plot = TRUE,
  save_csv = TRUE
)
bias_mixute$heatmap_overall
bias_mixute$heatmap_associated
bias_mixute$heatmap_not_associated
```

## d. Bias- Individual
```{r bias, fig.width=10, fig.height=8}
# Calculate bias at species level
bias_individual <- calculate_bias_species(
  data = all_formatted_results,
  analysis_type = "individual",
  save_plot = TRUE,
  save_csv = TRUE
)
bias_individual$heatmap_overall
bias_individual$heatmap_associated
bias_individual$heatmap_not_associated
```