---
title: "BaHZING Results"
format: 
  docx:
    fig-width: 7
    fig-height: 5
    dpi: 300
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
source("Libraries.R")

# Source your processing functions if they're in separate files
source("Functions.R")

# Set theme for all plots
theme_set(theme_bw(base_family = "Times", base_size = 11))
```

# Simulation Overview
```{r load-data}
# Load & process simulation results
source("Simulation_Results_Processing.R")
```

## Mixture Effect Estimates - Color Scheme 1
```{r scheme1-plots, fig.width=14, fig.height=12}
mixture_s1 <- create_estimate_plots_scheme1(all_formatted_results, 
                                            analysis_type = "mixture")
mixture_s1$option1
mixture_s1$option2
mixture_s1$option3
```

## Mixture Effect Estimates - Color Scheme 2
```{r scheme2-plots, fig.width=14, fig.height=12}
mixture_s2 <- create_estimate_plots_scheme2(all_formatted_results, 
                                            analysis_type = "mixture")
mixture_s2$option1
mixture_s2$option2
mixture_s2$option3
```

## Individual Effect Estimates - Color Scheme 1
```{r individual-plots-scheme1, fig.width=14, fig.height=12}
individual_s1 <- create_estimate_plots_scheme1(all_formatted_results, 
                                               analysis_type = "individual")
individual_s1$option1
individual_s1$option2
individual_s1$option3
```

## Individual Effect Estimates - Color Scheme 2
```{r individual-plots-scheme2, fig.width=14, fig.height=12}
individual_s2 <- create_estimate_plots_scheme2(all_formatted_results, 
                                               analysis_type = "individual")
individual_s2$option1
individual_s2$option2
individual_s2$option3
```

## Sensitivity Measures - Individual Exposure
```{r sensitivity-individual, fig.width=10, fig.height=8}
individual_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "individual"
)

individual_sens$heatmap_high_good
individual_sens$heatmap_low_good
```

## Sensitivity Measures - Mixture Exposure
```{r sensitivity-mixture, fig.width=10, fig.height=8}
mixture_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "mixture"
)

mixture_sens$heatmap_high_good
mixture_sens$heatmap_low_good
```
