---
title: "BaHZING Results"
format: 
  docx:
    fig-width: 7
    fig-height: 5
    dpi: 300
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
#Set Directories
# dir.dat <- c("/Users/hhampson/Library/Mobile Documents/com~apple~CloudDocs/BHRM_microbiome/Simulation Code 11_04/Simularion Results/Final")
# dir.code <- c("/Users/hhampson/Library/Mobile Documents/com~apple~CloudDocs/BHRM_microbiome/Simulation Code 11_04/HPC Code")
# dir.lib <- c("/Users/hhampson/Library/Mobile Documents/com~apple~CloudDocs/BHRM_microbiome/Simulation Code 11_04")
# dir.results <- c("/Users/hhampson/Library/CloudStorage/OneDrive-UW/Biostatistics Core Shared Drive/Hailey Hampson/1_Ongoing Projects/Microbiome Manuscript/Simulation Results/Processed Simulation Results")

#Source Packages
source("Libraries.R")

# Source Functions
source("Functions.R")

# Set theme for all plots
theme_set(theme_bw(base_family = "Times", base_size = 11))
```

# Simulation Overview
```{r load-data}
# Load & process simulation results
source("Data_Cleaning.R")
```

## Mixture Effect Estimates
```{r scheme1-plots, fig.width=14, fig.height=12}
mixture_plot <- create_estimate_plots(all_formatted_results, 
                                    analysis_type = "mixture",
                                    n_sample_iterations = 25)
mixture_plot
```


## Individual Effect Estimates
```{r scheme1-plots, fig.width=14, fig.height=12}
individual_plot <- create_estimate_plots(all_formatted_results, 
                                    analysis_type = "individual",
                                    n_sample_iterations = 25)
individual_plot
```

## Sensitivity Measures - Individual Exposure
```{r sensitivity-individual, fig.width=10, fig.height=8}
individual_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "individual"
)

individual_sens$heatmap_high_good
individual_sens$heatmap_low_good
```

## Sensitivity Measures - Mixture Exposure
```{r sensitivity-mixture, fig.width=10, fig.height=8}
mixture_sens <- calculate_sensitivity_measures(
  all_formatted_results,
  analysis_type = "mixture"
)

mixture_sens$heatmap_specificity
mixture_sens$heatmap_fdr


```
##Bias 
```{r bias, fig.width=10, fig.height=8}
# Calculate bias at species level
bias_results <- calculate_bias_species(
  data = all_formatted_results,
  analysis_type = "mixture",
  save_plot = TRUE,
  save_csv = TRUE
)
bias_results$heatmap_overall
bias_results$heatmap_associated
bias_results$heatmap_not_associated
```
