---
title: "EDNSG Presentation 2025"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r echo = F}
library(dplyr)
library(tidyr)
library(Hmisc)
library(purrr)
library(arsenal)
```

```{r echo = F}
dat <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = c(" ", "", "-9999",-9999))
st_ids <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Spatial transcriptomics/spatial_transcriptomics_ids.csv")
pb90_ids <- readRDS("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/scRNA/data_clean/pb90_meta.rds")
```

```{r echo = F}
st_dat_sub <- dat %>%
  filter(paste0(record_id, visit) %in% paste0(st_ids$x, st_ids$visit)) %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) %>%
  mutate(race_ethnicity_condensed = case_when(race == "White" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                              race == "Black or African American" & 
                                                ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                              ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                              T ~ "Not Hispanic or Latino Other"),
         sglt2i_ever = case_when(group == "Lean Control" ~ "No", T~ sglt2i_ever), 
         group_visit = case_when(group == "Lean Control" ~ "Lean Control",
                                 group == "Type 2 Diabetes" & visit == "baseline" ~ "T2D Pre-MBS",
                                 group == "Type 2 Diabetes" ~ "T2D Post-MBS")) 

```

```{r echo = F}
# Table 1

summary(tableby(group_visit ~ age + sex + bmi + kwt(acr_u, "Nmiss", "median", "q1q3") + hba1c + sglt2i_ever + eGFR_CKD_epi + sbp + dbp + map, data = st_dat_sub))
```
