---
title: "VSG vs SMT urine metabolomics"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(ggpubr)
library(readxl)
library(stringr)
library(tidyr)
library(dplyr)
library(parallel)

# specify user for paths
user <- Sys.info()[["user"]]
if (user == "laurapyle") {
  data_path <- '/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/AstraZeneca'
  vsg_path <- '/Users/laurapyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/VSG'
} else if (user == "lpyle") {
  data_path <- '/Users/lpyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/AstraZeneca'
  vsg_path <- '/Users/lpyle/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/VSG'
} else {
  stop("Unknown user: please specify root path for this user.")
}

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
# QUESTIONS
# In the RPC2 analysis, we did not normalize by creatinine - I think this is because the metabolites are semi-quantitative

# based on emails with Filippos Michopoulos, I believe this is the correct version of the data to use
# metabolites are log-2 transformed
# time has been merged with ID
filename <- "RPC2 targeted normalised data combined PN with dose.xlsx"
full_path <- file.path(data_path, filename)
data <- read_xlsx(full_path, sheet = "Targeted data")
#creat <- read_xlsx(full_path, sheet = "Creatinine quant")
#data <- left_join(data, creat, by = "ID")
data <- data %>% filter(!Dose == "QC")
data$Peak.Area <- data$`Peak Area`
data$`Peak Area` <- NULL
data$Peak.Area <- as.numeric(data$Peak.Area)
data_keep <- data %>% select(ID, Dose, Metabolite, Peak.Area)

data_wide <- data_keep %>%
  pivot_wider(
    id_cols = c(ID, Dose),
    names_from = Metabolite,
    values_from = Peak.Area
  )
data_wide <- data_wide %>% mutate(visit = case_when(
  str_detect(ID, "12M") ~ "12 months",
  str_detect(ID, "BL") ~ "Baseline",
  .default = "Baseline"
))
data_wide <- data_wide %>% mutate(ID = str_remove(ID, "_BL"))
data_wide <- data_wide %>% mutate(ID = str_remove(ID, "_12M"))
data_wide$ID <- str_replace(data_wide$ID, "IT2D", "IT")
data_wide$ID <- str_replace_all(data_wide$ID, "_", "-")
data_wide$record_id <- data_wide$ID
data_wide$ID <- NULL

# create separate dfs for IMPROVE and RH/RH2 since they will be merged slightly differently
data_wide_improve <- data_wide %>% filter(grepl("IT", record_id))
data_wide_improve$updated_pre_post <- ifelse(data_wide_improve$visit == "Baseline", "pre", "post")
data_wide_improve$updated_record_id <- data_wide_improve$record_id
data_wide_rh <- data_wide %>% filter(grepl("RH", record_id))

# read in Long's data
filename <- "patient_cohort_prepost_table.xlsx"
full_path <- file.path(vsg_path, filename)
vsg_smt_patients <- read_xlsx(full_path, sheet = "patient_cohort_prepost_table")
vsg_smt_patients$record_id <- ifelse(vsg_smt_patients$cohort == "IMPROVE", str_replace(vsg_smt_patients$record_id, "_", "-"), vsg_smt_patients$record_id)
vsg_smt_patients <- vsg_smt_patients %>% mutate(time = case_when(
  cohort == "IMPROVE" & updated_pre_post == "pre" ~ "baseline",
  cohort == "IMPROVE" & updated_pre_post == "post" ~ "12_months_post_surgery",
  cohort != "IMPROVE" ~ "baseline"
  )
)
vsg_smt_patients$updated_record_id <- str_replace(vsg_smt_patients$updated_record_id, "_", "-")
vsg_smt_patients_improve <- vsg_smt_patients %>% filter(updated_cohort == "IMPROVE")
vsg_smt_patients_improve_keep <- vsg_smt_patients_improve %>% select(updated_record_id, updated_pre_post)
vsg_smt_patients_rh <- vsg_smt_patients %>% filter(updated_cohort %in% c("RENAL HEIR", "RENAL HEIRITAGE"))

final_improve <- left_join(vsg_smt_patients_improve_keep, data_wide_improve, by = c("updated_record_id", "updated_pre_post"))
final_rh <- left_join(vsg_smt_patients_rh, data_wide_rh, by = "record_id")
final_rh <- final_rh %>% select(-c(cohort, pre_post, updated_cohort, comment, time))

final <- rbind(final_improve, final_rh)
final$vis_num <- ifelse(final$updated_pre_post == "pre", 1, 2)
```

```{r, include=FALSE}
seqs <- unique(data$Metabolite)

# Teen LABS is not correct template
# want a mixed model with group by time interaction

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"OC_LC")
writeData(wb,"OC_LC",results_OC_LC,rowNames = T)

addWorksheet(wb,"LC_T1D")
writeData(wb,"LC_T1D",results_LC_T1D,rowNames = T)

addWorksheet(wb,"LC_T2D")
writeData(wb,"LC_T2D",results_LC_T2D,rowNames = T)

addWorksheet(wb,"OC_T1D")
writeData(wb,"OC_T1D",results_OC_T1D,rowNames = T)

addWorksheet(wb,"OC_T2D")
writeData(wb,"OC_T2D",results_OC_T2D,rowNames = T)

addWorksheet(wb,"T1D_T2D")
writeData(wb,"T1D_T2D",results_T1D_T2D,rowNames = T)

saveWorkbook(wb,"/Users/pylell/Documents/Downtime/RPC2/RPC2_AZ_urine_metabolomics.xlsx",overwrite = TRUE)

# now look for overlap of metabolites among groups
results_LC_T1D_sig <- results_LC_T1D[results_LC_T1D$adj.P.Val < 0.05,]
results_LC_T1D_sig <- results_LC_T1D_sig %>% filter(!is.na(logFC))
results_LC_T1D_sig$Metabolites <- row.names(results_LC_T1D_sig)
results_LC_T1D_sig <- results_LC_T1D_sig %>% rename(logFC_LC_T1D = logFC, P.Value_LC_T1D = P.Value,
                                                    adj.P.Val_LC_T1D = adj.P.Val)
results_LC_T1D_sig <- results_LC_T1D_sig %>% select(Metabolites, logFC_LC_T1D, P.Value_LC_T1D, adj.P.Val_LC_T1D)

results_LC_T2D_sig <- results_LC_T2D[results_LC_T2D$adj.P.Val < 0.05,]
results_LC_T2D_sig <- results_LC_T2D_sig %>% filter(!is.na(logFC))
results_LC_T2D_sig$Metabolites <- row.names(results_LC_T2D_sig)
results_LC_T2D_sig <- results_LC_T2D_sig %>% rename(logFC_LC_T2D = logFC, P.Value_LC_T2D = P.Value,
                                                    adj.P.Val_LC_T2D = adj.P.Val )
results_LC_T2D_sig <- results_LC_T2D_sig %>% select(Metabolites, logFC_LC_T2D, P.Value_LC_T2D, adj.P.Val_LC_T2D)


results_T1D_T2D_sig <- results_T1D_T2D[results_T1D_T2D$adj.P.Val < 0.05,]
results_T1D_T2D_sig <- results_T1D_T2D_sig %>% filter(!is.na(logFC))
results_T1D_T2D_sig$Metabolites <- row.names(results_T1D_T2D_sig)
results_T1D_T2D_sig <- results_T1D_T2D_sig %>% rename(logFC_T1D_T2D = logFC, P.Value_T1D_T2D = P.Value,
                                                     adj.P.Val_T1D_T2D = adj.P.Val )
results_T1D_T2D_sig <- results_T1D_T2D_sig %>% select(Metabolites, logFC_T1D_T2D, P.Value_T1D_T2D, adj.P.Val_T1D_T2D)

results_sig <- full_join(results_LC_T1D_sig, results_LC_T2D_sig, by = "Metabolites")
results_sig <- full_join(results_sig, results_T1D_T2D_sig, by = "Metabolites")

results_sig$count <- results_sig %>% group_by(Metabolites) %>% 
   summarise(count = sum(!is.na(logFC_LC_T1D), !is.na(logFC_LC_T2D), !is.na(logFC_T1D_T2D)))
results_sig_overlap <- results_sig %>% filter(count$count >= 2)
write.csv(results_sig_overlap,"/Users/pylell/Documents/Downtime/RPC2/RPC2_AZ_urine_metabolomics_overlap.csv")

```

```{r, include=FALSE}
# write a function to make each panel of the plot
panel_in_boxplot <- function(data, seq) {
  p <- ggplot(data,
       aes(x = Dose,
                     y = .data[[seq]],
                     fill = Dose))  +
  geom_boxplot(show.legend = FALSE) +  
  labs(x = NULL,
       y = NULL) +
       #,
       #fill = "Group") 
  theme(axis.title.x = element_text(size = 16),
        axis.title.y = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        panel.background = element_rect(fill = "#f2e9e4",
                                        color = "grey")) + 
  scale_fill_manual(values = c("#c2dfe3", "#fff9ec",
                                "#fcb1a6", "#fb6376")) +
  geom_jitter() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) 
  p <- p + scale_x_discrete(labels=c("LC", "OC", "T1D","T2D"))
  p <- p + theme(legend.position = "none")
}

# function call for above template
p_Betaine <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Betaine_P")
p_Betaine <- p_Betaine + labs(title = "Betaine (+)")

p_thymine <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._thymine_N")
p_thymine <- p_thymine + labs(title = "Thymine (-)")

p_glucose6 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Glucose_6_Phosphate_N")
p_glucose6 <- p_glucose6 + labs(title = "Glucose 6-phosphate (-)")

p_galactose <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Galactose_1_Phosphate_N")
p_galactose <- p_galactose + labs(title = "Galactose 1-phosphate (-)")

p_oxalic <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Oxalic_acid_N")
p_oxalic <- p_oxalic + labs(title = "Oxalic acid (-)")

p_hp <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Hydroxy_proline_N")
p_hp <- p_hp + labs(title = "Hydroxyproline (-)")

p_uracil <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._uracil_N")
p_uracil <- p_uracil + labs(title = "Uracil (-)")

p_mannose6 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Mannose_6_phosphate_N")
p_mannose6 <- p_mannose6 + labs(title = "Mannose 6-phosphate (-)")

p_f1 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Fructose__1_Phosphate_N")
p_f1 <- p_f1 + labs(title = "Fructose 1-phosphate (-)")

p_f6 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Fructose_6_Phosphate_N")
p_f6 <- p_f6 + labs(title = "Fructose 6-phosphate (-)")

p_a8 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._acyl_carnitine_8_0_P")
p_a8 <- p_a8 + labs(title = "Acylcarnitine 8:0 (+)")

p_dpa <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._dihydroxy_phenyl_acetic_acid_N")
p_dpa <- p_dpa + labs(title = "Dihydroxyphenylacetic acid (-)")

p_p5p <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Pyridoxal_5_Phosphate_N")
p_p5p <- p_p5p + labs(title = "Pyridoxal 5-phosphate (-)")

p_m <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._malate_N")
p_m <- p_m + labs(title = "Malate (-)")

p_sm <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._sorbitol_mannitol_N")
p_sm <- p_sm + labs(title = "Sorbitol mannitol (-)")

p_hpp <- panel_in_boxplot(data = data_wide, seq = "Peak.Area.Hydroxy_phenyl_propionic_acid_N")
p_hpp <- p_hpp + labs(title = "Hydroxyphenylpropionic acid (-)")

p_a <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Alanine_P")
p_a <- p_a + labs(title = "Alanine (+)")

p_sarc <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Sarcosine_P")
p_sarc <- p_sarc + labs(title = "Sarcosine (+)")

p_a10 <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._acyl_carnitine_10_0_P")
p_a10 <- p_a10 + labs(title = "Acylcarnitine (10:0)")

p_ps <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Phospho_serine_N")
p_ps <- p_ps + labs(title = "Phosphoserine (-)")

p_sdma <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._SDMA_P")
p_sdma <- p_sdma + labs(title = "SDMA (+)")

p_isoc <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._isocitrate_sp_N")
p_isoc <- p_isoc + labs(title = "Isocitrate (-)")

p_ky <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Kynurenine_P")
p_ky <- p_ky + labs(title = "Kynurenine (+)")

p_cys <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Cystine_N")
p_cys <- p_cys + labs(title = "Cystine (-)")

p_pcreat <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Pcreatine_N")
p_pcreat <- p_pcreat + labs(title = "Pcreatine (-)")

p_ha <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Hippuric_Acid_P")
p_ha <- p_ha + labs(title = "Hippuric acid (+)")

p_cyt <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._cytosine_N")
p_cyt <- p_cyt + labs(title = "Cytosine (-)")

p_hypo <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Hypoxanthine_P")
p_hypo <- p_hypo + labs(title = "Hypoxanthine (+)")

p_hpla <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Hydroxy_phenyl_lactic_acid_N")
p_hpla <- p_hpla + labs(title = "Hydroxyphenyllactic acid (-)")

p_py <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._pyruvic_acid_N")
p_py <- p_py + labs(title = "Pyruvic acid (-)")

p_q <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Quinolinic_acid_N")
p_q <- p_q + labs(title = "Quinolinic acid (-)")

p_lysine <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Lysine_P")
p_lysine <- p_lysine + labs(title = "Lysine (+)")

p_aa <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._2_Aminoadipic_acid_P")
p_aa <- p_aa + labs(title = "Aminoadipic acid (+)")

p_c <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Creatine_P")
p_c <- p_c + labs(title = "Creatine (+)")

p_pep <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Phospho_enol_pyruvic_acid_N")
p_pep <- p_pep + labs(title = "Phosphenolpyruvic acid (-)")

p_mx <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._7_Methylxanthine_P")
p_mx <- p_mx + labs(title = "Methylxanthine (+)")

p_mxn <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._methylxanthine_N")
p_mxn <- p_mxn + labs(title = "Methylxanthine (-)")

p_me <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Mesaconic_Acid_N")
p_me <- p_me + labs(title = "Mesaconic acid (-)")

p_glut <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._glutathione_ox_N")
p_glut <- p_glut + labs(title = "Glutathione ox (-)")

p_mer <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Mercapturic_acid_N")
p_mer <- p_mer + labs(title = "Mercapturic acid (-)")

p_ga <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._glutaric_acid_N")
p_ga <- p_ga + labs(title = "Glutaric acid (-)")

p_mna <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._1_MNA_P")
p_mna <- p_mna + labs(title = "MNA (+)")

p_gm <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Guanosine monophosphate_N")
p_gm <- p_gm + labs(title = "Guanosine monophosphate (-)")

p_cm <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._Cytidine_monophosphate_N")
p_cm <- p_cm + labs(title = "Cytidine monophosphate (-)")

p_mxp <- panel_in_boxplot(data = data_wide, seq = "Peak.Area._3_Methylxanthine_P")
p_mxp <- p_mxp + labs(title = "3-methylxanthine (+)")









# arrange
grpbox <- ggarrange(p_seq.3343.1,p_seq.8958.51,p_seq.24957.6,
                    p_seq.2948.58,p_seq.2999.6,p_seq.4498.62,p_seq.20161.41,
                    p_seq.5634.39,p_seq.7735.17,p_seq.13998.26,p_seq.7957.2,p_seq.24681.2,
                    p_seq.19563.3,p_seq.13408.23,p_seq.3235.50,
                    nrow = 3, ncol = 5,
                    common.legend = T)
png(height = 3000, width = 2500, file = "/Users/pylell/Dropbox/TODAY HTN and DKD output/local_T2D_HTN_boxplot.png", res = 170)
grpbox
dev.off()
```