---
title: "VSG and SMT cohort descriptive"
format: html
---

```{r}
library(aws.s3)
library(jsonlite)
library(dplyr)
library(Hmisc)
library(purrr)
```

```{r}
user <- Sys.info()[["user"]]

if (user == "choiyej") { # local version
  root_path <- "/Users/choiyej/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/keys.json")
} else if (user == "rameshsh") { # hyak version
  root_path <- ""
  git_path <- "/mmfs1/gscratch/togo/rameshsh/CHCO-Code/Petter Bjornstad"
} else if (user == "yejichoi") { # hyak version
  root_path <- "/mmfs1/gscratch/togo/yejichoi/"
  git_path <- "/mmfs1/gscratch/togo/yejichoi/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/yejichoi/keys.json")
} else if (user == "pylell") {
  root_path <- "/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/pylell/keys.json")
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r}
harm_dat <- read.csv(file.path(root_path, "Data Harmonization/Data Clean/harmonized_dataset.csv"), na.strings = "")

# SMT with biopsy cohort
smt_dat <- harm_dat %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit))  %>%
  filter(study %in% c("RENAL-HEIR", "RENAL-HEIRitage")) %>%
  filter(is.na(improve_id)) %>%
  # filter(!is.na(rh_id) & !is.na(rh2_id)) %>%
  filter(!is.na(kit_id)) %>%
  filter(study == "RENAL-HEIR")

summary(arsenal::tableby(~age + sex + glp1_agonist_timepoint, data = smt_dat))

# VSG with biopsy cohort
vsg_dat <- harm_dat %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit))  %>%
  filter(study %in% c("IMPROVE")) %>%
  filter(!is.na(kit_id)) %>%
  mutate(bx_yn = case_when(record_id == "IT_14" & 
                             visit == "baseline" ~ F,
                           record_id == "IT_20" & 
                             visit == "baseline" ~ F,
                           T ~ T)) %>%
  filter(bx_yn)

summary(arsenal::tableby(~age + sex + glp1_agonist_timepoint, data = subset(vsg_dat, visit == "baseline")))

```