---
title: "CALICO Aim 1 Analyses"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(tidyverse)
library(factoextra)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/tim/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/BDC/Janet Snell-Bergeon/CALICO",
  "Windows" = "C:/Users/Tim/OneDrive - The University of Colorado Denver/Vigers/BDC/Janet Snell-Bergeon/CALICO",
  "Linux" = "/home/tim/OneDrive/Vigers/BDC/Janet Snell-Bergeon/CALICO"
)
github_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/tim/Documents/GitHub",
  "Windows" = "C:/Users/Tim/Documents/GitHub",
  "Linux" = "/home/tim/Documents/GitHub"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data import}
#| include: false
# Set seed
set.seed(1017)
# Load data
load("./Data_Clean/analysis_data.RData")
# Limit to earliest visit
df <- df %>%
  group_by(record_number) %>%
  slice_min(cv_monthssincepcosdx) %>% 
  ungroup()
```

# Data cleaning

- Data were limited to each participant's earliest visit. 

# Total Testosterone and SHBG

```{r}
clust_df = df %>% select(cv_tt,cv_shbg) %>% drop_na()
fviz_nbclust(clust_df,FUNcluster = kmeans)
k_res = kmeans(clust_df)
fviz_cluster(k_res)
```

# Questions

- What is our outcome for the clustering? What are the reproductive and metabolic phenotypes?

