---
title: "CALICO Liver Analysis"
author: "Tim Vigers"
date: "today"
date-format: long
format:
  html:
    toc: true
    toc-depth: 5
    toc-float: true
    code-fold: true
    self-contained: true
    fig-cap-location: top
    fig-width: 12
    fig-height: 9
    page-layout: full
editor: source
---

```{r setup}
#| include: false
library(Hmisc)
library(tidyverse)
library(arsenal)
library(gtsummary)
library(sjPlot)
home_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/tim/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Vigers/BDC/Janet Snell-Bergeon/CALICO",
  "Windows" = "C:/Users/Tim/OneDrive - The University of Colorado Denver/Vigers/BDC/Janet Snell-Bergeon/CALICO",
  "Linux" = "/home/tim/OneDrive/Vigers/BDC/Janet Snell-Bergeon/CALICO"
)
github_dir <- switch(Sys.info()["sysname"],
  "Darwin" = "/Users/tim/Documents/GitHub",
  "Windows" = "C:/Users/Tim/Documents/GitHub",
  "Linux" = "/home/tim/Documents/GitHub"
)
knitr::opts_knit$set(root.dir = home_dir)
```

```{r data import}
#| include: false
# Load data
load("./Data_Clean/analysis_data.RData")
# LF:FSH ratio
df$cv_lh_fsh <- df$cv_lh / df$cv_fsh
label(df$cv_lh_fsh) <- "LH:FSH"
# Combine lean and overweight
df$weight_cat <- factor(df$weight_cat,
  levels = c("Normal weight", "Overweight", "Obese"),
  labels = c("Non-Obese", "Non-Obese", "Obese")
)
label(df$weight_cat) <- "Weight Category (by percentile then raw value)"
# Combine race categories
df$combined_race <- factor(df$combined_race,
  levels = c(
    "Caucasian", "African American", "American Indian or Alaska Native", "Asian",
    "More than one", "Other", "Pacific Islander"
  ),
  labels = c(
    "Caucasian", "African American", "Other/More than one", "Other/More than one",
    "Other/More than one", "Other/More than one", "Other/More than one"
  )
)
label(df$combined_race) <- "Race"
# Combine other variable levels
df$cv_acneface <- factor(df$cv_acneface,
  levels = c(
    "Mild", "Moderate (pustular)", "Severe (nodular, cystic, scarring)", "None",
    "Acne noted by clinician, severity unknown."
  ),
  labels = c(
    "None/Mild/Unknown", "Moderate/Severe", "Moderate/Severe",
    "None/Mild/Unknown", "None/Mild/Unknown"
  )
)
label(df$cv_acneface) <- "Acne severity on the face"
df$cv_acanthosisneck <- factor(df$cv_acanthosisneck,
  levels = c(
    "Back of neck, barely visible (minimal)", "Back of neck, obvious (mild)",
    "Lateral sides of neck (moderate)", "Circumferential (severe)", "None"
  ),
  labels = c("Present", "Present", "Present", "Present", "Absent")
)
label(df$cv_acanthosisneck) <- "Acanthosis at the neck"
df$cv_osa_sx <- factor(df$cv_osa_sx,
  levels = c(
    "Yes, not addressed", "Yes, prescribed CPAP but not using it",
    "Yes, referral placed for sleep study", "No, treated with CPAP",
    "No, not currently treated"
  ),
  labels = c("Present", "Present", "Present", "Absent", "Absent")
)
label(df$cv_osa_sx) <- "Symptoms of sleep apnea (snoring, frequent awakening, AM headaches, daytime fatigue, napping during day)"
# Variable lists
demo_vars <- c(
  "pcosdx_age", "combined_race", "ethnicity", "insur_type"
)
liver_vars <- c(
  "pcosdx_menarche", "cv_alt", "cv_tg", "cv_hdl", "cv_shbg",
  "cv_a1c", "cv_fbg", "cv_2hrglucoseogtt", "cv_fastinsulin", "cv_tt_perc",
  "cv_ft_perc", "cv_dheas_perc", "cv_androstendione_perc", "cv_lh", "cv_fsh",
  "cv_lh_fsh", "cv_amh_perc", "cv_sbp", "cv_dbp", "pcosdx_famhx_parent___7",
  "pcosdx_famhx___7", "cv_hirsutism_num", "cv_waist", "cv_acneface",
  "cv_acanthosisneck", "cv_osa_sx"
)
# Basic formula for tables
f <- as.formula(paste("~", paste(c(demo_vars, liver_vars), collapse = "+")))
# Set table options
mycontrols <-
  tableby.control(
    numeric.stats = c("N", "Nmiss", "meansd", "medianq1q3", "range"),
    cat.stats = c("N", "Nmiss", "countpct")
  )
# First visit only, exclude those on hormones at Dx
cv1 <- df %>%
  group_by(record_number) %>%
  filter(
    cv_monthssincepcosdx == 0, cv_medications___5 == "Unchecked",
    cv_medications___6 == "Unchecked", cv_medications___7 == "Unchecked",
    cv_medications___9 == "Unchecked", cv_medications___10 == "Unchecked",
    cv_medications___11 == "Unchecked", cv_medications___12 == "Unchecked"
  ) %>%
  ungroup()
```

# Baseline tables

## Comparisons by weight category

```{r results='asis'}
t1 <- tableby(update(f, weight_cat ~ .), data = cv1, control = mycontrols)
summary(t1, labelTranslations = labels(df), pfootnote = T)
```

## Comparisons by race

```{r results='asis'}
t2 <- tableby(update(f, combined_race ~ weight_cat + . - combined_race),
  data = cv1, control = mycontrols
)
summary(t2, labelTranslations = labels(df), pfootnote = T)
```

# Baseline models

In the models below, the interaction term indicates whether or not the effect of ALT on the outcome varies by weight category. 

## HbA1c

```{r}
m <- lm(cv_alt ~ cv_a1c * weight_cat, data = cv1)
m %>%
  tbl_regression() %>%
  add_n(location = "level")
plot_model(m, type = "pred", terms = c("cv_a1c", "weight_cat"))
```

## Fasting glucose

```{r}
m <- lm(cv_alt ~ cv_fbg * weight_cat, data = cv1)
m %>%
  tbl_regression() %>%
  add_n(location = "level")
plot_model(m, type = "pred", terms = c("cv_fbg", "weight_cat"))
```

## 2 hour glucose

```{r}
m <- lm(cv_alt ~ cv_2hrglucoseogtt * weight_cat, data = cv1)
m %>%
  tbl_regression() %>%
  add_n(location = "level")
plot_model(m, type = "pred", terms = c("cv_2hrglucoseogtt", "weight_cat"))
```
