#Libraries
library(reprex)
library(tidyverse)
library(BiocManager)        
library(arsenal)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(Seurat)
library(future)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggpubr)
library(venn)
library(rstatix)
library(table1)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(fgsea)
library(ReactomeGSA)
library(msigdbr)
library(kableExtra)
library(knitr)
library(SingleCellExperiment)
library(fgsea)
library(EnhancedVolcano)
library(openxlsx)
library(BiocManager)
# library(MAST)
library(ggrepel)
# library(qpcR)
library(ggpubr)
library(ggplot2)
library(GGally)
# library(limma)
# library(reshape2)
# library(data.table)
# library(knitr)
# library(TxDb.Hsapiens.UCSC.hg19.knownGene)
# library(stringr)
# library(NMF)
# library(rsvd)
# library(RColorBrewer)
library(devtools)
# install_github("Sun-lab/ideas",force=T)
# library(ideas)
library(foreach)
library(doRNG)
library(doParallel)
library(fs)
library(future)
# registerDoParallel(cores = 6)
# library(VennDiagram)
#install.packages("survival")
library(survival)
#install.packages("lme4")  # If not already installed
library(lme4)
#install.packages("lmerTest")
library(lmerTest)
# install.packages("emmeans")
library(emmeans)
# install.packages("glmmTMB")
library(glmmTMB)
library(ggrepel)
# library(qpcR)
library(ggpubr)
#install.packages("devtools")
library(devtools)
# BiocManager::install("enrichplot")
# library(enrichplot)
library(enrichR)
dbs <- c("GO_Biological_Process_2023", 
         "KEGG_2021_Human",
         # "Reactome_2022", 
         "Reactome_Pathways_2024",
         # "MSigDB_Oncogenic_Signatures",
         # "MSigDB_Computational",
         "MSigDB_Hallmark_2020")
library(pheatmap)
library(janitor)
library(BiocParallel)
library(scran)
library(hexbin)
library(Seurat)
library(future)
library(tidyverse)
library(colorspace)
library(patchwork)
library(ggdendro)
library(cowplot)
library(ggpubr)
library(rstatix)
library(table1)
library(Biobase)
library(ReactomeGSA)
library(GSEABase)
library(msigdbr)
library(kableExtra)
library(knitr)
library(slingshot)
library(SingleCellExperiment)
library(RColorBrewer)
library(scales)
library(viridis)
library(UpSetR)
library(pheatmap)
library(fgsea)
# library(tradeSeq)
library(DescTools)
# library(Totem)
library(dyndimred)
library(pushoverr)
# set_pushover_user(user = "uv4fkwcjfp88sprou64rboojje4xvm")
# set_pushover_app(token = "avi88qsjeunh4xmvz3mbgp2fzpmkey")
library(DelayedMatrixStats)
# remotes::install_github("dynverse/dynfeature")
# remotes::install_github("dynverse/dynplot")
# remotes::install_github("elolab/Totem")
library(dynfeature)
library(dynplot)
# library(Totem)
library(BiocParallel)
# library(slingshot)
# library(SingleCellExperiment)
# library(ggplot2)
# library(dplyr)
# Install BiocManager if you haven't already
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# Install the Bioconductor dependencies
# BiocManager::install(c("Biobase", "BiocNeighbors", "BiocGenerics", "ComplexHeatmap"))
# devtools::install_github("sqjin/CellChat")
library(CellChat)
# BiocManager::install("speckle")
library(speckle)
# install.packages("doFuture")
# library(doFuture)
# remove.packages("nebula")
# install_github("lhe17/nebula",force=T)
library(nebula)
