---
title: "TODAY metabolomics analysis - synthesis and report"
author: "Kristen Miller"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  word_document:
    toc: true
    toc_depth: '3'
  html_document:
    number_sections: true
    theme: readable
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
library(knitr)
library(readxl)
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

user <- Sys.info()[["user"]]
if (user == "choiyej") { # local version
  root_path <- "/Users/choiyej/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive/TODAY subaward"
  git_path <- "/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad"
} else if (user == "pylell") {
  root_path <- "/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive/TODAY subaward"
  git_path <- "/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad"
} else if (user == "kristenmiller") {
  root_path <- "/Users/kristenmiller/Library/CloudStorage/OneDrive-UW/Laura Pyle's files - Biostatistics Core Shared Drive/TODAY subaward"
  git_path <- "/Users/kristenmiller/Documents/GitHub/CHCO-Code/Petter Bjornstad"
} else {
  stop("Unknown user: please specify root path for this user.")
}

knitr::opts_knit$set(root.dir = root_path)
```

```{r, include=FALSE}

read_ex(wb,"./Results/Metabolomics Linear and Cox models/TODAY plasma metabolomics Cox models scaled baseline adjusted_march2026.xlsx",overwrite = TRUE)


```

# Results

Need to remember that the interpretation of the hazard ratios is as follows: for a one SD increase in the log of seqXXX, the risk is multiplied by....

```{r echo=FALSE, include=TRUE}

```
