---
title: "TODAY urine metabolomics baseline analyses - adjusted Cox models"
author: "Laura Pyle"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)
library(survival)
library(broom)
library(stringr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
# if(Sys.info()["sysname"] == "Windows"){
#   home_dir = "E:/Petter Bjornstad/TODAY subaward"
# } else if (Sys.info()["sysname"] == "Linux"){
#   home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
# } else if (Sys.info()["sysname"] == "Darwin"){
#   home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
# }
#3/13/2026: KM updated to point to OneDrive: (should work for any user if using mac? confirm this is how OneDrive is mapped to Laura's computer too)
home_dir = paste0("/Users/",Sys.info()["user"],"/Library/CloudStorage/OneDrive-UW/Laura Pyle's files - Biostatistics Core Shared Drive/TODAY subaward")
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
load("./Metabolomic data/urine.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load baseline risk factors
load("./Clinical data/TODAY/baserisk.Rdata")

# load CKM outcomes
dat.ckm<-read.csv("./CKM/Results/CKM stage summary.csv")

# take only the baseline samples
urine$Date.Drawn <- as.Date(urine$Date.Drawn,format = "%m/%d/%Y")
base <- urine %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
base <- base %>% arrange(Date.Drawn)

# create kyurenine/tryptophan ratio
base <- base %>% mutate(`kyu.tryp.ratio.in.nM/mM` = `Kynurenine.in.nM/mM.Creatinine`/`Tryptophan.in.nM/mM.Creatinine`)

# merge in complication data
base <- merge(base, comorb, by="releaseid",all.x=T, all.y=F)

# merge in baseline risk factors
base <- merge(base, baserisk, by="releaseid",all.x=T, all.y=F)

# merge in CKM outcomes
dat.ckm$releaseid<-dat.ckm$RELEASEID
base <- merge(base, dat.ckm[,c("releaseid",
                               "CKM_syn_base","CKM_max",
                               "progress_CKM","days_to_first_ckm_prog",
                               "progress_CKM_stage3","days_to_first_ckm_stage3_prog",
                               "progress_CKM_stage4","days_to_first_ckm_stage4_prog")], by="releaseid",all.x=T, all.y=F)

# identify columns corresponding to proteins
#is_seq <- function(.x) grepl("^seq\\.[0-9]{4}", .x) # regex for analytes
is_seq <- function(.x) grepl("nM/mM", .x)
seq <- is_seq(names(base))

# convert to numeric
base[,seq] <- apply(base[,seq],2,as.numeric)

# are there proteins with low variability?
metabolites<-base[,seq]
no_var = caret::nearZeroVar(metabolites)
if (length(no_var)>0){
  no_var_names<-names(metabolites[,no_var])
  base <- base[,-which(colnames(base)%in%no_var_names)]  
}
seq <- is_seq(names(base))

# log transform
base_log <- base %>% modify_if(is_seq(names(.)), log)

# scale by SD
base_log_scale <- base_log
predictors <- colnames(base_log[seq])
for (i in 1:length(predictors)) {
  base_log_scale[predictors[i]] <- base_log_scale[predictors[i]]/sd(base_log[,paste0(predictors[i])])
}

# now we need to change the format of the variable names
temp <- str_replace_all(colnames(base_log_scale[,seq]),"/","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"-","_")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"3","Three")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"2","Two")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"\\(s\\)","s")
colnames(base_log_scale)[seq] <- temp
temp <- str_replace_all(colnames(base_log_scale[,seq]),"5","Five")
colnames(base_log_scale)[seq] <- temp
```

```{r, include=FALSE}
# Macroalbuminuria
result_MAC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOMAC, MAC)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_MAC <- rbind(result_MAC,tidymod)
}
result_MAC$adj.p.value <- p.adjust(result_MAC$p.value, "fdr")
result_MAC <- result_MAC[order(result_MAC$p.value),] 

# Microalbuminuria
result_MIC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOMIC, MIC)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_MIC <- rbind(result_MIC,tidymod)
}
result_MIC$adj.p.value <- p.adjust(result_MIC$p.value, "fdr")
result_MIC <- result_MIC[order(result_MIC$p.value),] 

# hyperfiltration
result_HYP <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOHYP, HYP)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_HYP <- rbind(result_HYP,tidymod)
}
result_HYP$adj.p.value <- p.adjust(result_HYP$p.value, "fdr")
result_HYP <- result_HYP[order(result_HYP$p.value),] 

# rapid eGFR decline
result_RAPID <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTORAPID, RAPID)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_RAPID <- rbind(result_RAPID,tidymod)
}
result_RAPID$adj.p.value <- p.adjust(result_RAPID$p.value, "fdr")
result_RAPID <- result_RAPID[order(result_RAPID$p.value),] 

# hypertension with SBP
results_htn_bp <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOHTN, HTN)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  results_htn_bp <- rbind(results_htn_bp,tidymod)
}
results_htn_bp$adj.p.value <- p.adjust(results_htn_bp$p.value, "fdr")
results_htn_bp <- results_htn_bp[order(results_htn_bp$p.value),] 

# hypertension
# omit SBP
result_HTN <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOHTN, HTN)~",predictors[i],"+HbA1c+log_trig+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_HTN <- rbind(result_HTN,tidymod)
}
result_HTN$adj.p.value <- p.adjust(result_HTN$p.value, "fdr")
result_HTN <- result_HTN[order(result_HTN$p.value),] 

# neuropathy
result_NEURO <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTONEURO, NEURO)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_NEURO <- rbind(result_NEURO,tidymod)
}
result_NEURO$adj.p.value <- p.adjust(result_NEURO$p.value, "fdr")
result_NEURO <- result_NEURO[order(result_NEURO$p.value),] 

# retinopathy
result_RETINO <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTORETINO, RETINO)~",predictors[i],"+HbA1c+log_trig+sbp+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_RETINO <- rbind(result_RETINO,tidymod)
}
result_RETINO$adj.p.value <- p.adjust(result_RETINO$p.value, "fdr")
result_RETINO <- result_RETINO[order(result_RETINO$p.value),] 

# glycemic failure
result_GLYC <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOGLYC, GLYC)~",predictors[i],"+bmi+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  result_GLYC <- rbind(result_GLYC,tidymod)
}
result_GLYC$adj.p.value <- p.adjust(result_GLYC$p.value, "fdr")
result_GLYC <- result_GLYC[order(result_GLYC$p.value),] 

# glycemic failure with A1c
results_glyc_a1c <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(DAYSTOGLYC, GLYC)~",predictors[i],"+HbA1c+bmi+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  results_glyc_a1c <- rbind(results_glyc_a1c,tidymod)
}
results_glyc_a1c$adj.p.value <- p.adjust(results_glyc_a1c$p.value, "fdr")
results_glyc_a1c <- results_glyc_a1c[order(results_glyc_a1c$p.value),] 

# CKM progression
results_ckm_prog <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(days_to_first_ckm_prog, progress_CKM)~",predictors[i],"+HbA1c+bmi+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  results_ckm_prog <- rbind(results_ckm_prog,tidymod)
}
results_ckm_prog$adj.p.value <- p.adjust(results_ckm_prog$p.value, "fdr")
results_ckm_prog <- results_ckm_prog[order(results_ckm_prog$p.value),] 

# CKM progression stage 3
results_ckm_prog3 <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(days_to_first_ckm_stage3_prog, progress_CKM_stage3)~",predictors[i],"+HbA1c+bmi+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  results_ckm_prog3 <- rbind(results_ckm_prog3,tidymod)
}
results_ckm_prog3$adj.p.value <- p.adjust(results_ckm_prog3$p.value, "fdr")
results_ckm_prog3 <- results_ckm_prog3[order(results_ckm_prog3$p.value),] 

# CKM progression stage 4
results_ckm_prog4 <- NULL
predictors <- colnames(base_log_scale[seq])
for (i in 1:length(predictors)) {
  form <- paste0("Surv(days_to_first_ckm_stage4_prog, progress_CKM_stage4)~",predictors[i],"+HbA1c+bmi+si_1_ins0")
  mod <- coxph(data = base_log_scale, formula = as.formula(form))
  tidymod <- tidy(mod, exponentiate=TRUE, conf.int = TRUE)
  tidymod <- tidymod[1,]
  results_ckm_prog4 <- rbind(results_ckm_prog4,tidymod)
}
results_ckm_prog4$adj.p.value <- p.adjust(results_ckm_prog4$p.value, "fdr")
results_ckm_prog4 <- results_ckm_prog4[order(results_ckm_prog4$p.value),] 

# write all results to file
wb <- createWorkbook()
addWorksheet(wb,"MAC CPH")
writeData(wb,"MAC CPH",result_MAC,rowNames = F)
addWorksheet(wb,"MIC CPH")
writeData(wb,"MIC CPH",result_MIC,rowNames = F)
addWorksheet(wb,"HYP CPH")
writeData(wb,"HYP CPH",result_HYP,rowNames = F)
addWorksheet(wb,"RAPID CPH")
writeData(wb,"RAPID CPH",result_RAPID,rowNames = F)
addWorksheet(wb,"HTN with SBP CPH")
writeData(wb,"HTN with SBP CPH",results_htn_bp,rowNames = F)
addWorksheet(wb,"HTN CPH")
writeData(wb,"HTN CPH",result_HTN,rowNames = F)
addWorksheet(wb,"NEURO CPH")
writeData(wb,"NEURO CPH",result_NEURO,rowNames = F)
addWorksheet(wb,"RETINO CPH")
writeData(wb,"RETINO CPH",result_RETINO,rowNames = F)
addWorksheet(wb,"GLYC CPH")
writeData(wb,"GLYC CPH",result_GLYC,rowNames = F)
addWorksheet(wb,"GLYC with A1c CPH")
writeData(wb,"GLYC with A1c CPH",results_glyc_a1c,rowNames = F)
addWorksheet(wb,"CKM progression")
writeData(wb,"CKM progression",results_ckm_prog,rowNames = F)
addWorksheet(wb,"CKM progression stage 3")
writeData(wb,"CKM progression stage 3",results_ckm_prog3,rowNames = F)
addWorksheet(wb,"CKM progression stage 4")
writeData(wb,"CKM progression stage 4",results_ckm_prog4,rowNames = F)
saveWorkbook(wb,"./Results/Metabolomics Linear and Cox models/TODAY urine metabolomics Cox models scaled baseline adjusted_march2026.xlsx",overwrite = TRUE)


```

# Results

Need to remember that the interpretation of the hazard ratios is as follows: for a one SD increase in the log of seqXXX, the risk is multiplied by....

```{r echo=FALSE, include=TRUE}

```
