---
title: "TODAY plasma metabolomics 10 year cross-sectional analyses - adjusted models"
author: "Laura Pyle and Tim Vigers"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
library(limma)
library(dplyr)
library(caret)
library(purrr)
library(multtest)
library(openxlsx)
library(tableone)
library(EnhancedVolcano)
library(knitr)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE)

# knitr::opts_chunk$set(echo = FALSE)
# if(Sys.info()["sysname"] == "Windows"){
#   home_dir = "E:/Petter Bjornstad/TODAY subaward"
# } else if (Sys.info()["sysname"] == "Linux"){
#   home_dir = "~/UCD/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
# } else if (Sys.info()["sysname"] == "Darwin"){
#   home_dir = "/Volumes/som/PEDS/RI Biostatistics Core/Shared/Shared Projects/Laura/Peds Endo/Petter Bjornstad/TODAY subaward/"
# }
home_dir = paste0("/Users/",Sys.info()["user"],"/Library/CloudStorage/OneDrive-UW/Laura Pyle's files - Biostatistics Core Shared Drive/TODAY subaward")
knitr::opts_knit$set(root.dir = home_dir)
```

```{r, include=FALSE}
load("./Metabolomic data/plasma_all.Rdata")

# load comorbidity data
load("./Clinical data/comorb.Rdata")

# load year 10 covariates
load("./Clinical data/TODAY/yr10risk.Rdata")

# load CKM outcomes
dat.ckm<-read.csv("./CKM/Results/CKM stage summary.csv")

# take only the baseline samples
plasma<-plasma_all
plasma$Date.Drawn <- as.Date(plasma$Date.Drawn,format = "%m/%d/%Y")
base <- plasma %>% arrange(releaseid,Date.Drawn) %>% group_by(releaseid) %>% filter(row_number()==1)
base <- base %>% arrange(Date.Drawn)

# find follow-up samples
fup <- plasma %>% anti_join(base, soma, by=c("releaseid","Date.Drawn"))

# merge in nephropathy data
fup <- merge(fup, comorb, by="releaseid",all.x=T, all.y=F)

# merge in year 10 covariates
fup <- merge(fup, yr10risk, by="releaseid",all.x=T, all.y=F)

# merge in CKM outcomes
dat.ckm$releaseid<-dat.ckm$RELEASEID
fup <- merge(fup, dat.ckm[,c("releaseid","sex",
                               "CKM_syn_base","CKM_max",
                               "progress_CKM","days_to_first_ckm_prog",
                               "progress_CKM_stage3","days_to_first_ckm_stage3_prog",
                               "progress_CKM_stage4","days_to_first_ckm_stage4_prog")], by="releaseid",all.x=T, all.y=F)

# only keep observations with nonmissing values of covariates
# otherwise size of contrast matrix will be incorrect
fup <- fup %>% filter(!is.na(hba1c) & !is.na(log_trig) & !is.na(sbp) & !is.na(si_1_ins0))
fup_a1c <- fup %>% filter(!is.na(bmi))

# identify columns corresponding to proteins and convert to numeric
is_seq <- function(.x) grepl("uM", .x)
seq <- is_seq(names(fup))
fup[,seq] <- apply(fup[,seq],2,as.numeric)

# log transform
fup_log <- fup %>% modify_if(is_seq(names(.)), log)
fup_log_a1c <- fup_a1c %>% modify_if(is_seq(names(.)), log)
```

```{r, include=FALSE}
# MAC alone
MAC_contrast <- model.matrix(~MAC+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
ymat <- t(fup_log[,seq])
fit <- lmFit(ymat,MAC_contrast)
fit <- eBayes(fit)
results_MAC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MAC <- results_MAC[order(results_MAC$P.Value),] 

# MIC alone
MIC_contrast <- model.matrix(~MIC+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
ymat <- t(fup_log[,seq])
fit <- lmFit(ymat,MIC_contrast)
fit <- eBayes(fit)
results_MIC <- topTable(fit,coef = 2,number = nrow(ymat))
results_MIC <- results_MIC[order(results_MIC$P.Value),] 

# hyperfiltration
hyperfilt_contrast <- model.matrix(~HYP+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$HYP))
ymat <- t(y[,seq])
fit <- lmFit(ymat,hyperfilt_contrast)
fit <- eBayes(fit)
results_hyperfilt <- topTable(fit,coef = 2,number = nrow(ymat))
results_hyperfilt <- results_hyperfilt[order(results_hyperfilt$P.Value),] 
ymat <- NULL
fit <- NULL

# rapid eGFR decline
rapid_contrast <- model.matrix(~RAPID+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$RAPID))
ymat <- t(y[,seq])
fit <- lmFit(ymat,rapid_contrast)
fit <- eBayes(fit)
results_rapid <- topTable(fit,coef = 2,number = nrow(ymat))
results_rapid <- results_rapid[order(results_rapid$P.Value),] 
ymat <- NULL
fit <- NULL

# hypertension with SBP
htn_bp_contrast <- model.matrix(~HTN+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$HTN))
ymat <- t(y[,seq])
fit <- lmFit(ymat,htn_bp_contrast)
fit <- eBayes(fit)
results_htn_bp <- topTable(fit,coef = 2,number = nrow(ymat))
results_htn_bp <- results_htn_bp[order(results_htn_bp$P.Value),] 
ymat <- NULL
fit <- NULL

# hypertension
htn_contrast <- model.matrix(~HTN+hba1c+log_trig+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$HTN))
ymat <- t(y[,seq])
fit <- lmFit(ymat,htn_contrast)
fit <- eBayes(fit)
results_htn <- topTable(fit,coef = 2,number = nrow(ymat))
results_htn <- results_htn[order(results_htn$P.Value),] 
ymat <- NULL
fit <- NULL

# neuropathy
neuro_contrast <- model.matrix(~NEURO+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$NEURO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,neuro_contrast)
fit <- eBayes(fit)
results_neuro <- topTable(fit,coef = 2,number = nrow(ymat))
results_neuro <- results_neuro[order(results_neuro$P.Value),] 
ymat <- NULL
fit <- NULL

# retinopathy
retino_contrast <- model.matrix(~RETINO+hba1c+log_trig+sbp+si_1_ins0+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$RETINO))
ymat <- t(y[,seq])
fit <- lmFit(ymat,retino_contrast)
fit <- eBayes(fit)
results_retino <- topTable(fit,coef = 2,number = nrow(ymat))
results_retino <- results_retino[order(results_retino$P.Value),] 
ymat <- NULL
fit <- NULL

# glycemic failure
# omit A1c
glyc_contrast <- model.matrix(~GLYC+log_trig+sbp+si_1_ins0+sex,fup_a1c)
# moderated t-tests with and without FDR adjustment
y <- fup_log_a1c %>% filter(!is.na(fup_log_a1c$GLYC))
ymat <- t(y[,seq])
fit <- lmFit(ymat,glyc_contrast)
fit <- eBayes(fit)
results_glyc <- topTable(fit,coef = 2,number = nrow(ymat))
results_glyc <- results_glyc[order(results_glyc$P.Value),] 
ymat <- NULL
fit <- NULL

# glycemic failure
# with A1c
glyc_a1c_contrast <- model.matrix(~GLYC+hba1c+log_trig+sbp+si_1_ins0+sex,fup_a1c)
# moderated t-tests with and without FDR adjustment
y <- fup_log_a1c %>% filter(!is.na(fup_log_a1c$GLYC))
ymat <- t(y[,seq])
fit <- lmFit(ymat,glyc_a1c_contrast)
fit <- eBayes(fit)
results_glyc_a1c <- topTable(fit,coef = 2,number = nrow(ymat))
results_glyc_a1c <- results_glyc_a1c[order(results_glyc_a1c$P.Value),] 
ymat <- NULL
fit <- NULL

# CKM progression
ckm_contrast <- model.matrix(~progress_CKM+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$progress_CKM))
ymat <- t(y[,seq])
fit <- lmFit(ymat,ckm_contrast)
fit <- eBayes(fit)
results_ckm <- topTable(fit,coef = 2,number = nrow(ymat))
results_ckm <- results_ckm[order(results_ckm$P.Value),] 
ymat <- NULL
fit <- NULL

# CKM progression stage 3
ckm3_contrast <- model.matrix(~progress_CKM_stage3+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$progress_CKM_stage3))
ymat <- t(y[,seq])
fit <- lmFit(ymat,ckm3_contrast)
fit <- eBayes(fit)
results_ckm3 <- topTable(fit,coef = 2,number = nrow(ymat))
results_ckm3 <- results_ckm3[order(results_ckm3$P.Value),] 
ymat <- NULL
fit <- NULL

# CKM progression stage 4
ckm4_contrast <- model.matrix(~progress_CKM_stage4+sex,fup)
# moderated t-tests with and without FDR adjustment
y <- fup_log %>% filter(!is.na(fup_log$progress_CKM_stage3))
ymat <- t(y[,seq])
fit <- lmFit(ymat,ckm4_contrast)
fit <- eBayes(fit)
results_ckm4 <- topTable(fit,coef = 2,number = nrow(ymat))
results_ckm4 <- results_ckm4[order(results_ckm4$P.Value),] 
ymat <- NULL
fit <- NULL

# write all results to file
wb <- createWorkbook()

addWorksheet(wb,"MAC_moderated_FDR")
writeData(wb,"MAC_moderated_FDR",results_MAC,rowNames = T)

addWorksheet(wb,"MIC_moderated_FDR")
writeData(wb,"MIC_moderated_FDR",results_MIC,rowNames = T)

addWorksheet(wb,"hyperfilt_moderated_FDR")
writeData(wb,"hyperfilt_moderated_FDR",results_hyperfilt,rowNames = T)

addWorksheet(wb,"rapid_moderated_FDR")
writeData(wb,"rapid_moderated_FDR",results_rapid,rowNames = T)

addWorksheet(wb,"htn_with_SBP_moderated_FDR")
writeData(wb,"htn_with_SBP_moderated_FDR",results_htn_bp,rowNames = T)

addWorksheet(wb,"htn_moderated_FDR")
writeData(wb,"htn_moderated_FDR",results_htn,rowNames = T)

addWorksheet(wb,"neuro_moderated_FDR")
writeData(wb,"neuro_moderated_FDR",results_neuro,rowNames = T)

addWorksheet(wb,"retino_moderated_FDR")
writeData(wb,"retino_moderated_FDR",results_retino,rowNames = T)

addWorksheet(wb,"glyc_with_a1c_moderated_FDR")
writeData(wb,"glyc_with_a1c_moderated_FDR",results_glyc_a1c,rowNames = T)

addWorksheet(wb,"glyc_moderated_FDR")
writeData(wb,"glyc_moderated_FDR",results_glyc,rowNames = T)

addWorksheet(wb,"ckmprog_moderated_FDR")
writeData(wb,"ckmprog_moderated_FDR",results_ckm,rowNames = T)

addWorksheet(wb,"ckmprog3_moderated_FDR")
writeData(wb,"ckmprog3_moderated_FDR",results_ckm3,rowNames = T)

addWorksheet(wb,"ckmprog4_moderated_FDR")
writeData(wb,"ckmprog4_moderated_FDR",results_ckm4,rowNames = T)

saveWorkbook(wb,"./Results/Metabolomics Linear and Cox models/TODAY plasma metabolomics limma yr10 adjusted_march2026.xlsx",overwrite = TRUE)

```

# Results

## Descriptive statistics

```{r echo=FALSE, include=FALSE}
# add table of count of outcomes
t1data <- fup
t1data$MAC <- as.factor(t1data$MAC)
t1data$MIC <- as.factor(t1data$MIC)
t1data$HYP <- as.factor(t1data$HYP)
t1data$RAPID <- as.factor(t1data$RAPID)
t1data$NEURO <- as.factor(t1data$NEURO)
t1data$RETINO <- as.factor(t1data$RETINO)
t1data$GLYC <- as.factor(t1data$GLYC)
t1data$progress_CKM <- as.factor(t1data$progress_CKM)
t1data$progress_CKM_stage3 <- as.factor(t1data$progress_CKM_stage3)
t1data$progress_CKM_stage4 <- as.factor(t1data$progress_CKM_stage4)

t1 <- CreateTableOne(data=t1data, vars=c("MAC","MIC","HYP","RAPID","NEURO","RETINO","GLYC","progress_CKM","progress_CKM_stage3","progress_CKM_stage4"))
t1 <- print(t1)
```

```{r echo=FALSE, include=TRUE}
kable(t1)
```
