---
title: "CROCODILE descriptives for RPPR"
author: "Ye Ji Choi"
date: "`r lubridate::today()`"
format: 
  html:
    toc: true
    toc-depth: 5
    toc-location: left
    code-fold: true
    embed-resources: true
---

```{r libraries, echo=F, include = F}
library(SomaDataIO)
library(tidyverse)
library(growthcleanr)
library(arsenal)
library(dplyr)
```

```{r}
user <- Sys.info()[["user"]]

if (user == "choiyej") { # local version
  root_path <- "/Users/choiyej/Library/CloudStorage/OneDrive-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/choiyej/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/keys.json")
} else if (user == "rameshsh") { # hyak version
  root_path <- ""
  git_path <- "/mmfs1/gscratch/togo/rameshsh/CHCO-Code/Petter Bjornstad"
} else if (user == "yejichoi") { # hyak version
  root_path <- "/mmfs1/gscratch/togo/yejichoi/"
  git_path <- "/mmfs1/gscratch/togo/yejichoi/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/yejichoi/keys.json")
} else if (user == "pylell") {
  root_path <- "/Users/pylell/Library/CloudStorage/OneDrive-SharedLibraries-UW/Bjornstad/Biostatistics Core Shared Drive"
  git_path <- "/Users/pylell/Documents/GitHub/CHCO-Code/Petter Bjornstad"
  keys <- fromJSON("/mmfs1/home/pylell/keys.json")      
} else {
  stop("Unknown user: please specify root path for this user.")
}
```

```{r load-data, echo = F, include = F}
# Load SOMAScan analytes data
load(file.path(root_path, "Data Harmonization/Combined SomaScan/analytes.Rdata"))

# Load dictionary function and file
source("/Users/choiyej/GitHub/YC_CHCO/R Functions/label_harmonized_function.R")
```

```{r prep-data, echo = F, include = F}
# Load clinical data
load(file.path(root_path, "CROCODILE/Data_Cleaned/croc_data.RData")) # dat
```

```{r echo = F}
# Descriptive tables
summary(tableby(group ~ age + sex + group + weight + height + bmi + hba1c + gfr_raw_plasma + gfr_bsa_plasma + erpf_raw_plasma + erpf_bsa_plasma + total_kidney_volume_ml + ht_adj_tkv + mm_airg + mm_bcell + mm_di + mm_ir + mm_si, data = dat, total = T, test = F))

dat_sub <- dat %>%
  mutate(age = floor(age)) %>%
  dplyr::select(record_id, group, age, sex, race, ethnicity)

write.csv(dat_sub, file.path(root_path, "CROCODILE/Data_Cleaned/croc_enrollment.csv"), row.names = F)
```
