---
title: "RH/RH2 ASN Oral Presentation"
author: "Ye Ji Choi"
format:
  revealjs:
    embed-resources: true
    scrollable: true
    transition: slide
    controls-layout: bottom-right
    menu: true
    toc: true
    toc-depth: 1
    fontsize: 15
    number-sections: true
---


```{r include = F}
library(jsonlite)
library(aws.s3)
library(knitr)
library(dplyr)
library(kableExtra)
library(tidyverse)
library(lmerTest)
library(emmeans)
library(broom)
library(ggbeeswarm)
library(lemon)
library(quantreg)
library(readxl)
library(growthcleanr)
library(ggbreak)
library(janitor)   # for tabyl/adorn helpers
library(forcats)   # for fct_relevel (optional but nice)


source("~/GitHub/CHCO-Code/Petter Bjornstad/Resources/YC/R Functions/correlation_function.R")
source("~/GitHub/CHCO-Code/Petter Bjornstad/ATTEMPT/attempt_functions.R")
source("~/GitHub/CHCO-Code/Petter Bjornstad/Renal HEIRitage/RH_RH2_IMPROVE_functions.R")
```

```{r include = F}
## Create an S3 client
keys <- fromJSON("/Users/choiyej/Library/CloudStorage/OneDrive-TheUniversityofColoradoDenver/Bjornstad Pyle Lab/keys.json")

Sys.setenv(
  "AWS_ACCESS_KEY_ID" = keys$MY_ACCESS_KEY,
  "AWS_SECRET_ACCESS_KEY" = keys$MY_SECRET_KEY,
  "AWS_DEFAULT_REGION" = "",
  "AWS_REGION" = "",
  "AWS_S3_ENDPOINT" = "s3.kopah.uw.edu"
)
```

```{r echo = F}
harm_dat <- read.csv("/Users/choiyej/Library/CloudStorage/OneDrive-SharedLibraries-UW/Laura Pyle - Bjornstad/Biostatistics Core Shared Drive/Data Harmonization/Data Clean/harmonized_dataset.csv", na.strings = "")

harm_dat_collapsed <- harm_dat %>%
  group_by(record_id, visit) %>%
  fill(date, .direction = "updown") %>% ungroup() %>%
  dplyr::summarise(across(where(negate(is.numeric)), ~ ifelse(all(is.na(.x)), NA_character_, last(na.omit(.x)))),
                   across(where(is.numeric), ~ ifelse(all(is.na(.x)), NA_real_, mean(.x, na.rm = TRUE))),
                   .by = c(record_id, visit)) %>%
  dplyr::mutate(race_ethnicity_condensed = case_when(race == "White" &
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino White",
                                                     race == "Black or African American" &
                                                       ethnicity == "Not Hispanic or Latino" ~ "Not Hispanic or Latino Black",
                                                     ethnicity == "Hispanic or Latino" ~ "Hispanic or Latino",
                                                     T ~ "Not Hispanic or Latino Other")) %>%
  arrange(record_id) %>%
  mutate(agem = age*12)

# subset(harm_dat, eGFR_CKD_epi < 40)$record_id
```

```{r echo = F}
# RH/RH2 subset
rh_rh2_croc_panther <- harm_dat_collapsed %>% 
  filter(study %in% c("RENAL-HEIR", "RENAL-HEIRitage", "CROCODILE", "PANTHER")) %>%
  filter(group %in% c("Type 2 Diabetes", "Obese Control", "Lean Control")) %>%
  filter(visit == "baseline")

bmi_percentile = ext_bmiz(data = subset(rh_rh2_croc_panther, 
                                        select = c("record_id", "sex", "agem", "weight", "height", "bmi")),
                          wt = "weight", ht = "height") %>%
  dplyr::select(record_id, bmip)
  
rh_rh2_croc_panther_unique <- rh_rh2_croc_panther %>%
  left_join(bmi_percentile) %>%
  arrange(mrn, date) %>%
  distinct(mrn, date, .keep_all = TRUE) %>%
  group_by(mrn) %>%
  mutate(
    date = as.Date(date),
    date_diff_days = case_when(is.na(lag(date)) ~ 0, 
                               T ~ as.numeric(difftime(date, lag(date), units = "days"))),
    date_diff_years = date_diff_days/365,
    new_cluster = if_else(is.na(lag(date)) | date_diff_days > 7,
                          1, 0),
    cluster_id = cumsum(replace_na(new_cluster, 1))
  ) %>%
  group_by(mrn, cluster_id) %>%
  slice_min(order_by = date, with_ties = FALSE) %>%
  ungroup() %>%
  #stratify T2D and OB in RH/RH2 by UACR >= 100 mg/g and look at the kidney MRI parameters.. I want to include some of this preliminary data in my slides for Spain
  # eGFR <60 for eGFR_CKD_epi AND/OR UACR>= 100 mg/g
  # in other words, to be in the high risk group EITHER eGFR <60 AND/OR UACR>= 100mg/g
  # so if you have UACR >= 100 mg/g but eGFR >60 you qualify, or if you have UACR <100 but eGFR <60 you qualify, and if you have both, i.e., UACR >= 100 and eGFR <60 you qualify
  mutate(uacr_100 = case_when(acr_u >= 100 ~ "UACR >=100 mg/g",
                              acr_u < 100 ~ "UACR <100 mg/g"),
         uacr_group = case_when(eGFR_CKD_epi < 75 | acr_u >= 100 ~ "eGFR < 75 and/or UACR >=100 mg/g",
                                eGFR_CKD_epi >=75 | acr_u < 100 ~ "eGFR >= 75 and UACR <100 mg/g"),
         uacr_group = factor(uacr_group, levels = c("eGFR >= 75 and UACR <100 mg/g",
                                                    "eGFR < 75 and/or UACR >=100 mg/g")),
         # eGFR categories
         egfr_cat = case_when(
           eGFR_CKD_epi < 60                      ~ "<60",
           eGFR_CKD_epi >= 60 & eGFR_CKD_epi < 90 ~ "60–<90",
           eGFR_CKD_epi >= 90                     ~ "≥90",
           TRUE ~ NA_character_
         ),
         egfr_cat = factor(egfr_cat, levels = c("<60", "60–<90", "≥90")),
         # ACR categories
         acr_u_cat3 = case_when(
           acr_u < 30                  ~ "<30",
           acr_u >= 30 & acr_u < 300   ~ "30–<300",
           acr_u >= 300                ~ "≥300",
           TRUE ~ NA_character_
         ),
         acr_u_cat3 = factor(acr_u_cat3, levels = c("<30", "30–<300", "≥300")),
         bmi_cat = case_when(
           # Adults (≥18 years)
           age >= 18 & bmi < 25                ~ "Lean",
           age >= 18 & bmi >= 25 & bmi < 30    ~ "Overweight",
           age >= 18 & bmi >= 30               ~ "Obese",
           
           # Pediatrics (<18 years)
           age < 18 & bmip < 85      ~ "Lean",
           age < 18 & bmip >= 85 & bmip < 95 ~ "Overweight",
           age < 18 & bmip >= 95     ~ "Obese",
           
           TRUE ~ NA_character_
         ),
         bmi_cat = factor(
           bmi_cat,
           levels = c("Lean", "Overweight", "Obese")
         ),
         group_risk = case_when(bmip >= 95 | hba1c >=6 | group == "Type 2 Diabetes" ~ "High",
                                bmip < 85 & hba1c <=5.6 ~ "Low"),
         tkv_combined = coalesce(total_kidney_volume_ml, total_kidney_volume_ml_manual),
         htadjtkv_combined = coalesce(ht_adj_tkv, ht_adj_tkv_manual),
  )

rh_rh2_unique <- rh_rh2_croc_panther_unique %>%
  filter(group %nin% c("Lean Control")) %>%
  filter(study != "PANTHER")

rh_rh2_unique_follow_up <- rh_rh2_unique %>%
  group_by(mrn) %>%
  filter(n() > 1) %>%
  ungroup() %>%
  mutate(study_visit = case_when(study == "RENAL-HEIR" ~ "Baseline",
                                 T ~ "Follow up"))
rh_rh2_unique_follow_up$log_uacr <- log(rh_rh2_unique_follow_up$acr_u)

# delta dataframe
clinical_vars <- c("eGFR_CKD_epi", "eGFR_fas_cr", "gfr_bsa_plasma", "erpf_bsa_plasma", 
                   "htadjtkv_combined", "log_uacr")
rh_rh2_delta <- rh_rh2_unique_follow_up %>%
  # Pivot wider to get baseline and follow-up in separate columns
  pivot_wider(
    id_cols = mrn,
    names_from = study_visit,
    values_from = all_of(clinical_vars),
    names_sep = "_"
  ) %>%
  
  # Calculate deltas (follow-up - baseline)
  mutate(
    delta_gfr_bsa_plasma = `gfr_bsa_plasma_Follow up` - gfr_bsa_plasma_Baseline,
    delta_eGFR_CKD_epi = `eGFR_CKD_epi_Follow up` - eGFR_CKD_epi_Baseline,
    delta_eGFR_fas_cr = `eGFR_fas_cr_Follow up` - eGFR_fas_cr_Baseline,
    delta_erpf_bsa_plasma = `erpf_bsa_plasma_Follow up` - erpf_bsa_plasma_Baseline,
    delta_htadjtkv_combined = `htadjtkv_combined_Follow up` - htadjtkv_combined_Baseline,
    delta_log_uacr = `log_uacr_Follow up` - log_uacr_Baseline
  ) %>%
  dplyr::select(mrn, starts_with("delta_"), ends_with("Baseline")) 
 
rh_rh2_unique_follow_up <- rh_rh2_unique_follow_up %>%
  left_join(rh_rh2_delta) %>%
  mutate(
    across(
      starts_with("delta_"),
      ~ ifelse(study == "RENAL-HEIR", 0, .x)
    )
  )
```

# Descriptive tables

## RH & RH2 combined

```{r echo = F, results = 'asis'}
# everyone
summary(arsenal::tableby(study ~ age + sex + bmi + group + uacr_group + diabetes_duration + sbp + dbp + hba1c + gfr_bsa_plasma + erpf_bsa_plasma + htadjtkv_combined + avg_c_r2 + avg_m_r2  + avg_k_r2 + avg_c_fsoc + avg_m_fsoc + avg_c_r2 + avg_c_adc + avg_pcascl, data = rh_rh2_unique, digits = 1))
```

## Limited to those with paired data

```{r echo = F, results = 'asis'}
# RH follow up
# determine follow up by screen date and MRN
summary(arsenal::tableby(study_visit ~ age + sex + bmi + group + uacr_group + diabetes_duration + sbp + dbp + hba1c + gfr_bsa_plasma + erpf_bsa_plasma + date_diff_years + htadjtkv_combined + avg_c_r2 + avg_k_r2 + avg_c_adc + avg_pcascl + acr_u_cat3 + kwt(acr_u, "medianq1q3"), data = rh_rh2_unique_follow_up, digits = 1))
```

## RH2 only
```{r echo = F, results = 'asis'}
summary(arsenal::tableby(uacr_group ~ age + sex + bmi + group + diabetes_duration + sbp + dbp + hba1c + gfr_bsa_plasma + erpf_bsa_plasma  + htadjtkv_combined + avg_c_r2 + avg_k_r2 + avg_c_adc + avg_pcascl, data = subset(rh_rh2_unique, study == "RENAL-HEIRitage"), digits = 1))
```

# Plots

## Paired RH vs. RH2

```{r warning = F, results = 'asis'}
# Paired RH vs. RH2 follow up
# mGFR
create_comparison_boxplot(
  data = rh_rh2_unique_follow_up,
  x_var = "study_visit",
  y_var = "gfr_bsa_plasma",
  y_label = "GFR",
  y_buffer = 20,
  paired = TRUE,
  show_lines = TRUE,
  comparisons = list(c("Baseline", "Follow up")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.format"
)

# 3) ERPF
create_comparison_boxplot(
  data = rh_rh2_unique_follow_up,
  x_var = "study_visit",
  y_var = "erpf_bsa_plasma",
  y_label = "ERPF",
  y_buffer = 50,
  paired = TRUE,
  show_lines = TRUE,
  comparisons = list(c("Baseline", "Follow up")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.format"
)

# 4) Height-adjusted TKV
create_comparison_boxplot(
  data = rh_rh2_unique_follow_up,
  x_var = "study_visit",
  y_var = "htadjtkv_combined",
  y_label = "Height adjusted TKV",
  y_buffer = 20,
  paired = TRUE,
  show_lines = TRUE,
  comparisons = list(c("Baseline", "Follow up")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.signif"
)

# 5) UACR
create_comparison_boxplot(
  data = rh_rh2_unique_follow_up,
  x_var = "study_visit",
  y_var = "log_uacr",
  y_label = "log(UACR)",
  y_buffer = 1.5,
  paired = TRUE,
  show_lines = TRUE,
  comparisons = list(c("Baseline", "Follow up")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.format"
)

create_comparison_boxplot(
  data = rh_rh2_unique_follow_up,
  x_var = "study_visit",
  y_var = "avg_k_r2",
  y_label = "Kidney R2*",
  y_buffer = 1.5,
  paired = TRUE,
  show_lines = TRUE,
  comparisons = list(c("Baseline", "Follow up")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.format"
)

create_comparison_boxplot(
  data = rh_rh2_unique,
  x_var = "study",
  y_var = "avg_k_r2",
  y_label = "Kidney R2*",
  y_buffer = 5,
  paired = F,
  show_lines = F,
  comparisons = list(c("RENAL-HEIR", "RENAL-HEIRitage")),
  p_label_size = 12,
  text_size = 20,
  p_format = "p.format"
)
```

## Deltas

```{r}
# deltas
plot_mean_ci_stars_renal(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_gfr_bsa_plasma",
  y_axis_title = "\u0394mGFR",
  x_var = "study_visit",
  studys_to_plot = c("Baseline", "Follow up"),
  group_var = "uacr_group",
  test_method = "t.test",
  paired = FALSE,  # Set to FALSE if data isn't truly paired
  show_individual_points = TRUE,
  colors = c("#f7b538", "#f28482")
)
plot_mean_ci_continuous_time(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_gfr_bsa_plasma",
  time_var = "date_diff_years",  
  y_axis_title = "\u0394mGFR",
  group_var = "uacr_group",
  show_individual_lines = T
)

plot_mean_ci_stars_renal(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_erpf_bsa_plasma",
  y_axis_title = "\u0394ERPF",
  x_var = "study_visit",
  studys_to_plot = c("Baseline", "Follow up"),
  group_var = "uacr_group",
  test_method = "t.test",
  paired = FALSE,  # Set to FALSE if data isn't truly paired
  show_individual_points = TRUE,
  colors = c("#f7b538", "#f28482")
)
plot_mean_ci_continuous_time(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_erpf_bsa_plasma",
  time_var = "date_diff_years",  
  y_axis_title = "\u0394ERPF",
  group_var = "uacr_group",
  show_individual_lines = T
)

plot_mean_ci_stars_renal(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_htadjtkv_combined",
  y_axis_title = "\u0394Height adjusted TKV",
  x_var = "study_visit",
  studys_to_plot = c("Baseline", "Follow up"),
  group_var = "uacr_group",
  test_method = "t.test",
  paired = FALSE,  # Set to FALSE if data isn't truly paired
  show_individual_points = TRUE,
  colors = c("#f7b538", "#f28482")
)
plot_mean_ci_continuous_time(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_htadjtkv_combined",
  time_var = "date_diff_years",  
  y_axis_title = "\u0394Height adjusted TKV",
  group_var = "uacr_group",
  show_individual_lines = T
)

plot_mean_ci_stars_renal(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_log_uacr",
  y_axis_title = "\u0394log(UACR)",
  x_var = "study_visit",
  studys_to_plot = c("Baseline", "Follow up"),
  group_var = "uacr_group",
  test_method = "t.test",
  paired = FALSE,  # Set to FALSE if data isn't truly paired
  show_individual_points = TRUE,
  colors = c("#f7b538", "#f28482")
)
plot_mean_ci_continuous_time(
  data = rh_rh2_unique_follow_up,
  y_var = "delta_log_uacr",
  time_var = "date_diff_years",  
  y_axis_title = "\u0394log(UACR)",
  group_var = "uacr_group",
  show_individual_lines = T
)
```

## RH2 only (further along in disease)

```{r warning = F}
rh2_unique <- rh_rh2_unique %>%
  filter(study == "RENAL-HEIRitage")
# Unpaired in RH2 (CKD)
# 2) mGFR
create_comparison_boxplot(
  data = rh2_unique,
  x_var = "uacr_group",
  y_var = "gfr_bsa_plasma",
  y_label = "mGFR",
  y_buffer = 10,
  paired = F,
  show_lines = F,
  comparisons = list(c("eGFR >= 75 and UACR <100 mg/g", 
                       "eGFR < 75 and/or UACR >=100 mg/g")),
  colors = c("#598392", "#d9ae94"),
  box_color = "black")


# 3) ERPF
create_comparison_boxplot(
  data = rh2_unique,
  x_var = "uacr_group",
  y_var = "erpf_bsa_plasma",
  y_label = "ERPF",
  y_buffer = 50,
  paired = F,
  show_lines = F,
  comparisons = list(c("eGFR >= 75 and UACR <100 mg/g", 
                       "eGFR < 75 and/or UACR >=100 mg/g")),
  colors = c("#598392", "#d9ae94"),
  box_color = "black")

# 4) Height-adjusted TKV
create_comparison_boxplot(
  data = rh2_unique,
  x_var = "uacr_group",
  y_var = "htadjtkv_combined",
  y_label = "Height adjusted TKV",
  y_buffer = 20,
  paired = F,
  show_lines = F,
  comparisons = list(c("eGFR >= 75 and UACR <100 mg/g", 
                       "eGFR < 75 and/or UACR >=100 mg/g")),
  colors = c("#598392", "#d9ae94"),
  box_color = "black")


```
