---
title: "RENAL HEIR Lipidomics"
author: "Henry Mangalapalli"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
## Not sure if this is the best place for the project to be rooted...
# knitr::opts_chunk$set(root.dir = "C:\\Users\\Henry Mangalapalli\\OneDrive\\Henry - UW\\Laura Pyle's files - Biostatistics Core Shared Drive\\Renal HEIR\\Data_Raw")
### Save data & results to specific working directories like this:
# dir.dat <- c("/Users/hhampson/Library/CloudStorage/OneDrive-UW/Biostatistics Core Shared Drive")
# dir.results <- c("/Users/hhampson/Library/CloudStorage/OneDrive-UW/Biostatistics Core Shared Drive/Liver Project/NEBULA Results")
# write.csv(results,fs::path(dir.results,”Filename.csv”)) for saving files
# saveRDS(results,fs::path(dir.results,”Results”,”Filename.rds”)) for saving files to folder within dir.results
```

Code adapted from CROCODILE Lipidomics analysis to use lipidr package.
```{r}
#| include: false
library(tidyverse)
library(magrittr)
library(table1)
library(emmeans)
library(broom)
library(kableExtra)
library(arsenal)
library(olsrr)
library(data.table)
library(lipidr)
library(rgoslin)
library(LipidMS)
library(limma)
library(SummarizedExperiment)
library(labelled)
library(plotly)
library(knitr)
library(ggrepel)
library(data.table)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(kableExtra)
library(lipidomeR)
library(writexl)
source("C:/Users/Henry Mangalapalli/Documents/GitHub/CHCO-Code/Petter Bjornstad/CROCODILE/lipidr_unadj_function_R.R")


# library(MetaboAnalystR)
```

## Read in ALL the data for Renal HEIR
```{r, include=F}
dat <- read.csv("C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Data Harmonization/Data Clean/harmonized_dataset.csv")

rh_lipids_raw <- read.csv("C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR/Data_Raw/renal_heir_lipidomics.csv")
rh_lipids_name <- read.csv("C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR/Data_Raw/renal_heir_lipidomics_name.csv")

# Harmonized dataset contains data from ALL studies, thus why we have to separate out by Renal HEIR later on
dict <- read.csv("C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Data Harmonization/data_dictionary_master.csv", na.strings = c(" ", "", "-9999",-9999)) %>%
  select(variable_name, label)
```


```{r, include=F}
# Remove unnecessary rows/columns from rh_lipids_raw
rh_lipids_raw <- rh_lipids_raw[-c(1:2),-c(1:3)]
rh_lipids_raw <- rh_lipids_raw[-c(1),]
rh_lipids_raw <- rh_lipids_raw[,-c(1)]

# Remove polarity column from rh_lipids_name
rh_lipids_name <-rh_lipids_name[, -c(4)]

# Add variable_name column to rh_lipids_raw
rh_lipids_raw[[ "variable_name" ]] <- rh_lipids_name[[ "variable_name" ]]

# Move variable_name to first column
rh_lipids_raw <- rh_lipids_raw[ , c("variable_name", setdiff(names(rh_lipids_raw), "variable_name"))]

# Make both sheets dataframes
rh_lipids_raw <- as.data.frame(rh_lipids_raw)
rh_lipids_name <- as.data.frame(rh_lipids_name)

# Removing 1st column from lipids_raw in lipids_dat & setting column names to come from that 1st column.
# Converting row names to column called "variable_name"
# Joining lipids_name & lipids_raw at "variable_name" and "standardized_name_w_adduct" column
lipids_dat <- left_join(
  subset(rh_lipids_name, select = c("variable_name", "standardized_name")),
  rh_lipids_raw,
  by = "variable_name"
) # Contains ALL rows, including those without a standardized name

# Parsing out lipid names from the standardized_name_w_adduct column in lipids_name
parsed <- parseLipidNames(lipids_dat$standardized_name)
```

```{r}
# Save lipids_dat as a copycat of renal_heir_lipidomics 
raw_data_wd <- "C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR"
setwd(raw_data_wd)
lipids_dat <- as.data.frame(lipids_dat)
write_xlsx(lipids_dat, "lipids_dat.xlsx")
```


```{r}
# Save parsed lipids to raw_data_wd
raw_data_wd <- "C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR"
setwd(raw_data_wd)
parsed <- as.data.frame(parsed)
write_xlsx(parsed, "parsed.xlsx")
```

## Purpose of these chunks is to remove all "-" values from standardized names so I can go on and delete duplicates
```{r}
# Remove any rows where standardized_name = "-"; OPTIONAL
lipids_dat_full <- lipids_dat[lipids_dat$standardized_name != "-", ]

parsed_full <- parseLipidNames(lipids_dat_full$standardized_name)

```

```{r}
raw_data_wd <- "C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR"
setwd(raw_data_wd)
parsed_full <- as.data.frame(parsed_full)
write_xlsx(parsed_full, "parsed_full.xlsx")

lipids_dat_full <- as.data.frame(lipids_dat_full)
write_xlsx(lipids_dat_full, "lipids_dat_full.xlsx")
```

## Non-parsed lipids
```{r Remove non-parsed lipids}
# Separate out non-parsed lipids
non_parsed_rh <- parsed_full[parsed_full$Grammar == "NOT_PARSEABLE",]

# Save non-parsed lipids to raw_data_wd
raw_data_wd <- "C:/Users/Henry Mangalapalli/UW/OneDrive - UW/Laura Pyle's files - Biostatistics Core Shared Drive/Renal HEIR"
setwd(raw_data_wd)
non_parsed_rh <- as.data.frame(non_parsed_rh)
write_xlsx(non_parsed_rh, "non_parsed_rh.xlsx")
```

##### Continue with analysis here. Beyond this, it's purely analysis; no more duplicate deleting #####
## Make sheet with ONLY parseable lipids 
```{r}
# Re-make parsed_rh sheet without non-parsed lipids
parsed_only <- parsed_full[parsed_full$Grammar != "NOT_PARSEABLE",]
```


```{r}
# Convert lipids_dat into a lipidomics experiment object
parsed_only <- as_lipidomics_experiment(parsed_only)
```
