setwd('G:/My Drive/lab files/Bryan Bergman/cohort 11-8-24 CAT VAT SAT')
folder_names = as.data.frame(list.files('./kallisto_outs/'))
colnames(folder_names) = 'folder_name'

#note need to run first co,and for first file:

f1 = read.delim('./kallisto_outs/52_CAT_3_S3/abundance.tsv')
f1$sample = paste0('52_CAT_3_S3')
full_melted_cnts =  as.data.frame(f1)
f1 = read.delim('./kallisto_outs/52_SAT_1_S1/abundance.tsv')
f1$sample = paste0('52_SAT_1_S1')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/52_VAT_2_S2/abundance.tsv')
f1$sample = paste0('52_VAT_2_S2')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/60_CAT_27_S27/abundance.tsv')
f1$sample = paste0('60_CAT_27_S27')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/60_SAT_25_S25/abundance.tsv')
f1$sample = paste0('60_SAT_25_S25')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/60_VAT_26_S26/abundance.tsv')
f1$sample = paste0('60_VAT_26_S26')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/69_CAT_6_S6/abundance.tsv')
f1$sample = paste0('69_CAT_6_S6')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/69_SAT_4_S4/abundance.tsv')
f1$sample = paste0('69_SAT_4_S4')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/69_VAT_5_S5/abundance.tsv')
f1$sample = paste0('69_VAT_5_S5')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/70_CAT_9_S9/abundance.tsv')
f1$sample = paste0('70_CAT_9_S9')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/70_SAT_7_S7/abundance.tsv')
f1$sample = paste0('70_SAT_7_S7')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/70_VAT_8_S8/abundance.tsv')
f1$sample = paste0('70_VAT_8_S8')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/71_CAT_30_S30/abundance.tsv')
f1$sample = paste0('71_CAT_30_S30')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/71_SAT_28_S28/abundance.tsv')
f1$sample = paste0('71_SAT_28_S28')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/71_VAT_29_S29/abundance.tsv')
f1$sample = paste0('71_VAT_29_S29')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/72_CAT_33_S33/abundance.tsv')
f1$sample = paste0('72_CAT_33_S33')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/72_SAT_31_S31/abundance.tsv')
f1$sample = paste0('72_SAT_31_S31')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/72_VAT_32_S32/abundance.tsv')
f1$sample = paste0('72_VAT_32_S32')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/73_CAT_12_S12/abundance.tsv')
f1$sample = paste0('73_CAT_12_S12')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/73_SAT_10_S10/abundance.tsv')
f1$sample = paste0('73_SAT_10_S10')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/73_VAT_11_S11/abundance.tsv')
f1$sample = paste0('73_VAT_11_S11')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/74_CAT_15_S15/abundance.tsv')
f1$sample = paste0('74_CAT_15_S15')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/74_SAT_13_S13/abundance.tsv')
f1$sample = paste0('74_SAT_13_S13')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/74_VAT_14_S14/abundance.tsv')
f1$sample = paste0('74_VAT_14_S14')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/75_CAT_18_S18/abundance.tsv')
f1$sample = paste0('75_CAT_18_S18')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/75_SAT_16_S16/abundance.tsv')
f1$sample = paste0('75_SAT_16_S16')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/75_VAT_17_S17/abundance.tsv')
f1$sample = paste0('75_VAT_17_S17')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/76_CAT_36_S36/abundance.tsv')
f1$sample = paste0('76_CAT_36_S36')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/76_SAT_34_S34/abundance.tsv')
f1$sample = paste0('76_SAT_34_S34')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/76_VAT_35_S35/abundance.tsv')
f1$sample = paste0('76_VAT_35_S35')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/77_CAT_24_S24/abundance.tsv')
f1$sample = paste0('77_CAT_24_S24')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/77_SAT_22_S22/abundance.tsv')
f1$sample = paste0('77_SAT_22_S22')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/77_VAT_23_S23/abundance.tsv')
f1$sample = paste0('77_VAT_23_S23')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/78_CAT_39_S39/abundance.tsv')
f1$sample = paste0('78_CAT_39_S39')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/78_SAT_37_S37/abundance.tsv')
f1$sample = paste0('78_SAT_37_S37')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/78_VAT_38_S38/abundance.tsv')
f1$sample = paste0('78_VAT_38_S38')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/79_CAT_21_S21/abundance.tsv')
f1$sample = paste0('79_CAT_21_S21')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/79_SAT_19_S19/abundance.tsv')
f1$sample = paste0('79_SAT_19_S19')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/79_VAT_20_S20/abundance.tsv')
f1$sample = paste0('79_VAT_20_S20')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/84_CAT_42_S42/abundance.tsv')
f1$sample = paste0('84_CAT_42_S42')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/84_SAT_40_S40/abundance.tsv')
f1$sample = paste0('84_SAT_40_S40')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))
f1 = read.delim('./kallisto_outs/84_VAT_41_S41/abundance.tsv')
f1$sample = paste0('84_VAT_41_S41')
full_melted_cnts =  as.data.frame(rbind(full_melted_cnts, f1))

head(full_melted_cnts)
library(biomaRt)
mart <- useMart("ensembl","hsapiens_gene_ensembl")
vec1 = unique(full_melted_cnts$target_id)
vec1[1:100]
ensemble2gene <- getBM(attributes=c("hgnc_symbol","entrezgene_id","chromosome_name","start_position","end_position", "ensembl_transcript_id_version", "ensembl_transcript_id"),
                       filters = "ensembl_transcript_id_version",
                       values = vec1, 
                       mart = mart)
full_melted_cnts$gene_symbol = ensemble2gene$hgnc_symbol[match(full_melted_cnts$target_id, ensemble2gene$ensembl_transcript_id_version)]
full_melted_cnts$entrezgene_id = ensemble2gene$entrezgene_id[match(full_melted_cnts$target_id, ensemble2gene$ensembl_transcript_id_version)]
length(unique(full_melted_cnts$gene_symbol))
write.csv(full_melted_cnts, file = 'full melted kallisto counts and tpm.csv', row.names = F)
head(full_melted_cnts)
library(reshape2)
library(dplyr)
cnts1 = dcast(full_melted_cnts, gene_symbol ~ sample, value.var = 'est_counts', fun.aggregate = as.integer(mean), na.rm=T)

write.csv(cnts1, file = 'gene-level counts matrix.csv', row.names = F)
full_melted_cnts = read.csv('full melted kallisto counts and tpm.csv')
cnts_tpm = dcast(full_melted_cnts, gene_symbol ~ sample, value.var = 'tpm', fun.aggregate = mean, na.rm=T)
